//+------------------------------------------------------------------+
//|                                                 Buy_And_Hold.mq5 |
//|                                      Auto-generated by Assistant |
//+------------------------------------------------------------------+
#property copyright "Vu"
#property link      ""
#property version   "1.00"
#property description "Chỉ vào duy nhất 1 lệnh BUY khi bắt đầu, không có TP/SL"

#include <Trade\Trade.mqh>
CTrade trade;

input group "=== Cài Đặt Chung ==="
input double InpLotSize     = 0.01;      // Khối lượng lệnh (Lot Size)
input ulong  InpMagicNumber = 999999;    // Magic Number

bool g_has_traded = false;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   trade.SetExpertMagicNumber(InpMagicNumber);
   g_has_traded = false;
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   // Nếu đã trade rồi thì không làm gì nữa, tiết kiệm thuật toán
   if(g_has_traded) return;
   
   // Kiểm tra xem đã có vị thế nào của con EA này chưa (đề phòng tắt bật lại)
   bool position_exists = false;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      string symbol = PositionGetSymbol(i);
      if(symbol == _Symbol && PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
        {
         position_exists = true;
         break;
        }
     }
   
   // Nếu chưa có lệnh thì mở 1 lệnh BUY duy nhất
   if(!position_exists)
     {
      double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      if(trade.Buy(InpLotSize, _Symbol, ask, 0, 0, "Buy and Hold"))
        {
         Print("Đã vào lệnh BUY And Hold thành công lúc bắt đầu.");
         g_has_traded = true; // Đánh dấu là đã trade
        }
      else
        {
         Print("Lỗi vào lệnh: ", GetLastError());
        }
     }
   else
     {
      // Nếu bật EA lên mà thấy có lệnh ở đó rồi thì đánh dấu luôn
      g_has_traded = true;
     }
  }
//+------------------------------------------------------------------+
