//+------------------------------------------------------------------+
//|                                                  darvas_cvd.mq5  |
//|                                  Copyright 2024, Vu (Antigravity)|
//+------------------------------------------------------------------+
#property copyright "Vu - Generated by AI"
#property link      "https://antigravity.ide"
#property version   "1.00"
#property description "Darvas Box Breakout + Detrended CVD Filter + EMA D1"
#property description "Buy: CVD>0 & Close>EMA(D1) | Sell: CVD<0 & Close<EMA(D1)"

#include <Trade\Trade.mqh>
CTrade trade;

//--- inputs
input group "=== General Settings ==="
input double InpFixLot        = 0.01;    // Fixed Lot Size
input ulong  InpMagicNumber   = 44445;   // Magic Number
input int    InpSlippage       = 3;       // Slippage (points)

input group "=== Darvas Box ==="
input int    InpConfirmBars    = 3;       // Bars to confirm Top/Bottom

input group "=== Entry Settings ==="
input double InpEntryPadPips   = 2.0;     // Entry Pad from Box Top/Bottom (pips)
input bool   InpAddSpread      = true;    // Add Spread to Buy Stop

input group "=== Stop Loss ==="
input double InpSLPadPips      = 2.0;     // SL Pad outside Box (pips)

input group "=== Risk Settings ==="
input double InpMaxLossUSD     = 0;       // Max Floating Loss ($, 0=off)

input group "=== CVD Filter ==="
input int    InpCVDLength      = 100;     // CVD Z-Score Window Size
input double InpCVDLimitStd    = 2.0;     // CVD Standard Deviation Limit
input int    InpCVDSignalEma   = 9;       // CVD Signal Line EMA Period
input bool   InpCVDUseRealVol  = false;   // Use Real Volume (False = Tick Volume)

input group "=== EMA D1 Trend Filter ==="
input bool   InpUseEMAFilter   = true;    // Enable EMA D1 Filter
input int    InpEMAPeriod      = 200;     // EMA Period (on D1)
input ENUM_MA_METHOD InpEMAMethod = MODE_EMA; // MA Method

input group "=== Display Settings ==="
input color  ClrBoxBuy         = clrDodgerBlue;   // Box Color (Buy bias)
input color  ClrBoxSell        = clrOrangeRed;     // Box Color (Sell bias)
input color  ClrBoxNeutral     = clrGold;          // Box Color (Neutral)
input color  ClrSLLine         = clrCrimson;       // Stop Loss Line
input color  ClrTrailLine      = clrLime;          // Trailing SL

//--- Box building state machine
enum ENUM_BOX_STATE { STATE_FIND_TOP, STATE_FIND_BOTTOM };

ENUM_BOX_STATE g_state           = STATE_FIND_TOP;
double   g_candidateTop          = 0;
int      g_topConfirmCount       = 0;
double   g_trackMinLow           = DBL_MAX;   // Min low during top confirmation
datetime g_candidateTopTime      = 0;

double   g_candidateBottom       = 0;
int      g_bottomConfirmCount    = 0;
datetime g_candidateBottomTime   = 0;

// Active box
double   g_boxTop                = 0;
double   g_boxBottom             = 0;
int      g_boxNumber             = 0;

// Pending & position tracking
datetime g_lastBarTime           = 0;
ulong    g_pendingBuyTicket      = 0;
ulong    g_pendingSellTicket     = 0;

// CVD Buffers (internal calculation)
double   g_cvdRaw[];             // Raw cumulative CVD
double   g_cvdZScore[];          // Z-Score of CVD
double   g_cvdSignal[];          // Signal line (EMA of Z-Score)
int      g_cvdSize               = 0;

// EMA D1 handle
int      g_emaHandle             = INVALID_HANDLE;

//+------------------------------------------------------------------+
double PipsToPrice(double pips) {
   int digits = (int)SymbolInfoInteger(Symbol(), SYMBOL_DIGITS);
   if(digits == 5 || digits == 3)
      return pips * 10.0 * SymbolInfoDouble(Symbol(), SYMBOL_POINT);
   else
      return pips * SymbolInfoDouble(Symbol(), SYMBOL_POINT);
}

//+------------------------------------------------------------------+
int OnInit() {
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   trade.SetTypeFilling(ORDER_FILLING_IOC);
   
   g_state = STATE_FIND_TOP;
   g_candidateTop = 0;
   g_topConfirmCount = 0;
   g_trackMinLow = DBL_MAX;
   g_boxNumber = 0;
   g_cvdSize = 0;
   
   // Pre-allocate CVD arrays
   ArrayFree(g_cvdRaw);
   ArrayFree(g_cvdZScore);
   ArrayFree(g_cvdSignal);
   
   // Create EMA handle on D1
   if(InpUseEMAFilter) {
      g_emaHandle = iMA(Symbol(), PERIOD_D1, InpEMAPeriod, 0, InpEMAMethod, PRICE_CLOSE);
      if(g_emaHandle == INVALID_HANDLE) {
         Print("[DV] ERROR: Failed to create EMA D1 handle!");
         return(INIT_FAILED);
      }
   }
   
   Print("=== Darvas Box + CVD Filter + EMA D1 EA Initialized ===");
   Print("Confirm Bars: ", InpConfirmBars,
         " | Entry Pad: ", InpEntryPadPips, " pips",
         " | SL Pad: ", InpSLPadPips, " pips");
   Print("CVD Window: ", InpCVDLength, " | Signal EMA: ", InpCVDSignalEma);
   Print("EMA D1 Filter: ", (InpUseEMAFilter ? "ON" : "OFF"),
         (InpUseEMAFilter ? " | Period: " + IntegerToString(InpEMAPeriod) : ""));
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
void OnDeinit(const int reason) {
   ObjectsDeleteAll(0, "DV_");
   ArrayFree(g_cvdRaw);
   ArrayFree(g_cvdZScore);
   ArrayFree(g_cvdSignal);
   if(g_emaHandle != INVALID_HANDLE) {
      IndicatorRelease(g_emaHandle);
      g_emaHandle = INVALID_HANDLE;
   }
}

//+------------------------------------------------------------------+
void DrawText(string name, datetime t, double price, string text, color clr) {
   ObjectCreate(0, name, OBJ_TEXT, 0, t, price);
   ObjectSetString(0, name, OBJPROP_TEXT, text);
   ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, name, OBJPROP_FONTSIZE, 9);
   ObjectSetString(0, name, OBJPROP_FONT, "Arial Bold");
}

void DrawRect(string name, datetime t1, double p1, datetime t2, double p2, color clr) {
   ObjectCreate(0, name, OBJ_RECTANGLE, 0, t1, p1, t2, p2);
   ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, name, OBJPROP_FILL, false);
   ObjectSetInteger(0, name, OBJPROP_BACK, true);
   ObjectSetInteger(0, name, OBJPROP_WIDTH, 2);
}

void DrawHLine(string name, datetime t1, datetime t2, double price, color clr, int style, int width) {
   ObjectCreate(0, name, OBJ_TREND, 0, t1, price, t2, price);
   ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, name, OBJPROP_STYLE, style);
   ObjectSetInteger(0, name, OBJPROP_WIDTH, width);
   ObjectSetInteger(0, name, OBJPROP_RAY_RIGHT, false);
   ObjectSetInteger(0, name, OBJPROP_BACK, true);
}

//+------------------------------------------------------------------+
bool HasOpenPosition(ENUM_POSITION_TYPE &pos_type) {
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      string symbol = PositionGetSymbol(i);
      if(symbol == Symbol() && PositionGetInteger(POSITION_MAGIC) == (long)InpMagicNumber) {
         pos_type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
         return true;
      }
   }
   return false;
}

void CloseAllPositions() {
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      string symbol = PositionGetSymbol(i);
      if(symbol == Symbol() && PositionGetInteger(POSITION_MAGIC) == (long)InpMagicNumber)
         trade.PositionClose(PositionGetTicket(i));
   }
}

double GetTotalFloatingPL() {
   double total = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      string symbol = PositionGetSymbol(i);
      if(symbol == Symbol() && PositionGetInteger(POSITION_MAGIC) == (long)InpMagicNumber)
         total += PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);
   }
   return total;
}

//+------------------------------------------------------------------+
void DeleteAllPendings() {
   for(int i = OrdersTotal() - 1; i >= 0; i--) {
      if(OrderSelect(OrderGetTicket(i))) {
         if(OrderGetString(ORDER_SYMBOL) == Symbol() &&
            OrderGetInteger(ORDER_MAGIC) == (long)InpMagicNumber) {
            trade.OrderDelete(OrderGetInteger(ORDER_TICKET));
         }
      }
   }
   g_pendingBuyTicket = 0;
   g_pendingSellTicket = 0;
}

bool HasAnyPending() {
   for(int i = OrdersTotal() - 1; i >= 0; i--) {
      if(OrderSelect(OrderGetTicket(i))) {
         if(OrderGetString(ORDER_SYMBOL) == Symbol() &&
            OrderGetInteger(ORDER_MAGIC) == (long)InpMagicNumber)
            return true;
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| Trail SL of open position to new level (1-way only)              |
//+------------------------------------------------------------------+
bool TrailSL(double new_sl) {
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      string symbol = PositionGetSymbol(i);
      if(symbol == Symbol() && PositionGetInteger(POSITION_MAGIC) == (long)InpMagicNumber) {
         ulong ticket = PositionGetTicket(i);
         double cur_sl = PositionGetDouble(POSITION_SL);
         double cur_tp = PositionGetDouble(POSITION_TP);
         ENUM_POSITION_TYPE ptype = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
         
         if(ptype == POSITION_TYPE_BUY && new_sl > cur_sl)
            return trade.PositionModify(ticket, NormalizeDouble(new_sl, _Digits), cur_tp);
         if(ptype == POSITION_TYPE_SELL && (cur_sl == 0 || new_sl < cur_sl))
            return trade.PositionModify(ticket, NormalizeDouble(new_sl, _Digits), cur_tp);
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| Calculate CVD Z-Score for all available bars                      |
//+------------------------------------------------------------------+
void CalculateCVD() {
   int bars = Bars(Symbol(), Period());
   if(bars < InpCVDLength) return;
   
   // Resize arrays if needed
   if(g_cvdSize != bars) {
      ArrayResize(g_cvdRaw, bars);
      ArrayResize(g_cvdZScore, bars);
      ArrayResize(g_cvdSignal, bars);
      
      // If first time or bars changed significantly, full recalc
      if(g_cvdSize == 0 || bars < g_cvdSize) {
         ArrayInitialize(g_cvdRaw, 0);
         ArrayInitialize(g_cvdZScore, 0);
         ArrayInitialize(g_cvdSignal, 0);
         g_cvdSize = 0; // Force full recalc
      }
   }
   
   int start = (g_cvdSize > 0) ? (g_cvdSize - 1) : 0;
   double alpha = 2.0 / (InpCVDSignalEma + 1.0);
   
   for(int i = start; i < bars; i++) {
      // Bar index in iClose etc. is (bars - 1 - i) for chronological order
      // But we store in chronological order: index 0 = oldest, index bars-1 = newest
      int bar_shift = bars - 1 - i;
      
      double o = iOpen(Symbol(), Period(), bar_shift);
      double c = iClose(Symbol(), Period(), bar_shift);
      double vol;
      if(InpCVDUseRealVol)
         vol = (double)iVolume(Symbol(), Period(), bar_shift);
      else
         vol = (double)iTickVolume(Symbol(), Period(), bar_shift);
      
      // === 1. Raw Delta ===
      double tick_delta = 0;
      if(c > o)
         tick_delta = vol;
      else if(c < o)
         tick_delta = -vol;
      
      // Cumulative CVD
      g_cvdRaw[i] = (i > 0 ? g_cvdRaw[i-1] : 0.0) + tick_delta;
      
      // === 2. Z-Score ===
      double z_cvd = 0.0;
      if(i >= InpCVDLength - 1) {
         double sum = 0.0;
         int wStart = i - InpCVDLength + 1;
         for(int j = wStart; j <= i; j++)
            sum += g_cvdRaw[j];
         
         double mean_cvd = sum / InpCVDLength;
         
         double sum_sq = 0.0;
         for(int j = wStart; j <= i; j++) {
            double d = g_cvdRaw[j] - mean_cvd;
            sum_sq += d * d;
         }
         
         double std_cvd = MathSqrt(sum_sq / InpCVDLength);
         
         if(std_cvd > 0.0)
            z_cvd = (g_cvdRaw[i] - mean_cvd) / std_cvd;
      }
      
      g_cvdZScore[i] = z_cvd;
      
      // === 3. Signal Line (EMA of Z-Score) ===
      if(i == 0)
         g_cvdSignal[i] = z_cvd;
      else
         g_cvdSignal[i] = z_cvd * alpha + g_cvdSignal[i-1] * (1.0 - alpha);
   }
   
   g_cvdSize = bars;
}

//+------------------------------------------------------------------+
//| Get current CVD Z-Score value (most recent completed bar)         |
//+------------------------------------------------------------------+
double GetCurrentCVD() {
   if(g_cvdSize < 2) return 0.0;
   // Return the Z-Score of the last completed bar (index = size - 2)
   // because size-1 is the current forming bar
   return g_cvdZScore[g_cvdSize - 2];
}

//+------------------------------------------------------------------+
//| Check CVD filter: true if direction is allowed                    |
//+------------------------------------------------------------------+
bool IsCVDBuyAllowed() {
   double cvd = GetCurrentCVD();
   return (cvd > 0.0);
}

bool IsCVDSellAllowed() {
   double cvd = GetCurrentCVD();
   return (cvd < 0.0);
}

//+------------------------------------------------------------------+
//| EMA D1 Trend Filter                                               |
//+------------------------------------------------------------------+
double GetEMAD1Value() {
   if(!InpUseEMAFilter || g_emaHandle == INVALID_HANDLE) return 0.0;
   double ema_buf[1];
   if(CopyBuffer(g_emaHandle, 0, 1, 1, ema_buf) <= 0) return 0.0;
   return ema_buf[0];
}

bool IsEMABuyAllowed() {
   if(!InpUseEMAFilter) return true;  // Filter tắt → luôn cho phép
   double ema_val = GetEMAD1Value();
   if(ema_val == 0.0) return true;    // Không lấy được data → cho qua
   double close_d1 = iClose(Symbol(), PERIOD_D1, 1); // Close D1 bar trước
   return (close_d1 > ema_val);
}

bool IsEMASellAllowed() {
   if(!InpUseEMAFilter) return true;  // Filter tắt → luôn cho phép
   double ema_val = GetEMAD1Value();
   if(ema_val == 0.0) return true;    // Không lấy được data → cho qua
   double close_d1 = iClose(Symbol(), PERIOD_D1, 1); // Close D1 bar trước
   return (close_d1 < ema_val);
}

//+------------------------------------------------------------------+
//| Called when a new Darvas Box is confirmed                        |
//+------------------------------------------------------------------+
void OnBoxComplete(double boxTop, double boxBottom, datetime topTime) {
   g_boxTop = boxTop;
   g_boxBottom = boxBottom;
   g_boxNumber++;
   
   double entry_pad = PipsToPrice(InpEntryPadPips);
   double sl_pad    = PipsToPrice(InpSLPadPips);
   double ask       = SymbolInfoDouble(Symbol(), SYMBOL_ASK);
   double bid       = SymbolInfoDouble(Symbol(), SYMBOL_BID);
   double spread    = ask - bid;
   datetime now     = iTime(Symbol(), Period(), 0);
   
   double cvd_val = GetCurrentCVD();
   double ema_val = GetEMAD1Value();
   double close_d1 = iClose(Symbol(), PERIOD_D1, 1);
   
   bool cvd_buy   = IsCVDBuyAllowed();
   bool cvd_sell  = IsCVDSellAllowed();
   bool ema_buy   = IsEMABuyAllowed();
   bool ema_sell  = IsEMASellAllowed();
   
   bool buy_ok    = cvd_buy && ema_buy;
   bool sell_ok   = cvd_sell && ema_sell;
   
   Print("[DV] ══════════════════════════════════════");
   Print("[DV] ★ BOX #", g_boxNumber, " COMPLETE!");
   Print("[DV]   Top:    ", DoubleToString(boxTop, _Digits));
   Print("[DV]   Bottom: ", DoubleToString(boxBottom, _Digits));
   Print("[DV]   Range:  ", DoubleToString(boxTop - boxBottom, _Digits));
   Print("[DV]   CVD Z-Score: ", DoubleToString(cvd_val, 2),
         " | CVD Buy: ", (cvd_buy ? "YES" : "NO"),
         " | CVD Sell: ", (cvd_sell ? "YES" : "NO"));
   if(InpUseEMAFilter)
      Print("[DV]   EMA D1(", InpEMAPeriod, "): ", DoubleToString(ema_val, _Digits),
            " | Close D1: ", DoubleToString(close_d1, _Digits),
            " | EMA Buy: ", (ema_buy ? "YES" : "NO"),
            " | EMA Sell: ", (ema_sell ? "YES" : "NO"));
   Print("[DV]   FINAL → Buy: ", (buy_ok ? "YES" : "NO"),
         " | Sell: ", (sell_ok ? "YES" : "NO"));
   
   // === Draw the box with CVD-based color ===
   color box_clr = ClrBoxNeutral;
   if(buy_ok)       box_clr = ClrBoxBuy;
   else if(sell_ok) box_clr = ClrBoxSell;
   
   string box_name = "DV_Box_" + IntegerToString(g_boxNumber);
   DrawRect(box_name, topTime, boxTop, now, boxBottom, box_clr);
   
   string lbl_name = "DV_Lbl_" + IntegerToString(g_boxNumber);
   string lbl_text = "BOX #" + IntegerToString(g_boxNumber) +
                     " CVD:" + DoubleToString(cvd_val, 2);
   DrawText(lbl_name, topTime, boxTop + entry_pad, lbl_text, box_clr);
   
   // === Check position state ===
   ENUM_POSITION_TYPE pos_type;
   bool has_position = HasOpenPosition(pos_type);
   
   // --- If in position: TRAIL SL to new box level ---
   if(has_position) {
      if(pos_type == POSITION_TYPE_BUY) {
         double trail_sl = NormalizeDouble(boxBottom - sl_pad, _Digits);
         if(TrailSL(trail_sl)) {
            Print("[DV] ▲ Trail BUY SL → ", DoubleToString(trail_sl, _Digits),
                  " (Box #", g_boxNumber, " bottom)");
            string trl_name = "DV_Trail_" + IntegerToString(g_boxNumber);
            DrawHLine(trl_name, topTime, now, trail_sl, ClrTrailLine, STYLE_DASH, 1);
         }
      }
      if(pos_type == POSITION_TYPE_SELL) {
         double trail_sl = NormalizeDouble(boxTop + sl_pad + spread, _Digits);
         if(TrailSL(trail_sl)) {
            Print("[DV] ▼ Trail SELL SL → ", DoubleToString(trail_sl, _Digits),
                  " (Box #", g_boxNumber, " top)");
            string trl_name = "DV_Trail_" + IntegerToString(g_boxNumber);
            DrawHLine(trl_name, topTime, now, trail_sl, ClrTrailLine, STYLE_DASH, 1);
         }
      }
      return;
   }
   
   // --- No position: cancel old pendings & place new ones (CVD filtered) ---
   DeleteAllPendings();
   
   // BUY STOP above Box Top — only if CVD > 0
   if(buy_ok) {
      double buy_entry = NormalizeDouble(boxTop + entry_pad + (InpAddSpread ? spread : 0), _Digits);
      double buy_sl    = NormalizeDouble(boxBottom - sl_pad, _Digits);
      
      if(buy_entry > ask) {
         string cmt = StringFormat("DV_Buy_Box%d_CVD%.1f", g_boxNumber, cvd_val);
         if(trade.BuyStop(InpFixLot, buy_entry, Symbol(), buy_sl, 0, ORDER_TIME_GTC, 0, cmt)) {
            g_pendingBuyTicket = trade.ResultOrder();
            Print("[DV] ★ BUY STOP at ", DoubleToString(buy_entry, _Digits),
                  " | SL: ", DoubleToString(buy_sl, _Digits),
                  " | CVD: ", DoubleToString(cvd_val, 2));
            
            // Visuals
            string e_name = "DV_EntryB_" + IntegerToString(g_boxNumber);
            DrawHLine(e_name, topTime, now, buy_entry, ClrBoxBuy, STYLE_DOT, 1);
            string sl_name = "DV_SLB_" + IntegerToString(g_boxNumber);
            DrawHLine(sl_name, topTime, now, buy_sl, ClrSLLine, STYLE_DASH, 1);
         }
      }
   } else {
      string reason = "";
      if(!cvd_buy) reason += "CVD<0(" + DoubleToString(cvd_val, 2) + ") ";
      if(!ema_buy) reason += "Close<EMA_D1 ";
      Print("[DV] ✗ BUY STOP skipped — ", reason);
   }
   
   // SELL STOP below Box Bottom — only if CVD < 0
   if(sell_ok) {
      double sell_entry = NormalizeDouble(boxBottom - entry_pad, _Digits);
      double sell_sl    = NormalizeDouble(boxTop + sl_pad + (InpAddSpread ? spread : 0), _Digits);
      
      if(sell_entry < bid) {
         string cmt = StringFormat("DV_Sell_Box%d_CVD%.1f", g_boxNumber, cvd_val);
         if(trade.SellStop(InpFixLot, sell_entry, Symbol(), sell_sl, 0, ORDER_TIME_GTC, 0, cmt)) {
            g_pendingSellTicket = trade.ResultOrder();
            Print("[DV] ★ SELL STOP at ", DoubleToString(sell_entry, _Digits),
                  " | SL: ", DoubleToString(sell_sl, _Digits),
                  " | CVD: ", DoubleToString(cvd_val, 2));
            
            string e_name = "DV_EntryS_" + IntegerToString(g_boxNumber);
            DrawHLine(e_name, topTime, now, sell_entry, ClrBoxSell, STYLE_DOT, 1);
            string sl_name = "DV_SLS_" + IntegerToString(g_boxNumber);
            DrawHLine(sl_name, topTime, now, sell_sl, ClrSLLine, STYLE_DASH, 1);
         }
      }
   } else {
      string reason = "";
      if(!cvd_sell) reason += "CVD>0(" + DoubleToString(cvd_val, 2) + ") ";
      if(!ema_sell) reason += "Close>EMA_D1 ";
      Print("[DV] ✗ SELL STOP skipped — ", reason);
   }
}

//+------------------------------------------------------------------+
void OnTick() {
   // === Update CVD calculation ===
   CalculateCVD();
   
   // === MAX LOSS (every tick) ===
   if(InpMaxLossUSD > 0) {
      double pl = GetTotalFloatingPL();
      if(pl <= -InpMaxLossUSD) {
         CloseAllPositions();
         DeleteAllPendings();
         Alert("[DV] MAX LOSS HIT! $", DoubleToString(pl, 2));
         return;
      }
   }
   
   // === New bar check ===
   datetime current_time = iTime(Symbol(), Period(), 0);
   if(current_time == g_lastBarTime) return;
   g_lastBarTime = current_time;
   
   double high1     = iHigh(Symbol(), Period(), 1);
   double low1      = iLow(Symbol(), Period(), 1);
   datetime bar1_t  = iTime(Symbol(), Period(), 1);
   
   // ==============================================================
   // DARVAS BOX STATE MACHINE
   // Runs continuously — detects boxes for entries AND trailing
   // ==============================================================
   
   switch(g_state) {
      // ──────────────────────────────────────────────
      // STATE 1: Tìm & Xác nhận Nóc Hộp (Box Top)
      // ──────────────────────────────────────────────
      case STATE_FIND_TOP:
         if(g_candidateTop == 0 || high1 > g_candidateTop) {
            // Đỉnh mới → cập nhật candidate, reset đếm
            g_candidateTop = high1;
            g_candidateTopTime = bar1_t;
            g_topConfirmCount = 0;
            g_trackMinLow = low1;   // Bắt đầu track min low từ bar này
         }
         else {
            // Không phá đỉnh → đếm xác nhận
            g_topConfirmCount++;
            if(low1 < g_trackMinLow) g_trackMinLow = low1;
            
            if(g_topConfirmCount >= InpConfirmBars) {
               // ✔ NÓC HỘP XÁC NHẬN!
               Print("[DV] ✔ Box Top CONFIRMED at ", DoubleToString(g_candidateTop, _Digits),
                     " after ", InpConfirmBars, " bars");
               
               g_state = STATE_FIND_BOTTOM;
               g_candidateBottom = g_trackMinLow;
               g_candidateBottomTime = bar1_t;
               g_bottomConfirmCount = 0;
            }
         }
         break;
      
      // ──────────────────────────────────────────────
      // STATE 2: Tìm & Xác nhận Đáy Hộp (Box Bottom)
      // ──────────────────────────────────────────────
      case STATE_FIND_BOTTOM:
         // Kiểm tra phá nóc → hủy hộp, bắt đầu lại
         if(high1 > g_candidateTop) {
            Print("[DV] ✗ Top broken during bottom search. New candidate top.");
            g_candidateTop = high1;
            g_candidateTopTime = bar1_t;
            g_topConfirmCount = 0;
            g_trackMinLow = low1;
            g_state = STATE_FIND_TOP;
         }
         else if(low1 < g_candidateBottom) {
            // Đáy mới → cập nhật, reset đếm
            g_candidateBottom = low1;
            g_candidateBottomTime = bar1_t;
            g_bottomConfirmCount = 0;
         }
         else {
            // Không phá đáy → đếm xác nhận
            g_bottomConfirmCount++;
            
            if(g_bottomConfirmCount >= InpConfirmBars) {
               // ✔ ĐÁY HỘP XÁC NHẬN → HỘP HOÀN CHỈNH!
               Print("[DV] ✔ Box Bottom CONFIRMED at ", DoubleToString(g_candidateBottom, _Digits));
               
               OnBoxComplete(g_candidateTop, g_candidateBottom, g_candidateTopTime);
               
               // Reset state machine → tìm hộp mới
               g_candidateTop = high1;
               g_candidateTopTime = bar1_t;
               g_topConfirmCount = 0;
               g_trackMinLow = low1;
               g_state = STATE_FIND_TOP;
            }
         }
         break;
   }
   
   // === Cancel opposite pending when one triggers ===
   ENUM_POSITION_TYPE pos_type;
   bool has_pos = HasOpenPosition(pos_type);
   if(has_pos && HasAnyPending()) {
      Print("[DV] Position opened → cancelling remaining pendings.");
      DeleteAllPendings();
   }
}

//+------------------------------------------------------------------+
//| Trade transaction handler                                        |
//+------------------------------------------------------------------+
void OnTradeTransaction(const MqlTradeTransaction &trans,
                        const MqlTradeRequest &request,
                        const MqlTradeResult &result) {
   if(trans.type == TRADE_TRANSACTION_DEAL_ADD) {
      if(HistoryDealSelect(trans.deal)) {
         if(HistoryDealGetInteger(trans.deal, DEAL_MAGIC) == (long)InpMagicNumber) {
            ENUM_DEAL_ENTRY entry = (ENUM_DEAL_ENTRY)HistoryDealGetInteger(trans.deal, DEAL_ENTRY);
            if(entry == DEAL_ENTRY_IN) {
               double price = HistoryDealGetDouble(trans.deal, DEAL_PRICE);
               ENUM_DEAL_TYPE dtype = (ENUM_DEAL_TYPE)HistoryDealGetInteger(trans.deal, DEAL_TYPE);
               string dir = (dtype == DEAL_TYPE_BUY) ? "BUY" : "SELL";
               double cvd_val = GetCurrentCVD();
               Print("[DV] ✔ ", dir, " triggered at ", DoubleToString(price, _Digits),
                     " | Box #", g_boxNumber,
                     " | CVD: ", DoubleToString(cvd_val, 2));
            }
         }
      }
   }
}
//+------------------------------------------------------------------+
