//+------------------------------------------------------------------+
//|                                              EhlersCross_EA.mq5  |
//|                                  Copyright 2024, Vu (Antigravity)|
//+------------------------------------------------------------------+
#property copyright "Vu - Generated by AI"
#property link      "https://antigravity.ide"
#property version   "1.00"
#property description "EA Ehlers Instantaneous Trend Cross"
#property description "Ribbon + EMA200 Macro Bias + ATR Stop Loss"

#include <Trade\Trade.mqh>
CTrade trade;

//--- inputs
input group "=== General Settings ==="
input double InpFixLot          = 0.01;    // Fixed Lot Size
input ulong  InpMagicNumber     = 77777;   // Magic Number
input int    InpSlippage        = 3;       // Slippage

input group "=== Ehlers Settings ==="
input double InpAlpha           = 0.07;    // Ehlers Alpha
input int    InpEMAPeriod       = 200;     // EMA Period (Macro Bias)

input group "=== Risk Settings ==="
input int    InpATRPeriod       = 14;      // ATR Period for SL Buffer
input double InpATRSLMult       = 0.5;     // ATR Multiplier for SL

input group "=== Display Settings ==="
input color  ClrBullRibbon      = clrLime;          // Bullish Ribbon Color
input color  ClrBearRibbon      = clrRed;           // Bearish Ribbon Color
input color  ClrEMA             = clrGold;          // EMA200 Color
input color  ClrBuySignal       = clrDodgerBlue;    // Buy Signal Color
input color  ClrSellSignal      = clrOrangeRed;     // Sell Signal Color
input color  ClrExitSignal      = clrGray;          // Exit Signal Color

//--- Ehlers state (persistent)
double it_val[3];   // it[0]=current, it[1]=prev, it[2]=prev2
double lag_val[3];  // lag[0]=current, lag[1]=prev, lag[2]=prev2
bool   ehlers_initialized = false;
int    init_count = 0;

//--- Previous ribbon state
bool   prev_ribbon_bull = false; // lag > it = bullish ribbon

//--- Indicator handles
int    ema_handle = INVALID_HANDLE;
int    atr_handle = INVALID_HANDLE;

datetime last_bar_time = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit() {
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   
   // Reset Ehlers state
   ArrayInitialize(it_val, 0);
   ArrayInitialize(lag_val, 0);
   ehlers_initialized = false;
   init_count = 0;
   prev_ribbon_bull = false;
   
   // Create indicator handles
   ema_handle = iMA(Symbol(), Period(), InpEMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   atr_handle = iATR(Symbol(), Period(), InpATRPeriod);
   
   if(ema_handle == INVALID_HANDLE || atr_handle == INVALID_HANDLE) {
      Print("Error creating indicator handles");
      return(INIT_FAILED);
   }
   
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason) {
   if(ema_handle != INVALID_HANDLE) IndicatorRelease(ema_handle);
   if(atr_handle != INVALID_HANDLE) IndicatorRelease(atr_handle);
}

//+------------------------------------------------------------------+
//| Compute Ehlers IT for a given bar                                |
//+------------------------------------------------------------------+
void UpdateEhlers(double src0, double src1, double src2) {
   double a = InpAlpha;
   
   // Shift history
   it_val[2] = it_val[1];
   it_val[1] = it_val[0];
   lag_val[2] = lag_val[1];
   lag_val[1] = lag_val[0];
   
   if(!ehlers_initialized) {
      // Pine's nz(it[1], (src+2*src[1]+src[2])/4.0) initialization
      double seed = (src0 + 2.0 * src1 + src2) / 4.0;
      it_val[0] = seed;
      it_val[1] = seed;
      it_val[2] = seed;
      lag_val[0] = seed;
      lag_val[1] = seed;
      lag_val[2] = seed;
      ehlers_initialized = true;
      init_count = 0;
      return;
   }
   
   init_count++;
   
   // The Ehlers IT formula from Pine:
   // it = (a-(a*a)/4)*src + 0.5*a*a*src[1] - (a-0.75*a*a)*src[2] + 2*(1-a)*nz(it[1]) - (1-a)*(1-a)*nz(it[2])
   double term1 = (a - (a * a) / 4.0) * src0;
   double term2 = 0.5 * a * a * src1;
   double term3 = (a - 0.75 * a * a) * src2;
   double term4 = 2.0 * (1.0 - a) * it_val[1];
   double term5 = (1.0 - a) * (1.0 - a) * it_val[2];
   
   it_val[0] = term1 + term2 - term3 + term4 - term5;
   
   // lag = 2*it - it[2]
   lag_val[0] = 2.0 * it_val[0] - it_val[2];
}

//+------------------------------------------------------------------+
//| Draw Ehlers ribbon dots on chart                                 |
//+------------------------------------------------------------------+
void DrawRibbonDot(string prefix, datetime t, double val, color clr, int width) {
   string name = prefix + IntegerToString((long)t);
   ObjectCreate(0, name, OBJ_ARROW, 0, t, val);
   ObjectSetInteger(0, name, OBJPROP_ARROWCODE, 159); // small dot
   ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, name, OBJPROP_WIDTH, width);
   ObjectSetInteger(0, name, OBJPROP_BACK, true);
}

//+------------------------------------------------------------------+
//| Draw signal marker on chart                                      |
//+------------------------------------------------------------------+
void DrawSignal(string name, datetime t, double price, color clr, bool is_buy) {
   if(is_buy) {
      ObjectCreate(0, name, OBJ_ARROW_BUY, 0, t, price);
   } else {
      ObjectCreate(0, name, OBJ_ARROW_SELL, 0, t, price);
   }
   ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, name, OBJPROP_WIDTH, 2);
}

//+------------------------------------------------------------------+
//| Draw text label on chart                                         |
//+------------------------------------------------------------------+
void DrawTextLabel(string name, datetime t, double price, string text, color clr) {
   ObjectCreate(0, name, OBJ_TEXT, 0, t, price);
   ObjectSetString(0, name, OBJPROP_TEXT, text);
   ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, name, OBJPROP_FONTSIZE, 10);
   ObjectSetString(0, name, OBJPROP_FONT, "Arial Bold");
}

//+------------------------------------------------------------------+
//| Check if we have an open position                                |
//+------------------------------------------------------------------+
bool HasOpenPosition(ENUM_POSITION_TYPE &pos_type) {
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      string symbol = PositionGetSymbol(i);
      ulong magic = PositionGetInteger(POSITION_MAGIC);
      if(symbol == Symbol() && magic == InpMagicNumber) {
         pos_type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
         return true;
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| Close all positions of this EA                                   |
//+------------------------------------------------------------------+
void CloseAllPositions() {
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      string symbol = PositionGetSymbol(i);
      ulong magic = PositionGetInteger(POSITION_MAGIC);
      if(symbol == Symbol() && magic == InpMagicNumber) {
         ulong ticket = PositionGetTicket(i);
         trade.PositionClose(ticket);
      }
   }
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick() {
   datetime current_time = iTime(Symbol(), Period(), 0);
   if(current_time == last_bar_time) return;
   last_bar_time = current_time;
   
   // Need at least 3 bars of source data
   if(iBars(Symbol(), Period()) < InpEMAPeriod + 10) return;
   
   // Source = hl2 (as in Pine)
   double src0 = (iHigh(Symbol(), Period(), 1) + iLow(Symbol(), Period(), 1)) / 2.0;
   double src1 = (iHigh(Symbol(), Period(), 2) + iLow(Symbol(), Period(), 2)) / 2.0;
   double src2 = (iHigh(Symbol(), Period(), 3) + iLow(Symbol(), Period(), 3)) / 2.0;
   
   double close1 = iClose(Symbol(), Period(), 1);
   double open1  = iOpen(Symbol(), Period(), 1);
   double high1  = iHigh(Symbol(), Period(), 1);
   double low1   = iLow(Symbol(), Period(), 1);
   datetime bar_time = iTime(Symbol(), Period(), 1);
   
   // Get EMA200 value
   double ema_buf[];
   if(CopyBuffer(ema_handle, 0, 1, 1, ema_buf) <= 0) return;
   double ema200 = ema_buf[0];
   
   // Get ATR value
   double atr_buf[];
   if(CopyBuffer(atr_handle, 0, 1, 1, atr_buf) <= 0) return;
   double atr_val = atr_buf[0];
   
   // ============================================================
   // Update Ehlers Instantaneous Trend
   // ============================================================
   UpdateEhlers(src0, src1, src2);
   
   // Skip first few bars while filter stabilizes
   if(init_count < 5) return;
   
   double it_now  = it_val[0];
   double lag_now = lag_val[0];
   
   // Ribbon state: lag > it = BULLISH (green), lag < it = BEARISH (red)
   // Pine: bc = it > lag ? red : lime
   // Note: In Pine, barcolor red = bearish when it > lag. 
   // Ribbon fill: lag > it = UpTrend(green), it > lag = DownTrend(red)
   bool ribbon_bull = (lag_now > it_now);   // Green ribbon
   bool ribbon_bear = (lag_now < it_now);   // Red ribbon
   
   // Crossover detection
   bool cross_to_bull = ribbon_bull && !prev_ribbon_bull;  // Red -> Green
   bool cross_to_bear = ribbon_bear && prev_ribbon_bull;   // Green -> Red
   
   // ============================================================
   // Visual: Draw Ehlers lines and EMA on chart
   // ============================================================
   color ribbon_clr = ribbon_bull ? ClrBullRibbon : ClrBearRibbon;
   DrawRibbonDot("EH_IT_", bar_time, it_now, ribbon_clr, 1);
   DrawRibbonDot("EH_LAG_", bar_time, lag_now, ribbon_clr, 2);
   
   // Draw EMA200 dot
   DrawRibbonDot("EH_EMA_", bar_time, ema200, ClrEMA, 1);
   
   // ============================================================
   // Component 1: Macro Bias (EMA200 filter)
   // ============================================================
   bool above_ema = (close1 > ema200); // Allow Buy
   bool below_ema = (close1 < ema200); // Allow Sell
   
   bool is_green_candle = (close1 > open1);
   bool is_red_candle   = (close1 < open1);
   
   // ============================================================
   // Position tracking
   // ============================================================
   ENUM_POSITION_TYPE pos_type;
   bool has_position = HasOpenPosition(pos_type);
   
   // ============================================================
   // EXIT LOGIC FIRST: Ribbon Color Reversal -> Close
   // ============================================================
   if(has_position) {
      // Holding BUY -> Ribbon turns RED -> Close
      if(pos_type == POSITION_TYPE_BUY && cross_to_bear) {
         CloseAllPositions();
         
         string exit_name = "EH_ExitBuy_" + IntegerToString((long)bar_time);
         DrawTextLabel(exit_name, bar_time, high1 + atr_val * 0.3, "✕ CLOSE", ClrExitSignal);
         
         has_position = false; // Allow immediate re-entry
      }
      
      // Holding SELL -> Ribbon turns GREEN -> Close
      if(has_position && pos_type == POSITION_TYPE_SELL && cross_to_bull) {
         CloseAllPositions();
         
         string exit_name = "EH_ExitSell_" + IntegerToString((long)bar_time);
         DrawTextLabel(exit_name, bar_time, low1 - atr_val * 0.3, "✕ CLOSE", ClrExitSignal);
         
         has_position = false;
      }
   }
   
   // ============================================================
   // ENTRY LOGIC: Ribbon Cross + EMA Filter + Candle Confirmation
   // ============================================================
   double sl_buffer = atr_val * InpATRSLMult;
   
   // BUY: Ribbon Red->Green + Close above EMA200 + Green candle
   if(cross_to_bull && above_ema && is_green_candle && !has_position) {
      double ask = SymbolInfoDouble(Symbol(), SYMBOL_ASK);
      
      // SL: Below low of signal candle - 0.5*ATR
      double sl = NormalizeDouble(low1 - sl_buffer, _Digits);
      
      if(trade.Buy(InpFixLot, Symbol(), ask, sl, 0, "Ehlers Cross Buy")) {
         // Draw Buy signal
         string sig_name = "EH_BuySig_" + IntegerToString((long)bar_time);
         DrawSignal(sig_name, bar_time, low1 - atr_val * 0.2, ClrBuySignal, true);
         
         string txt_name = "EH_BuyTxt_" + IntegerToString((long)bar_time);
         DrawTextLabel(txt_name, bar_time, low1 - atr_val * 0.6, "BUY", ClrBuySignal);
         
         // Draw crossover highlight
         string cross_name = "EH_CrossUp_" + IntegerToString((long)bar_time);
         DrawTextLabel(cross_name, bar_time, lag_now + atr_val * 0.15, "▲", ClrBullRibbon);
      }
   }
   
   // SELL: Ribbon Green->Red + Close below EMA200 + Red candle
   if(cross_to_bear && below_ema && is_red_candle && !has_position) {
      double bid = SymbolInfoDouble(Symbol(), SYMBOL_BID);
      
      // SL: Above high of signal candle + 0.5*ATR
      double sl = NormalizeDouble(high1 + sl_buffer, _Digits);
      
      if(trade.Sell(InpFixLot, Symbol(), bid, sl, 0, "Ehlers Cross Sell")) {
         // Draw Sell signal
         string sig_name = "EH_SellSig_" + IntegerToString((long)bar_time);
         DrawSignal(sig_name, bar_time, high1 + atr_val * 0.2, ClrSellSignal, false);
         
         string txt_name = "EH_SellTxt_" + IntegerToString((long)bar_time);
         DrawTextLabel(txt_name, bar_time, high1 + atr_val * 0.6, "SELL", ClrSellSignal);
         
         // Draw crossover highlight
         string cross_name = "EH_CrossDn_" + IntegerToString((long)bar_time);
         DrawTextLabel(cross_name, bar_time, lag_now - atr_val * 0.15, "▼", ClrBearRibbon);
      }
   }
   
   // Save state for next bar
   prev_ribbon_bull = ribbon_bull;
}
//+------------------------------------------------------------------+
