//+------------------------------------------------------------------+
//|                                           RangeBreakoutEA_v2.mq5 |
//| Auto-generated by Assistant                                      |
//+------------------------------------------------------------------+
#property copyright "AlgoPoint / Converted to EA"
#property link      ""
#property version   "1.00"

#include <Trade\Trade.mqh>
CTrade trade;

//--- Enum phương thức Trailing
enum ENUM_TRAIL_METHOD
{
   TRAIL_EMA        = 0,  // EMA Trailing
   TRAIL_CHANDELIER = 1   // Chandelier Exit
};

//--- Cài đặt cơ bản
input string               Settings_Base        = "=== CÀI ĐẶT CƠ BẢN ===";
input double               InpLotSize           = 0.01;         // Khối lượng (Lot Size)
input ulong                InpMagicNumber       = 778899;       // Magic Number

//--- Component 1: Bộ Lọc Xu Hướng (The Macro Filter)
input string               Settings_Trend       = "=== BỘ LỌC XU HƯỚNG ===";
input ENUM_TIMEFRAMES      InpFilterTimeframe   = PERIOD_D1;    // Khung thời gian Xu hướng (D1)
input int                  InpEMAPeriod         = 100;          // Chu kỳ EMA Filter

//--- Component 2: Logic Range
input string               Settings_Range       = "=== LOGIC RANGE DETECTOR ===";
input ENUM_TIMEFRAMES      InpRangeTimeframe    = PERIOD_H1;    // Khung thời gian Range (H1)
input int                  InpRangePeriod       = 20;           // Số nến để tính biên độ hộp
input int                  InpAvgPeriod         = 100;          // Số nến trung bình
input double               InpThreshold         = 0.85;         // Hệ số nén
input double               InpOverlapPct        = 0.60;         // Tỷ lệ overlap (%)
input int                  InpMinGap            = 5;            // Khoảng cách overlap tối thiểu

//--- Component 3: Quản trị Rủi ro (ATR Stop Loss & Trailing)
input string               Settings_Risk           = "=== STOP LOSS & TRAILING ===";
input int                  InpATRPeriod            = 14;          // Chu kỳ ATR
input double               InpSLMultiplier         = 1.5;         // Hệ số SL theo ATR
input double               InpSpreadATRRatio       = 0.10;        // Max Spread tự động = ATR × tỷ lệ này (ví dụ 0.1 = 10% ATR)

//--- Trailing Stop
input ENUM_TRAIL_METHOD    InpTrailMethod          = TRAIL_EMA;   // Phương thức Trailing (EMA / Chandelier)
input double               InpTrailMultiplier      = 1.5;         // Hệ số Trailing (cho cả EMA lẫn Chandelier)
input int                  InpTrailEMAPeriod       = 21;          // Chu kỳ EMA Trailing (dùng khi chọn EMA)
input int                  InpChandelierPeriod     = 22;          // Chu kỳ Chandelier (số nến tính High/Low)  

//--- Handles
int h_ema_filter;
int h_atr;
int h_ema_trail;
int h_atr_trail; // ATR riêng cho Chandelier (dùng InpChandelierPeriod nếu muốn tách, hoặc dùng chung h_atr)

//--- Startup flag: chạy logic tín hiệu ngay lần đầu không cần đợi nến mới
bool g_initialized = false;

//+------------------------------------------------------------------+
//| Kiểm tra spread hiện tại so với ngưỡng tự động theo ATR         |
//| MaxSpread = ATR × InpSpreadATRRatio                              |
//| Tự động thích nghi với mọi cặp tiền không cần chỉnh tay         |
//+------------------------------------------------------------------+
bool IsSpreadOK(double current_atr)
{
   long   spread_points = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);  // đơn vị: points
   double spread_price  = spread_points * _Point;                     // đổi ra giá
   double max_spread    = current_atr * InpSpreadATRRatio;            // ngưỡng tự động
   
   if(spread_price > max_spread)
   {
      PrintFormat("[Spread Filter] Spread quá rộng: %.5f > MaxSpread %.5f (ATR=%.5f × %.2f)",
                  spread_price, max_spread, current_atr, InpSpreadATRRatio);
      return false;
   }
   return true;
}

//+------------------------------------------------------------------+
//| In log lỗi giao dịch với retcode và mô tả                       |
//+------------------------------------------------------------------+
void LogTradeError(string context)
{
   uint   retcode = trade.ResultRetcode();
   string desc    = trade.ResultRetcodeDescription();
   PrintFormat("[Trade ERROR] %s | Retcode: %u | %s", context, retcode, desc);
}

//+------------------------------------------------------------------+
//| Lỗi tạm thời có thể retry (requote, giá thay đổi, mất quotes)   |
//+------------------------------------------------------------------+
bool IsRetryableError(uint retcode)
{
   return (retcode == TRADE_RETCODE_REQUOTE      ||
           retcode == TRADE_RETCODE_PRICE_CHANGED ||
           retcode == TRADE_RETCODE_PRICE_OFF     ||
           retcode == TRADE_RETCODE_CONNECTION);
}

//+------------------------------------------------------------------+
//| Gửi email thông báo giao dịch                                   |
//+------------------------------------------------------------------+
void SendTradeEmail(string event_type, string direction, double price, double sl, double lot)
{
   if(!TerminalInfoInteger(TERMINAL_EMAIL_ENABLED))
   {
      Print("[Email] Chưa cấu hình SMTP — bỏ qua email.");
      return;
   }
   
   string subject = StringFormat("[%s] %s %s @ %.5f",
                                 _Symbol, event_type, direction, price);
   string body    = StringFormat(
      "EA: Range Detect Breakout\n"
      "Symbol : %s\n"
      "Event  : %s\n"
      "Direction: %s\n"
      "Price  : %.5f\n"
      "Stop Loss: %.5f\n"
      "Lot    : %.2f\n"
      "Time   : %s",
      _Symbol, event_type, direction, price, sl, lot,
      TimeToString(TimeCurrent(), TIME_DATE|TIME_MINUTES|TIME_SECONDS));
   
   if(!SendMail(subject, body))
      PrintFormat("[Email] Gửi thất bại: %s", subject);
   else
      PrintFormat("[Email] Đã gửi: %s", subject);
}

//+------------------------------------------------------------------+
//| Helper func: Range calculation                                   |
//+------------------------------------------------------------------+
double CalcBarRange(ENUM_TIMEFRAMES tf, int bar, int period)
{
   double high[], low[];
   ArraySetAsSeries(high, true);
   ArraySetAsSeries(low, true);
   if(CopyHigh(_Symbol, tf, bar, period, high) < period) return 0;
   if(CopyLow(_Symbol, tf, bar, period, low) < period) return 0;
   
   int hi_idx = ArrayMaximum(high);
   int lo_idx = ArrayMinimum(low);
   return high[hi_idx] - low[lo_idx];
}

//+------------------------------------------------------------------+
//| Overlap check for Range Detection                                |
//+------------------------------------------------------------------+
double CalcOverlapRatio(ENUM_TIMEFRAMES tf, int bar, int period, int min_gap)
{
   double high[], low[];
   ArraySetAsSeries(high, true);
   ArraySetAsSeries(low, true);
   if(CopyHigh(_Symbol, tf, bar, period, high) < period) return 0;
   if(CopyLow(_Symbol, tf, bar, period, low) < period) return 0;
   
   int cnt = period;
   if(cnt <= min_gap) return 0.0;
   
   int revisited = 0;
   
   for(int j = 0; j < cnt; j++)
   {
      double h_j = high[j];
      double l_j = low[j];
      bool has_distant_overlap = false;
      
      for(int k = 0; k < cnt; k++)
      {
         if(MathAbs(k - j) < min_gap) continue;
         
         if(low[k] <= h_j && high[k] >= l_j)
         {
            has_distant_overlap = true;
            break;
         }
      }
      if(has_distant_overlap) revisited++;
   }
   
   return (double)revisited / cnt;
}

//+------------------------------------------------------------------+
//| Get highest/lowest of current period                             |
//+------------------------------------------------------------------+
void GetRangeExtremes(ENUM_TIMEFRAMES tf, int bar, int period, double &range_high, double &range_low)
{
   range_high = 0; range_low = 0;
   double high[], low[];
   ArraySetAsSeries(high, true);
   ArraySetAsSeries(low, true);
   if(CopyHigh(_Symbol, tf, bar, period, high) < period) return;
   if(CopyLow(_Symbol, tf, bar, period, low) < period) return;
   
   int hi_idx = ArrayMaximum(high);
   int lo_idx = ArrayMinimum(low);
   
   range_high = high[hi_idx];
   range_low = low[lo_idx];
}

//+------------------------------------------------------------------+
//| Check if ranging at given bar                                    |
//+------------------------------------------------------------------+
bool CheckIsRanging(int bar)
{
   double current_range = CalcBarRange(InpRangeTimeframe, bar, InpRangePeriod);
   
   double sum_range = 0;
   for(int i = 0; i < InpAvgPeriod; i++)
   {
      sum_range += CalcBarRange(InpRangeTimeframe, bar + i, InpRangePeriod);
   }
   double avg_range = sum_range / InpAvgPeriod;
   
   bool cond_squeeze = false;
   if(avg_range > 0) cond_squeeze = (current_range < avg_range * InpThreshold);
   
   double overlap = CalcOverlapRatio(InpRangeTimeframe, bar, InpRangePeriod, InpMinGap);
   bool cond_overlap = (overlap >= InpOverlapPct);
   
   return cond_squeeze && cond_overlap;
}

//+------------------------------------------------------------------+
//| Draw recent ranges for visual verification                       |
//+------------------------------------------------------------------+
void DrawRecentRanges()
{
   int ranges_found = 0;
   bool in_range = false;
   int current_range_right = -1;
   int current_range_left = -1;
   
   ObjectsDeleteAll(0, "RangeBox_");
   
   // Quét đến 1500 nến trong quá khứ để tìm 3 range gần nhất
   for(int i = 1; i < 1500; i++)
   {
      if(ranges_found >= 3) break;
      
      bool is_ranging = CheckIsRanging(i);
      
      if(is_ranging)
      {
         if(!in_range)
         {
            in_range = true;
            current_range_right = i;
            current_range_left = i + InpRangePeriod - 1;
         }
         else
         {
            current_range_left = i + InpRangePeriod - 1;
         }
      }
      else
      {
         if(in_range)
         {
            double r_high, r_low;
            int total_period = current_range_left - current_range_right + 1;
            GetRangeExtremes(InpRangeTimeframe, current_range_right, total_period, r_high, r_low);
            
            datetime time1 = iTime(_Symbol, InpRangeTimeframe, current_range_left);
            datetime time2 = iTime(_Symbol, InpRangeTimeframe, current_range_right);
            
            string obj_name = "RangeBox_" + IntegerToString(ranges_found);
            ObjectCreate(0, obj_name, OBJ_RECTANGLE, 0, time1, r_high, time2, r_low);
            ObjectSetInteger(0, obj_name, OBJPROP_COLOR, clrDimGray);
            ObjectSetInteger(0, obj_name, OBJPROP_FILL, true);
            ObjectSetInteger(0, obj_name, OBJPROP_BACK, true);
            
            ranges_found++;
            in_range = false;
         }
      }
   }
   
   if(in_range && ranges_found < 3)
   {
      double r_high, r_low;
      int total_period = current_range_left - current_range_right + 1;
      GetRangeExtremes(InpRangeTimeframe, current_range_right, total_period, r_high, r_low);
      
      datetime time1 = iTime(_Symbol, InpRangeTimeframe, current_range_left);
      datetime time2 = iTime(_Symbol, InpRangeTimeframe, current_range_right);
      
      string obj_name = "RangeBox_" + IntegerToString(ranges_found);
      ObjectCreate(0, obj_name, OBJ_RECTANGLE, 0, time1, r_high, time2, r_low);
      ObjectSetInteger(0, obj_name, OBJPROP_COLOR, clrDimGray);
      ObjectSetInteger(0, obj_name, OBJPROP_FILL, true);
      ObjectSetInteger(0, obj_name, OBJPROP_BACK, true);
      
      ranges_found++;
   }
   
   ChartRedraw();
}

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   trade.SetExpertMagicNumber(InpMagicNumber);
   
   h_ema_filter = iMA(_Symbol, InpFilterTimeframe, InpEMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   h_atr        = iATR(_Symbol, InpRangeTimeframe, InpATRPeriod);
   h_ema_trail  = iMA(_Symbol, InpRangeTimeframe, InpTrailEMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   h_atr_trail  = iATR(_Symbol, InpRangeTimeframe, InpChandelierPeriod); // ATR cho Chandelier
   
   if(h_ema_filter == INVALID_HANDLE || h_atr == INVALID_HANDLE ||
      h_ema_trail  == INVALID_HANDLE || h_atr_trail == INVALID_HANDLE)
   {
      Print("Failed to initialize indicators");
      return INIT_FAILED;
   }
   
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| New Bar check                                                    |
//+------------------------------------------------------------------+
bool IsNewBar(ENUM_TIMEFRAMES tf)
{
   static datetime last_time = 0;
   datetime current_time = iTime(_Symbol, tf, 0);
   if(current_time != last_time)
   {
      if(last_time == 0)
      {
         last_time = current_time;
         return false;
      }
      last_time = current_time;
      return true;
   }
   return false;
}

//+------------------------------------------------------------------+
//| Main logic tick                                                  |
//+------------------------------------------------------------------+
//+------------------------------------------------------------------+
//| Core signal logic — gọi khi có nến mới HOẶC lần đầu bật máy    |
//+------------------------------------------------------------------+
void RunSignalLogic()
{
   double ema_filter_arr[], atr_arr[];
   if(CopyBuffer(h_ema_filter, 0, 1, 1, ema_filter_arr) <= 0) return;
   if(CopyBuffer(h_atr, 0, 1, 1, atr_arr) <= 0) return;
   
   double ema_filter = ema_filter_arr[0];
   double current_atr = atr_arr[0];
   
   // --- Khung D1 Filter
   double close_current = iClose(_Symbol, InpFilterTimeframe, 1);
   bool is_bullish = close_current > ema_filter;
   bool is_bearish = close_current < ema_filter;
   
   // --- Range Detection Logic ---
   bool is_ranging = CheckIsRanging(1);
   
   // Draw recent ranges for visual verification
   DrawRecentRanges();
   
   int pos_count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == InpMagicNumber) pos_count++;
   }

   // --- Placing Pending Orders ---
   if(pos_count == 0)
   {
       // Remove stale orders first
      for(int i = OrdersTotal() - 1; i >= 0; i--)
      {
         ulong pkt = OrderGetTicket(i);
         if(OrderGetString(ORDER_SYMBOL) == _Symbol && OrderGetInteger(ORDER_MAGIC) == InpMagicNumber)
         {
            if(!trade.OrderDelete(pkt))
               LogTradeError(StringFormat("OrderDelete ticket=%I64u", pkt));
         }
      }
       
      if(is_ranging)
      {
         // --- Spread filter: kiểm tra spread trước khi đặt lệnh ---
         if(!IsSpreadOK(current_atr)) return;
         
         double r_high, r_low;
         GetRangeExtremes(InpRangeTimeframe, 1, InpRangePeriod, r_high, r_low);
         
         double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
         double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
         double stoplevel = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL) * _Point;
         if(stoplevel == 0) stoplevel = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD) * _Point * 2;
         
         if(is_bullish && r_high > 0)
         {
            double entry_price = NormalizeDouble(r_high, _Digits);
            double stop_loss   = NormalizeDouble(entry_price - (InpSLMultiplier * current_atr), _Digits);
            
            if(ask < entry_price - stoplevel)
            {
               if(!trade.BuyStop(InpLotSize, entry_price, _Symbol, stop_loss, 0, ORDER_TIME_GTC, 0, "Range Breakout Buy"))
               {
                  LogTradeError(StringFormat("BuyStop @ %.5f SL=%.5f", entry_price, stop_loss));
                  // Retry một lần nếu lỗi tạm thời
                  if(IsRetryableError(trade.ResultRetcode()))
                  {
                     Sleep(200);
                     entry_price = NormalizeDouble(SymbolInfoDouble(_Symbol, SYMBOL_ASK), _Digits);
                     if(!trade.BuyStop(InpLotSize, entry_price, _Symbol,
                                       NormalizeDouble(entry_price - InpSLMultiplier * current_atr, _Digits),
                                       0, ORDER_TIME_GTC, 0, "Range Breakout Buy [retry]"))
                        LogTradeError("BuyStop RETRY thất bại");
                     else
                        SendTradeEmail("ORDER PLACED", "BUY STOP", entry_price,
                                       NormalizeDouble(entry_price - InpSLMultiplier * current_atr, _Digits), InpLotSize);
                  }
               }
               else
                  SendTradeEmail("ORDER PLACED", "BUY STOP", entry_price, stop_loss, InpLotSize);
            }
         }
         else if(is_bearish && r_low > 0)
         {
            double entry_price = NormalizeDouble(r_low, _Digits);
            double stop_loss   = NormalizeDouble(entry_price + (InpSLMultiplier * current_atr), _Digits);
            
            if(bid > entry_price + stoplevel)
            {
               if(!trade.SellStop(InpLotSize, entry_price, _Symbol, stop_loss, 0, ORDER_TIME_GTC, 0, "Range Breakout Sell"))
               {
                  LogTradeError(StringFormat("SellStop @ %.5f SL=%.5f", entry_price, stop_loss));
                  if(IsRetryableError(trade.ResultRetcode()))
                  {
                     Sleep(200);
                     entry_price = NormalizeDouble(SymbolInfoDouble(_Symbol, SYMBOL_BID), _Digits);
                     if(!trade.SellStop(InpLotSize, entry_price, _Symbol,
                                        NormalizeDouble(entry_price + InpSLMultiplier * current_atr, _Digits),
                                        0, ORDER_TIME_GTC, 0, "Range Breakout Sell [retry]"))
                        LogTradeError("SellStop RETRY thất bại");
                     else
                        SendTradeEmail("ORDER PLACED", "SELL STOP", entry_price,
                                       NormalizeDouble(entry_price + InpSLMultiplier * current_atr, _Digits), InpLotSize);
                  }
               }
               else
                  SendTradeEmail("ORDER PLACED", "SELL STOP", entry_price, stop_loss, InpLotSize);
            }
         }
      }
   }
   else
   {
       // If we have an open position, delete any remaining pending limit/stop orders
      for(int i = OrdersTotal() - 1; i >= 0; i--)
      {
         ulong pkt = OrderGetTicket(i);
         if(OrderGetString(ORDER_SYMBOL) == _Symbol && OrderGetInteger(ORDER_MAGIC) == InpMagicNumber)
         {
            if(!trade.OrderDelete(pkt))
               LogTradeError(StringFormat("OrderDelete (cleanup) ticket=%I64u", pkt));
         }
      }
   }
}

void OnTick()
{
   // Manage Trailing stop every tick for precision
   ManageTrailingStop();
   
   // Lần đầu bật máy: chạy logic ngay không cần đợi nến mới
   // Đảm bảo không bỏ lỡ tín hiệu xảy ra lúc bot offline
   if(!g_initialized)
   {
      g_initialized = true;
      IsNewBar(InpRangeTimeframe); // khởi tạo last_time để IsNewBar hoạt động đúng sau đó
      RunSignalLogic();
      return;
   }
   
   // Các tick tiếp theo: chỉ xử lý khi có nến mới
   if(!IsNewBar(InpRangeTimeframe)) return;
   
   RunSignalLogic();
}

//+------------------------------------------------------------------+
//| Theo dõi deal: gửi email khi lệnh khớp (fill)                   |
//+------------------------------------------------------------------+
void OnTradeTransaction(const MqlTradeTransaction &trans,
                        const MqlTradeRequest     &request,
                        const MqlTradeResult      &result)
{
   if(trans.type != TRADE_TRANSACTION_DEAL_ADD) return;
   
   ulong deal_ticket = trans.deal;
   if(!HistoryDealSelect(deal_ticket)) return;
   
   if(HistoryDealGetInteger(deal_ticket, DEAL_MAGIC)  != (long)InpMagicNumber) return;
   if(HistoryDealGetString(deal_ticket,  DEAL_SYMBOL) != _Symbol) return;
   
   ENUM_DEAL_ENTRY deal_entry = (ENUM_DEAL_ENTRY)HistoryDealGetInteger(deal_ticket, DEAL_ENTRY);
   
   // --- Email khi lệnh KHỚP (mở position từ pending order) ---
   if(deal_entry == DEAL_ENTRY_IN)
   {
      ENUM_DEAL_TYPE deal_type  = (ENUM_DEAL_TYPE)HistoryDealGetInteger(deal_ticket, DEAL_TYPE);
      string         direction  = (deal_type == DEAL_TYPE_BUY) ? "BUY" : "SELL";
      double         fill_price = HistoryDealGetDouble(deal_ticket, DEAL_PRICE);
      double         fill_vol   = HistoryDealGetDouble(deal_ticket, DEAL_VOLUME);
      double         pos_sl     = 0;
      
      // Lấy SL hiện tại của position
      ulong pos_id = (ulong)HistoryDealGetInteger(deal_ticket, DEAL_POSITION_ID);
      if(PositionSelectByTicket(pos_id))
         pos_sl = PositionGetDouble(POSITION_SL);
      
      SendTradeEmail("ORDER FILLED", direction, fill_price, pos_sl, fill_vol);
   }
}

//+------------------------------------------------------------------+
//| Dispatcher: chọn phương thức trailing theo setting               |
//+------------------------------------------------------------------+
void ManageTrailingStop()
{
   if(InpTrailMethod == TRAIL_EMA)
      ManageEMATrailing();
   else
      ManageChandelierTrailing();
}

//+------------------------------------------------------------------+
//| Trailing theo EMA                                                |
//+------------------------------------------------------------------+
void ManageEMATrailing()
{
   double ema_trail_arr[];
   // Lấy nến đã đóng (shift 1) để tránh repaint
   if(CopyBuffer(h_ema_trail, 0, 1, 1, ema_trail_arr) <= 0) return;
   double trail_level = ema_trail_arr[0];
   
   ApplyTrailingLevel(trail_level);
}

//+------------------------------------------------------------------+
//| Trailing theo Chandelier Exit                                    |
//| Buy  SL = Highest High (n) - ATR(n) × multiplier                |
//| Sell SL = Lowest  Low  (n) + ATR(n) × multiplier                |
//+------------------------------------------------------------------+
void ManageChandelierTrailing()
{
   double atr_arr[];
   if(CopyBuffer(h_atr_trail, 0, 1, 1, atr_arr) <= 0) return;
   double atr_val = atr_arr[0];
   
   // Tính Highest High và Lowest Low trong InpChandelierPeriod nến gần nhất (shift 1)
   double high_arr[], low_arr[];
   ArraySetAsSeries(high_arr, true);
   ArraySetAsSeries(low_arr,  true);
   if(CopyHigh(_Symbol, InpRangeTimeframe, 1, InpChandelierPeriod, high_arr) < InpChandelierPeriod) return;
   if(CopyLow (_Symbol, InpRangeTimeframe, 1, InpChandelierPeriod, low_arr)  < InpChandelierPeriod) return;
   
   double highest_high = high_arr[ArrayMaximum(high_arr)];
   double lowest_low   = low_arr [ArrayMinimum(low_arr)];
   
   double stoplevel = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL) * _Point;
   if(stoplevel == 0) stoplevel = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD) * _Point * 2;
   
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if(PositionGetInteger(POSITION_MAGIC)  != InpMagicNumber) continue;
      
      ENUM_POSITION_TYPE type       = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
      double             current_sl = PositionGetDouble(POSITION_SL);
      
      if(type == POSITION_TYPE_BUY)
      {
         double new_sl = NormalizeDouble(highest_high - InpTrailMultiplier * atr_val, _Digits);
         if(current_sl == 0 || new_sl > current_sl + _Point)
         {
            double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
            if(new_sl <= bid - stoplevel)
            {
               if(!trade.PositionModify(ticket, new_sl, 0))
                  LogTradeError(StringFormat("Chandelier PositionModify BUY ticket=%I64u new_sl=%.5f", ticket, new_sl));
            }
            else if(new_sl >= bid)
            {
               if(!trade.PositionClose(ticket))
                  LogTradeError(StringFormat("Chandelier PositionClose BUY ticket=%I64u", ticket));
            }
         }
      }
      else if(type == POSITION_TYPE_SELL)
      {
         double new_sl = NormalizeDouble(lowest_low + InpTrailMultiplier * atr_val, _Digits);
         if(current_sl == 0 || new_sl < current_sl - _Point)
         {
            double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
            if(new_sl >= ask + stoplevel)
            {
               if(!trade.PositionModify(ticket, new_sl, 0))
                  LogTradeError(StringFormat("Chandelier PositionModify SELL ticket=%I64u new_sl=%.5f", ticket, new_sl));
            }
            else if(new_sl <= ask)
            {
               if(!trade.PositionClose(ticket))
                  LogTradeError(StringFormat("Chandelier PositionClose SELL ticket=%I64u", ticket));
            }
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Shared: áp trailing level đã tính sẵn (dùng cho EMA trailing)   |
//+------------------------------------------------------------------+
void ApplyTrailingLevel(double trail_level)
{
   double stoplevel = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL) * _Point;
   if(stoplevel == 0) stoplevel = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD) * _Point * 2;
   
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if(PositionGetInteger(POSITION_MAGIC)  != InpMagicNumber) continue;
      
      ENUM_POSITION_TYPE type       = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
      double             current_sl = PositionGetDouble(POSITION_SL);
      double             new_sl     = NormalizeDouble(trail_level, _Digits);
      
      if(type == POSITION_TYPE_BUY)
      {
         if(current_sl == 0 || new_sl > current_sl + _Point)
         {
            double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
            if(new_sl <= bid - stoplevel)
            {
               if(!trade.PositionModify(ticket, new_sl, 0))
                  LogTradeError(StringFormat("EMA PositionModify BUY ticket=%I64u new_sl=%.5f", ticket, new_sl));
            }
            else if(new_sl >= bid)
            {
               if(!trade.PositionClose(ticket))
                  LogTradeError(StringFormat("EMA PositionClose BUY ticket=%I64u", ticket));
            }
         }
      }
      else if(type == POSITION_TYPE_SELL)
      {
         if(current_sl == 0 || new_sl < current_sl - _Point)
         {
            double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
            if(new_sl >= ask + stoplevel)
            {
               if(!trade.PositionModify(ticket, new_sl, 0))
                  LogTradeError(StringFormat("EMA PositionModify SELL ticket=%I64u new_sl=%.5f", ticket, new_sl));
            }
            else if(new_sl <= ask)
            {
               if(!trade.PositionClose(ticket))
                  LogTradeError(StringFormat("EMA PositionClose SELL ticket=%I64u", ticket));
            }
         }
      }
   }
}
