//+------------------------------------------------------------------+
//|                                The Volatility Rider CVD Filter.mq5|
//|                                      Auto-generated by Assistant |
//+------------------------------------------------------------------+
#property copyright "Copyright 2024"
#property link      ""
#property version   "1.00"
#property description "Volatility Rider + CVD Filter + Session Filter"
#property description "Buy: EMA bullish & CVD>0 | Sell: EMA bearish & CVD<0"

#include <Trade\Trade.mqh>
CTrade trade;

//--- Cài đặt cơ bản
input string               Settings_Base        = "=== CÀI ĐẶT CƠ BẢN ===";
input double               InpLotSize           = 0.01;         // Khối lượng (Lot Size)
input ulong                InpMagicNumber       = 168169;       // Magic Number

//--- Component 1: Bộ Lọc Xu Hướng (The Macro Filter)
input string               Settings_Trend       = "=== BỘ LỌC XU HƯỚNG ===";
input ENUM_TIMEFRAMES      InpFilterTimeframe   = PERIOD_D1;    // Khung thời gian Xu hướng (D1)
input int                  InpEMAPeriod         = 100;          // Chu kỳ EMA

//--- Component 2: Tín Hiệu Vào Lệnh (The Entry Trigger)
input string               Settings_Entry       = "=== TÍN HIỆU VÀO LỆNH ===";
input ENUM_TIMEFRAMES      InpEntryTimeframe    = PERIOD_H1;    // Khung thời gian Vào lệnh (H1)
input int                  InpDonchianPeriod    = 20;           // Chu kỳ Kênh Donchian (High/Low)

//--- Component 3 & 4: Quản Trị Rủi Ro (Initial SL & Trailing)
input string               Settings_Risk        = "=== QUẢN TRỊ RỦI RO (ATR) ===";
input int                  InpATRPeriod         = 14;           // Chu kỳ ATR
input double               InpSLMultiplier      = 1.5;          // Hệ số SL ban đầu
input double               InpTrailingMultiplier= 3.0;          // Hệ số Trailing Stop (Chandelier)

//--- Component 5: Bộ Lọc Phiên Giao Dịch (Session Filter)
input string               Settings_Session     = "=== BỘ LỌC PHIÊN GIAO DỊCH ===";
input bool                 InpUseSession        = true;         // Bật bộ lọc phiên
input int                  InpSessionStartGMT   = 7;            // Giờ BẮT ĐẦU phiên (GMT) [07 = Frankfurt Open]
input int                  InpSessionEndGMT     = 20;           // Giờ KẾT THÚC phiên (GMT) [20 = 03:00 GMT+7]
input int                  InpGMTOffset         = 2;            // GMT Offset của Server (vd: 2 = GMT+2)
input bool                 InpDeletePendingOOS  = true;         // Xóa Pending khi hết phiên
input bool                 InpClosePositionOOS  = false;        // Đóng Position khi hết phiên

//--- Component 6: CVD Filter
input string               Settings_CVD         = "=== BỘ LỌC CVD ===";
input bool                 InpUseCVDFilter      = true;         // Bật bộ lọc CVD
input int                  InpCVDLength         = 100;          // CVD Z-Score Window Size
input double               InpCVDLimitStd       = 2.0;          // CVD Standard Deviation Limit
input int                  InpCVDSignalEma      = 9;            // CVD Signal Line EMA Period
input bool                 InpCVDUseRealVol     = false;        // Use Real Volume (False = Tick Volume)


//--- Handles
int h_ema;
int h_atr;

//--- CVD Buffers (internal calculation)
double   g_cvdRaw[];             // Raw cumulative CVD
double   g_cvdZScore[];          // Z-Score of CVD
double   g_cvdSignal[];          // Signal line (EMA of Z-Score)
int      g_cvdSize               = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   // Khởi tạo các Indicator handles
   h_ema = iMA(_Symbol, InpFilterTimeframe, InpEMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   h_atr = iATR(_Symbol, InpEntryTimeframe, InpATRPeriod);
   
   if(h_ema == INVALID_HANDLE || h_atr == INVALID_HANDLE)
     {
      Print("Không thể khởi tạo handles cho Indicators.");
      return(INIT_FAILED);
     }
     
   trade.SetExpertMagicNumber(InpMagicNumber);
   
   // Init CVD arrays
   ArrayFree(g_cvdRaw);
   ArrayFree(g_cvdZScore);
   ArrayFree(g_cvdSignal);
   g_cvdSize = 0;
   
   Print("=== Volatility Rider + CVD Filter Initialized ===");
   Print("CVD Filter: ", (InpUseCVDFilter ? "ON" : "OFF"),
         (InpUseCVDFilter ? " | Window: " + IntegerToString(InpCVDLength) : ""));
   
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   if(h_ema != INVALID_HANDLE) IndicatorRelease(h_ema);
   if(h_atr != INVALID_HANDLE) IndicatorRelease(h_atr);
   ArrayFree(g_cvdRaw);
   ArrayFree(g_cvdZScore);
   ArrayFree(g_cvdSignal);
  }

//+------------------------------------------------------------------+
//| Kiểm tra phiên giao dịch (Session Filter)                       |
//+------------------------------------------------------------------+
bool IsInSession()
  {
   if(!InpUseSession) return true;
   
   MqlDateTime dt;
   TimeCurrent(dt);
   int server_hour = dt.hour;
   
   int start_sv = InpSessionStartGMT + InpGMTOffset;
   int end_sv   = InpSessionEndGMT   + InpGMTOffset;
   
   while(start_sv >= 24) start_sv -= 24;
   while(start_sv < 0)   start_sv += 24;
   while(end_sv >= 24)   end_sv -= 24;
   while(end_sv < 0)     end_sv += 24;
   
   if(start_sv < end_sv)
      return (server_hour >= start_sv && server_hour < end_sv);
   else
      return (server_hour >= start_sv || server_hour < end_sv);
  }

//+------------------------------------------------------------------+
//| Xóa tất cả Pending Orders của EA                                 |
//+------------------------------------------------------------------+
void DeleteAllPendings()
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      ulong pkt = OrderGetTicket(i);
      if(OrderGetString(ORDER_SYMBOL) == _Symbol && OrderGetInteger(ORDER_MAGIC) == InpMagicNumber)
         trade.OrderDelete(pkt);
     }
  }

//+------------------------------------------------------------------+
//| Đóng tất cả Positions của EA                                     |
//+------------------------------------------------------------------+
void CloseAllPositions()
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
         trade.PositionClose(PositionGetTicket(i));
     }
  }

//+------------------------------------------------------------------+
//| Kiểm tra nến mới (New Bar)                                       |
//+------------------------------------------------------------------+
bool IsNewBar(ENUM_TIMEFRAMES timeframe)
  {
   static datetime last_time = 0;
   datetime current_time = iTime(_Symbol, timeframe, 0);
   if(current_time != last_time)
     {
      last_time = current_time;
      return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Calculate CVD Z-Score for all available bars                      |
//+------------------------------------------------------------------+
void CalculateCVD() {
   if(!InpUseCVDFilter) return;
   
   int bars = Bars(Symbol(), Period());
   if(bars < InpCVDLength) return;
   
   // Resize arrays if needed
   if(g_cvdSize != bars) {
      ArrayResize(g_cvdRaw, bars);
      ArrayResize(g_cvdZScore, bars);
      ArrayResize(g_cvdSignal, bars);
      
      if(g_cvdSize == 0 || bars < g_cvdSize) {
         ArrayInitialize(g_cvdRaw, 0);
         ArrayInitialize(g_cvdZScore, 0);
         ArrayInitialize(g_cvdSignal, 0);
         g_cvdSize = 0;
      }
   }
   
   int start = (g_cvdSize > 0) ? (g_cvdSize - 1) : 0;
   double alpha = 2.0 / (InpCVDSignalEma + 1.0);
   
   for(int i = start; i < bars; i++) {
      int bar_shift = bars - 1 - i;
      
      double o = iOpen(Symbol(), Period(), bar_shift);
      double c = iClose(Symbol(), Period(), bar_shift);
      double vol;
      if(InpCVDUseRealVol)
         vol = (double)iVolume(Symbol(), Period(), bar_shift);
      else
         vol = (double)iTickVolume(Symbol(), Period(), bar_shift);
      
      // Raw Delta
      double tick_delta = 0;
      if(c > o)
         tick_delta = vol;
      else if(c < o)
         tick_delta = -vol;
      
      // Cumulative CVD
      g_cvdRaw[i] = (i > 0 ? g_cvdRaw[i-1] : 0.0) + tick_delta;
      
      // Z-Score
      double z_cvd = 0.0;
      if(i >= InpCVDLength - 1) {
         double sum = 0.0;
         int wStart = i - InpCVDLength + 1;
         for(int j = wStart; j <= i; j++)
            sum += g_cvdRaw[j];
         
         double mean_cvd = sum / InpCVDLength;
         
         double sum_sq = 0.0;
         for(int j = wStart; j <= i; j++) {
            double d = g_cvdRaw[j] - mean_cvd;
            sum_sq += d * d;
         }
         
         double std_cvd = MathSqrt(sum_sq / InpCVDLength);
         
         if(std_cvd > 0.0)
            z_cvd = (g_cvdRaw[i] - mean_cvd) / std_cvd;
      }
      
      g_cvdZScore[i] = z_cvd;
      
      // Signal Line (EMA of Z-Score)
      if(i == 0)
         g_cvdSignal[i] = z_cvd;
      else
         g_cvdSignal[i] = z_cvd * alpha + g_cvdSignal[i-1] * (1.0 - alpha);
   }
   
   g_cvdSize = bars;
}

//+------------------------------------------------------------------+
//| Get current CVD Z-Score value (most recent completed bar)         |
//+------------------------------------------------------------------+
double GetCurrentCVD() {
   if(!InpUseCVDFilter || g_cvdSize < 2) return 0.0;
   return g_cvdZScore[g_cvdSize - 2];
}

//+------------------------------------------------------------------+
//| CVD Filter checks                                                 |
//+------------------------------------------------------------------+
bool IsCVDBuyAllowed() {
   if(!InpUseCVDFilter) return true;   // Filter tắt → luôn cho phép
   return (GetCurrentCVD() > 0.0);
}

bool IsCVDSellAllowed() {
   if(!InpUseCVDFilter) return true;   // Filter tắt → luôn cho phép
   return (GetCurrentCVD() < 0.0);
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   // Update CVD mỗi tick
   CalculateCVD();
   
   // Tất cả logic chỉ chạy một lần khi có nến mới trên khung Entry
   if(!IsNewBar(InpEntryTimeframe)) return;
   
   // === SESSION FILTER ===
   bool in_session = IsInSession();

   double ema_arr[];
   double atr_arr[];
   
   // Lấy dữ liệu Indicator ở nến trước đó (đã đóng cửa - index 1)
   if(CopyBuffer(h_ema, 0, 1, 1, ema_arr) <= 0) return;
   if(CopyBuffer(h_atr, 0, 1, 1, atr_arr) <= 0) return;
   
   double ema_val = ema_arr[0];
   double atr_val = atr_arr[0];
   
   // Đọc Close D1 ở nến trước đó để xác định hướng ổn định
   double h4_close = iClose(_Symbol, InpFilterTimeframe, 1);
   bool is_bullish_ema = h4_close > ema_val;
   bool is_bearish_ema = h4_close < ema_val;
   
   // === CVD FILTER ===
   double cvd_val    = GetCurrentCVD();
   bool cvd_buy_ok   = IsCVDBuyAllowed();
   bool cvd_sell_ok  = IsCVDSellAllowed();
   
   // Kết hợp: EMA trend + CVD filter
   bool is_bullish = is_bullish_ema && cvd_buy_ok;
   bool is_bearish = is_bearish_ema && cvd_sell_ok;
   
   // Đếm số lượng lệnh đang mở của EA này
   int pos_count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
        {
         pos_count++;
        }
     }
     
   // Tính Đỉnh cao nhất / Đáy thấp nhất (Donchian Channel) trên nến đóng cửa
   double highest_h1 = 0;
   double lowest_h1 = 0;
   
   int high_idx = iHighest(_Symbol, InpEntryTimeframe, MODE_HIGH, InpDonchianPeriod, 1);
   int low_idx  = iLowest(_Symbol, InpEntryTimeframe, MODE_LOW, InpDonchianPeriod, 1);
   
   if(high_idx != -1) highest_h1 = iHigh(_Symbol, InpEntryTimeframe, high_idx);
   if(low_idx != -1)  lowest_h1  = iLow(_Symbol, InpEntryTimeframe, low_idx);
   
   double stop_level = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL) * _Point;
   double spread = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD) * _Point;
   if(stop_level == 0) stop_level = spread * 2;
   
   // +------------------------------------------------------------------+
   // | QUẢN LÝ LỆNH ĐANG MỞ (LUÔN CHẠY - KỂ CẢ NGOÀI PHIÊN)
   // +------------------------------------------------------------------+
   if(pos_count > 0)
     {
      // Nếu đang có lệnh Market (Positions), xóa tất cả Pending Order thừa
      DeleteAllPendings();
      
      // === Đóng lệnh khi hết phiên (tùy chọn) ===
      if(!in_session && InpClosePositionOOS)
        {
         Print("[VR] ⏰ Hết phiên → Đóng tất cả positions");
         CloseAllPositions();
         return;
        }
      
      // Chandelier Trailing Stop (LUÔN hoạt động bảo vệ vốn)
      for(int i = PositionsTotal() - 1; i >= 0; i--)
        {
         ulong ticket = PositionGetTicket(i);
         if(PositionGetString(POSITION_SYMBOL) == _Symbol && PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
           {
            ENUM_POSITION_TYPE type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
            double current_sl = PositionGetDouble(POSITION_SL);
            
            if(type == POSITION_TYPE_BUY)
              {
               double latest_high = iHigh(_Symbol, InpEntryTimeframe, 1);
               double new_sl = NormalizeDouble(latest_high - (InpTrailingMultiplier * atr_val), _Digits);
               
               if(current_sl == 0 || new_sl > current_sl + _Point)
                 {
                  double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
                  if(new_sl >= bid)
                    {
                     trade.PositionClose(ticket);
                    }
                  else if(new_sl <= bid - stop_level)
                    {
                     trade.PositionModify(ticket, new_sl, 0);
                    }
                 }
              }
            else if(type == POSITION_TYPE_SELL)
              {
               double latest_low = iLow(_Symbol, InpEntryTimeframe, 1);
               double new_sl = NormalizeDouble(latest_low + (InpTrailingMultiplier * atr_val), _Digits);
               
               if(current_sl == 0 || new_sl < current_sl - _Point)
                 {
                  double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
                  if(new_sl <= ask)
                    {
                     trade.PositionClose(ticket);
                    }
                  else if(new_sl >= ask + stop_level)
                    {
                     trade.PositionModify(ticket, new_sl, 0);
                    }
                 }
              }
           }
        }
     }
   // +------------------------------------------------------------------+
   // | QUẢN LÝ LỆNH PENDING (TÍN HIỆU VÀO) - CHỈ TRONG PHIÊN
   // +------------------------------------------------------------------+
   else
     {
      // === NGOÀI PHIÊN: Xóa pending, không đặt lệnh mới ===
      if(!in_session)
        {
         if(InpDeletePendingOOS)
            DeleteAllPendings();
         return;
        }
      
      // === TRONG PHIÊN: Quản lý Pending Orders ===
      bool buy_stop_exists = false;
      bool sell_stop_exists = false;
      ulong buy_stop_ticket = 0;
      ulong sell_stop_ticket = 0;
      
      // Kiểm tra có lệnh Pending nào tồn tại
      for(int i = OrdersTotal() - 1; i >= 0; i--)
        {
         ulong pkt = OrderGetTicket(i);
         if(OrderGetString(ORDER_SYMBOL) == _Symbol && OrderGetInteger(ORDER_MAGIC) == InpMagicNumber)
           {
            ENUM_ORDER_TYPE type = (ENUM_ORDER_TYPE)OrderGetInteger(ORDER_TYPE);
            if(is_bullish && type == ORDER_TYPE_BUY_STOP)
              {
               buy_stop_exists = true;
               buy_stop_ticket = pkt;
              }
            else if(is_bearish && type == ORDER_TYPE_SELL_STOP)
              {
               sell_stop_exists = true;
               sell_stop_ticket = pkt;
              }
            else
              {
               // Xóa lệnh pending không hợp lệ (hướng sai hoặc CVD đổi chiều)
               trade.OrderDelete(pkt);
              }
           }
        }
        
      double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      
      // GIAO DỊCH BULLISH (EMA bullish + CVD > 0)
      if(is_bullish && highest_h1 > 0)
        {
         double target_price = NormalizeDouble(highest_h1, _Digits);
         double target_sl    = NormalizeDouble(target_price - (InpSLMultiplier * atr_val), _Digits);
         
         if(ask < target_price - stop_level)
           {
            if(buy_stop_exists)
              {
               double current_price = OrderGetDouble(ORDER_PRICE_OPEN);
               double current_sl    = OrderGetDouble(ORDER_SL);
               
               if(MathAbs(current_price - target_price) > _Point || MathAbs(current_sl - target_sl) > _Point)
                 {
                  trade.OrderModify(buy_stop_ticket, target_price, target_sl, 0, ORDER_TIME_GTC, 0);
                 }
              }
            else
              {
               string cmt = StringFormat("VR Buy CVD:%.2f", cvd_val);
               trade.BuyStop(InpLotSize, target_price, _Symbol, target_sl, 0, ORDER_TIME_GTC, 0, cmt);
               Print("[VR] ★ BUY STOP at ", DoubleToString(target_price, _Digits),
                     " | SL: ", DoubleToString(target_sl, _Digits),
                     " | CVD: ", DoubleToString(cvd_val, 2));
              }
           }
         else
           {
            if(buy_stop_exists) trade.OrderDelete(buy_stop_ticket);
           }
        }
        
      // GIAO DỊCH BEARISH (EMA bearish + CVD < 0)
      else if(is_bearish && lowest_h1 > 0)
        {
         double target_price = NormalizeDouble(lowest_h1, _Digits);
         double target_sl    = NormalizeDouble(target_price + (InpSLMultiplier * atr_val), _Digits);
         
         if(bid > target_price + stop_level)
           {
            if(sell_stop_exists)
              {
               double current_price = OrderGetDouble(ORDER_PRICE_OPEN);
               double current_sl    = OrderGetDouble(ORDER_SL);
               
               if(MathAbs(current_price - target_price) > _Point || MathAbs(current_sl - target_sl) > _Point)
                 {
                  trade.OrderModify(sell_stop_ticket, target_price, target_sl, 0, ORDER_TIME_GTC, 0);
                 }
              }
            else
              {
               string cmt = StringFormat("VR Sell CVD:%.2f", cvd_val);
               trade.SellStop(InpLotSize, target_price, _Symbol, target_sl, 0, ORDER_TIME_GTC, 0, cmt);
               Print("[VR] ★ SELL STOP at ", DoubleToString(target_price, _Digits),
                     " | SL: ", DoubleToString(target_sl, _Digits),
                     " | CVD: ", DoubleToString(cvd_val, 2));
              }
           }
         else
           {
            if(sell_stop_exists) trade.OrderDelete(sell_stop_ticket);
           }
        }
      // === CVD không khớp hướng EMA → xóa pending nếu có ===
      else
        {
         DeleteAllPendings();
         if(InpUseCVDFilter && (is_bullish_ema || is_bearish_ema))
           {
            string direction = is_bullish_ema ? "BULL" : "BEAR";
            Print("[VR] ✗ ", direction, " blocked by CVD filter (CVD: ", DoubleToString(cvd_val, 2), ")");
           }
        }
     }
  }
//+------------------------------------------------------------------+
