//+------------------------------------------------------------------+
//|                                         The Volatility Rider.mq5 |
//|                                      Auto-generated by Assistant |
//+------------------------------------------------------------------+
#property copyright "Copyright 2024"
#property link      ""
#property version   "1.00"

#include <Trade\Trade.mqh>
CTrade trade;

//--- Hướng giao dịch
enum ENUM_TRADE_DIRECTION {
   TRADE_BOTH      = 0,  // Cả hai (Buy + Sell)
   TRADE_BUY_ONLY  = 1,  // Chỉ Buy
   TRADE_SELL_ONLY = 2   // Chỉ Sell
};

//--- Cài đặt cơ bản
input string               Settings_Base        = "=== CÀI ĐẶT CƠ BẢN ===";
input double               InpLotSize           = 0.01;         // Khối lượng (Lot Size)
input ulong                InpMagicNumber       = 168168;       // Magic Number
input ENUM_TRADE_DIRECTION InpTradeDirection    = TRADE_BOTH;   // Hướng giao dịch

//--- Component 1: Bộ Lọc Xu Hướng (The Macro Filter)
input string               Settings_Trend       = "=== BỘ LỌC XU HƯỚNG ===";
input ENUM_TIMEFRAMES      InpFilterTimeframe   = PERIOD_D1;    // Khung thời gian Xu hướng (D1)
input int                  InpEMAPeriod         = 100;          // Chu kỳ EMA

//--- Component 2: Tín Hiệu Vào Lệnh (The Entry Trigger)
input string               Settings_Entry       = "=== TÍN HIỆU VÀO LỆNH ===";
input ENUM_TIMEFRAMES      InpEntryTimeframe    = PERIOD_H1;    // Khung thời gian Vào lệnh (H1)
input int                  InpDonchianPeriod    = 20;           // Chu kỳ Kênh Donchian (High/Low)

//--- Component 3 & 4: Quản Trị Rủi Ro (Initial SL & Trailing)
input string               Settings_Risk        = "=== QUẢN TRỊ RỦI RO (ATR) ===";
input int                  InpATRPeriod         = 14;           // Chu kỳ ATR
input double               InpSLMultiplier      = 1.5;          // Hệ số SL ban đầu
input double               InpTrailingMultiplier= 3.0;          // Hệ số Trailing Stop (Chandelier)

//--- Component Break-Even (Hòa Vốn)
input string               Settings_BE          = "=== BREAK-EVEN (HÒA VỐN) ===";
input bool                 InpUseBE             = true;         // Bật Break-Even
input double               InpBEMultiplier      = 1.5;          // Kích hoạt BE khi lãi đạt x×ATR (1.5)
input int                  InpBEBufferPoints    = 30;           // Buffer bù phí (points, vd: 30 = 3 pips 5-digit)

//--- Component 5: Bộ Lọc Phiên Giao Dịch (Session Filter)
input string               Settings_Session     = "=== BỘ LỌC PHIÊN GIAO DỊCH ===";
input bool                 InpUseSession        = true;         // Bật bộ lọc phiên
input int                  InpSessionStartGMT   = 7;            // Giờ BẮT ĐẦU phiên (GMT) [07 = Frankfurt Open]
input int                  InpSessionEndGMT     = 20;           // Giờ KẾT THÚC phiên (GMT) [20 = 03:00 GMT+7]
input int                  InpGMTOffset         = 2;            // GMT Offset của Server (vd: 2 = GMT+2)
input bool                 InpDeletePendingOOS  = true;         // Xóa Pending khi hết phiên
input bool                 InpClosePositionOOS  = false;        // Đóng Position khi hết phiên


//--- Handles
int h_ema;
int h_atr;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   // Khởi tạo các Indicator handles
   h_ema = iMA(_Symbol, InpFilterTimeframe, InpEMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   h_atr = iATR(_Symbol, InpEntryTimeframe, InpATRPeriod);
   
   if(h_ema == INVALID_HANDLE || h_atr == INVALID_HANDLE)
     {
      Print("Không thể khởi tạo handles cho Indicators.");
      return(INIT_FAILED);
     }
     
   trade.SetExpertMagicNumber(InpMagicNumber);
   
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   if(h_ema != INVALID_HANDLE) IndicatorRelease(h_ema);
   if(h_atr != INVALID_HANDLE) IndicatorRelease(h_atr);
  }

//+------------------------------------------------------------------+
//| Kiểm tra nến mới (New Bar)                                       |
//+------------------------------------------------------------------+
//+------------------------------------------------------------------+
//| Kiểm tra phiên giao dịch (Session Filter)                       |
//| Chuyển đổi giờ GMT → giờ Server, hỗ trợ qua nửa đêm            |
//+------------------------------------------------------------------+
bool IsInSession()
  {
   if(!InpUseSession) return true;  // Tắt filter → luôn cho phép
   
   MqlDateTime dt;
   TimeCurrent(dt);
   int server_hour = dt.hour;
   
   // Chuyển GMT → Server time
   int start_sv = InpSessionStartGMT + InpGMTOffset;
   int end_sv   = InpSessionEndGMT   + InpGMTOffset;
   
   // Normalize 0-23
   while(start_sv >= 24) start_sv -= 24;
   while(start_sv < 0)   start_sv += 24;
   while(end_sv >= 24)   end_sv -= 24;
   while(end_sv < 0)     end_sv += 24;
   
   // Xử lý trường hợp qua nửa đêm (vd: 22:00 → 05:00)
   if(start_sv < end_sv)
      return (server_hour >= start_sv && server_hour < end_sv);
   else
      return (server_hour >= start_sv || server_hour < end_sv);
  }

//+------------------------------------------------------------------+
//| Xóa tất cả Pending Orders của EA                                 |
//+------------------------------------------------------------------+
void DeleteAllPendings()
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      ulong pkt = OrderGetTicket(i);
      if(OrderGetString(ORDER_SYMBOL) == _Symbol && OrderGetInteger(ORDER_MAGIC) == InpMagicNumber)
         trade.OrderDelete(pkt);
     }
  }

//+------------------------------------------------------------------+
//| Đóng tất cả Positions của EA                                     |
//+------------------------------------------------------------------+
void CloseAllPositions()
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
         trade.PositionClose(PositionGetTicket(i));
     }
  }

//+------------------------------------------------------------------+
//| Kiểm tra nến mới (New Bar)                                       |
//+------------------------------------------------------------------+
bool IsNewBar(ENUM_TIMEFRAMES timeframe)
  {
   static datetime last_time = 0;
   datetime current_time = iTime(_Symbol, timeframe, 0);
   if(current_time != last_time)
     {
      last_time = current_time;
      return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   // Tất cả logic chỉ chạy một lần khi có nến mới trên khung Entry
   if(!IsNewBar(InpEntryTimeframe)) return;
   
   // === SESSION FILTER ===
   bool in_session = IsInSession();

   double ema_arr[];
   double atr_arr[];
   
   // Lấy dữ liệu Indicator ở nến trước đó (đã đóng cửa - index 1)
   if(CopyBuffer(h_ema, 0, 1, 1, ema_arr) <= 0) return;
   if(CopyBuffer(h_atr, 0, 1, 1, atr_arr) <= 0) return;
   
   double ema_val = ema_arr[0];
   double atr_val = atr_arr[0];
   
   // Đọc Close H4 ở nến trước đó để xác định hướng ổn định (chống repainting)
   double h4_close = iClose(_Symbol, InpFilterTimeframe, 1);
   bool is_bullish = h4_close > ema_val;
   bool is_bearish = h4_close < ema_val;
   
   // Đếm số lượng lệnh đang mở của EA này
   int pos_count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
        {
         pos_count++;
        }
     }
     
   // Tính Đỉnh cao nhất / Đáy thấp nhất (Donchian Channel) trên nến đóng cửa
   double highest_h1 = 0;
   double lowest_h1 = 0;
   
   int high_idx = iHighest(_Symbol, InpEntryTimeframe, MODE_HIGH, InpDonchianPeriod, 1);
   int low_idx  = iLowest(_Symbol, InpEntryTimeframe, MODE_LOW, InpDonchianPeriod, 1);
   
   if(high_idx != -1) highest_h1 = iHigh(_Symbol, InpEntryTimeframe, high_idx);
   if(low_idx != -1)  lowest_h1  = iLow(_Symbol, InpEntryTimeframe, low_idx);
   
   double stop_level = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL) * _Point;
   double spread = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD) * _Point;
   if(stop_level == 0) stop_level = spread * 2; // Dự phòng rủi ro nếu broker thiết lập = 0
   
   // +------------------------------------------------------------------+
   // | QUẢN LÝ LỆNH ĐANG MỞ (LUÔN CHẠY - KỂ CẢ NGOÀI PHIÊN)
   // +------------------------------------------------------------------+
   if(pos_count > 0)
     {
      // Nếu đang có lệnh Market (Positions), xóa tất cả Pending Order thừa
      DeleteAllPendings();
      
      // === Đóng lệnh khi hết phiên (tùy chọn) ===
      if(!in_session && InpClosePositionOOS)
        {
         Print("[VR] ⏰ Hết phiên → Đóng tất cả positions");
         CloseAllPositions();
         return;
        }
      
      // =================================================================
      // BREAK-EVEN + CHANDELIER TRAILING (LUÔN hoạt động bảo vệ vốn)
      // =================================================================
      for(int i = PositionsTotal() - 1; i >= 0; i--)
        {
         ulong ticket = PositionGetTicket(i);
         if(PositionGetString(POSITION_SYMBOL) == _Symbol && PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
           {
            ENUM_POSITION_TYPE type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
            double current_sl    = PositionGetDouble(POSITION_SL);
            double open_price    = PositionGetDouble(POSITION_PRICE_OPEN);
            double be_buffer     = InpBEBufferPoints * _Point;
            double be_trigger    = InpBEMultiplier * atr_val;  // Khoảng lãi để kích hoạt BE
            
            if(type == POSITION_TYPE_BUY)
              {
               double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
               double float_profit = bid - open_price;
               
               // === STEP 1: BREAK-EVEN ===
               // Kích hoạt khi lãi >= 1.5×ATR VÀ SL chưa ở hoà vốn
               if(InpUseBE && float_profit >= be_trigger && current_sl < open_price)
                 {
                  double be_sl = NormalizeDouble(open_price + be_buffer, _Digits);
                  if(be_sl <= bid - stop_level)
                    {
                     trade.PositionModify(ticket, be_sl, 0);
                     Print("[VR] ✔ BUY #", ticket, " Break-Even → SL=", DoubleToString(be_sl, _Digits),
                           " (profit=", DoubleToString(float_profit/_Point, 0), " pts, trigger=",
                           DoubleToString(be_trigger/_Point, 0), " pts)");
                    }
                  continue;  // BE xử lý xong, không cần Chandelier tick này
                 }
               
               // === STEP 2: CHANDELIER TRAILING ===
               double latest_high = iHigh(_Symbol, InpEntryTimeframe, 1);
               double new_sl = NormalizeDouble(latest_high - (InpTrailingMultiplier * atr_val), _Digits);
               
               // Chỉ dời lên, không bao giờ dời xuống
               if(current_sl == 0 || new_sl > current_sl + _Point)
                 {
                  if(new_sl >= bid)
                    {
                     trade.PositionClose(ticket);
                    }
                  else if(new_sl <= bid - stop_level)
                    {
                     trade.PositionModify(ticket, new_sl, 0);
                    }
                 }
              }
            else if(type == POSITION_TYPE_SELL)
              {
               double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
               double float_profit = open_price - ask;
               
               // === STEP 1: BREAK-EVEN ===
               if(InpUseBE && float_profit >= be_trigger && (current_sl > open_price || current_sl == 0))
                 {
                  double be_sl = NormalizeDouble(open_price - be_buffer, _Digits);
                  if(be_sl >= ask + stop_level)
                    {
                     trade.PositionModify(ticket, be_sl, 0);
                     Print("[VR] ✔ SELL #", ticket, " Break-Even → SL=", DoubleToString(be_sl, _Digits),
                           " (profit=", DoubleToString(float_profit/_Point, 0), " pts, trigger=",
                           DoubleToString(be_trigger/_Point, 0), " pts)");
                    }
                  continue;
                 }
               
               // === STEP 2: CHANDELIER TRAILING ===
               double latest_low = iLow(_Symbol, InpEntryTimeframe, 1);
               double new_sl = NormalizeDouble(latest_low + (InpTrailingMultiplier * atr_val), _Digits);
               
               // Chỉ dời xuống, không bao giờ dời lên
               if(current_sl == 0 || new_sl < current_sl - _Point)
                 {
                  if(new_sl <= ask)
                    {
                     trade.PositionClose(ticket);
                    }
                  else if(new_sl >= ask + stop_level)
                    {
                     trade.PositionModify(ticket, new_sl, 0);
                    }
                 }
              }
           }
        }
     }
   // +------------------------------------------------------------------+
   // | QUẢN LÝ LỆNH PENDING (TÍN HIỆU VÀO) - CHỈ TRONG PHIÊN
   // +------------------------------------------------------------------+
   else
     {
      // === NGOÀI PHIÊN: Xóa pending, không đặt lệnh mới ===
      if(!in_session)
        {
         if(InpDeletePendingOOS)
            DeleteAllPendings();
         return;
        }
      
      // === TRONG PHIÊN: Quản lý Pending Orders ===
      bool buy_stop_exists = false;
      bool sell_stop_exists = false;
      ulong buy_stop_ticket = 0;
      ulong sell_stop_ticket = 0;
      
      // Kiểm tra có lệnh Pending nào tồn tại
      for(int i = OrdersTotal() - 1; i >= 0; i--)
        {
         ulong pkt = OrderGetTicket(i);
         if(OrderGetString(ORDER_SYMBOL) == _Symbol && OrderGetInteger(ORDER_MAGIC) == InpMagicNumber)
           {
            ENUM_ORDER_TYPE type = (ENUM_ORDER_TYPE)OrderGetInteger(ORDER_TYPE);
            if(is_bullish && type == ORDER_TYPE_BUY_STOP)
              {
               buy_stop_exists = true;
               buy_stop_ticket = pkt;
              }
            else if(is_bearish && type == ORDER_TYPE_SELL_STOP)
              {
               sell_stop_exists = true;
               sell_stop_ticket = pkt;
              }
            else
              {
               // Xóa Limit/Stop lệnh lộn xộn dư thừa
               trade.OrderDelete(pkt);
              }
           }
        }
        
      double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      
      // === LỌc hướng giao dịch ===
      bool allow_buy  = (InpTradeDirection == TRADE_BOTH || InpTradeDirection == TRADE_BUY_ONLY);
      bool allow_sell = (InpTradeDirection == TRADE_BOTH || InpTradeDirection == TRADE_SELL_ONLY);
      
      // GIAO DỊCH BULLISH
      if(is_bullish && highest_h1 > 0 && allow_buy)
        {
         double target_price = NormalizeDouble(highest_h1, _Digits);
         double target_sl    = NormalizeDouble(target_price - (InpSLMultiplier * atr_val), _Digits);
         
         // Đảm bảo giá Stop hợp lệ (khoảng cách > stop_level so với Ask)
         if(ask < target_price - stop_level)
           {
            if(buy_stop_exists)
              {
               double current_price = OrderGetDouble(ORDER_PRICE_OPEN);
               double current_sl    = OrderGetDouble(ORDER_SL);
               
               if(MathAbs(current_price - target_price) > _Point || MathAbs(current_sl - target_sl) > _Point)
                 {
                  trade.OrderModify(buy_stop_ticket, target_price, target_sl, 0, ORDER_TIME_GTC, 0);
                 }
              }
            else
              {
               trade.BuyStop(InpLotSize, target_price, _Symbol, target_sl, 0, ORDER_TIME_GTC, 0, "VR Buy [Session]");
              }
           }
         else
           {
            if(buy_stop_exists) trade.OrderDelete(buy_stop_ticket);
           }
        }
        
      // GIAO DỊCH BEARISH
      else if(is_bearish && lowest_h1 > 0 && allow_sell)
        {
         double target_price = NormalizeDouble(lowest_h1, _Digits);
         double target_sl    = NormalizeDouble(target_price + (InpSLMultiplier * atr_val), _Digits);
         
         if(bid > target_price + stop_level)
           {
            if(sell_stop_exists)
              {
               double current_price = OrderGetDouble(ORDER_PRICE_OPEN);
               double current_sl    = OrderGetDouble(ORDER_SL);
               
               if(MathAbs(current_price - target_price) > _Point || MathAbs(current_sl - target_sl) > _Point)
                 {
                  trade.OrderModify(sell_stop_ticket, target_price, target_sl, 0, ORDER_TIME_GTC, 0);
                 }
              }
            else
              {
               trade.SellStop(InpLotSize, target_price, _Symbol, target_sl, 0, ORDER_TIME_GTC, 0, "VR Sell [Session]");
              }
           }
         else
           {
            if(sell_stop_exists) trade.OrderDelete(sell_stop_ticket);
           }
        }
     }
  }
//+------------------------------------------------------------------+
