//+------------------------------------------------------------------+
//|                                         The Volatility Rider.mq5 |
//|                                      Auto-generated by Assistant |
//+------------------------------------------------------------------+
#property copyright "Copyright 2024"
#property link      ""
#property version   "1.00"

#include <Trade\Trade.mqh>
CTrade trade;

//--- Cài đặt cơ bản
input string               Settings_Base        = "=== CÀI ĐẶT CƠ BẢN ===";
input double               InpLotSize           = 0.01;         // Khối lượng (Lot Size)
input ulong                InpMagicNumber       = 168168;       // Magic Number

//--- Component 1: Bộ Lọc Xu Hướng (The Macro Filter)
input string               Settings_Trend       = "=== BỘ LỌC XU HƯỚNG ===";
input ENUM_TIMEFRAMES      InpFilterTimeframe   = PERIOD_D1;    // Khung thời gian Xu hướng (D1)
input int                  InpEMAPeriod         = 100;          // Chu kỳ EMA

//--- Component 2: Tín Hiệu Vào Lệnh (The Entry Trigger)
input string               Settings_Entry       = "=== TÍN HIỆU VÀO LỆNH ===";
input ENUM_TIMEFRAMES      InpEntryTimeframe    = PERIOD_H1;    // Khung thời gian Vào lệnh (H1)
input int                  InpDonchianPeriod    = 20;           // Chu kỳ Kênh Donchian (High/Low)

enum ENUM_TP_MODE
  {
   TP_CHANDELIER, // 1. Chandelier
   TP_BOTH,       // 2. Chandelier & Thời gian
   TP_TIME        // 3. Chỉ theo Thời gian
  };

//--- Component 3 & 4: Quản Trị Rủi Ro (Initial SL & Trailing)
input string               Settings_Risk        = "=== QUẢN TRỊ RỦI RO (ATR) ===";
input int                  InpATRPeriod         = 14;           // Chu kỳ ATR
input double               InpSLMultiplier      = 1.5;          // Hệ số SL ban đầu
input double               InpTrailingMultiplier= 3.0;          // Hệ số Trailing Stop (Chandelier)

//--- Component 5: Take Profit (Chốt lời)
input string               Settings_TP          = "=== TAKE PROFIT ===";
input ENUM_TP_MODE         InpTPMode            = TP_BOTH;       // Chế độ Take Profit
input int                  InpCloseHour         = 18;            // Giờ đóng lệnh (0-23)
input int                  InpCloseMinute       = 0;             // Phút đóng lệnh (0-59)

//--- Handles
int h_ema;
int h_atr;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   // Khởi tạo các Indicator handles
   h_ema = iMA(_Symbol, InpFilterTimeframe, InpEMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   h_atr = iATR(_Symbol, InpEntryTimeframe, InpATRPeriod);
   
   if(h_ema == INVALID_HANDLE || h_atr == INVALID_HANDLE)
     {
      Print("Không thể khởi tạo handles cho Indicators.");
      return(INIT_FAILED);
     }
     
   trade.SetExpertMagicNumber(InpMagicNumber);
   
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   if(h_ema != INVALID_HANDLE) IndicatorRelease(h_ema);
   if(h_atr != INVALID_HANDLE) IndicatorRelease(h_atr);
  }

//+------------------------------------------------------------------+
//| Kiểm tra nến mới (New Bar)                                       |
//+------------------------------------------------------------------+
bool IsNewBar(ENUM_TIMEFRAMES timeframe)
  {
   static datetime last_time = 0;
   datetime current_time = iTime(_Symbol, timeframe, 0);
   if(current_time != last_time)
     {
      last_time = current_time;
      return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   // ==========================
   // KIỂM TRA ĐÓNG LỆNH THEO THỜI GIAN
   // ==========================
   bool timeToClose = false;
   if(InpTPMode == TP_BOTH || InpTPMode == TP_TIME)
     {
      MqlDateTime dt;
      TimeCurrent(dt);
      int current_minutes = dt.hour * 60 + dt.min;
      int close_minutes = InpCloseHour * 60 + InpCloseMinute;
      if(current_minutes >= close_minutes)
        {
         timeToClose = true;
        }
     }

   if(timeToClose)
     {
      for(int i = PositionsTotal() - 1; i >= 0; i--)
        {
         ulong ticket = PositionGetTicket(i);
         if(PositionGetString(POSITION_SYMBOL) == _Symbol && PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
           {
            trade.PositionClose(ticket);
           }
        }
      for(int i = OrdersTotal() - 1; i >= 0; i--)
        {
         ulong pkt = OrderGetTicket(i);
         if(OrderGetString(ORDER_SYMBOL) == _Symbol && OrderGetInteger(ORDER_MAGIC) == InpMagicNumber)
           {
            trade.OrderDelete(pkt);
           }
        }
     }

   // Tất cả logic chỉ chạy một lần khi có nến mới trên khung H1
   if(!IsNewBar(InpEntryTimeframe)) return;
   
   if(timeToClose) return; // Không mở lệnh mới nếu đã qua giờ chốt trong ngày

   double ema_arr[];
   double atr_arr[];
   
   // Lấy dữ liệu Indicator ở nến trước đó (đã đóng cửa - index 1)
   if(CopyBuffer(h_ema, 0, 1, 1, ema_arr) <= 0) return;
   if(CopyBuffer(h_atr, 0, 1, 1, atr_arr) <= 0) return;
   
   double ema_val = ema_arr[0];
   double atr_val = atr_arr[0];
   
   // Đọc Close H4 ở nến trước đó để xác định hướng ổn định (chống repainting)
   double h4_close = iClose(_Symbol, InpFilterTimeframe, 1);
   bool is_bullish = h4_close > ema_val;
   bool is_bearish = h4_close < ema_val;
   
   // Đếm số lượng lệnh đang mở của EA này
   int pos_count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
        {
         pos_count++;
        }
     }
     
   // Tính Đỉnh cao nhất / Đáy thấp nhất (Donchian Channel) trên nến đóng cửa
   double highest_h1 = 0;
   double lowest_h1 = 0;
   
   int high_idx = iHighest(_Symbol, InpEntryTimeframe, MODE_HIGH, InpDonchianPeriod, 1);
   int low_idx  = iLowest(_Symbol, InpEntryTimeframe, MODE_LOW, InpDonchianPeriod, 1);
   
   if(high_idx != -1) highest_h1 = iHigh(_Symbol, InpEntryTimeframe, high_idx);
   if(low_idx != -1)  lowest_h1  = iLow(_Symbol, InpEntryTimeframe, low_idx);
   
   double stop_level = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL) * _Point;
   double spread = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD) * _Point;
   if(stop_level == 0) stop_level = spread * 2; // Dự phòng rủi ro nếu broker thiết lập = 0
   
   // +------------------------------------------------------------------+
   // | QUẢN LÝ QUẢN TRỊ RỦI RO & DỜI SL QUẢN LÝ LỆNH ĐANG MỞ
   // +------------------------------------------------------------------+
   if(pos_count > 0)
     {
      // Nếu đang có lệnh Market (Positions), xóa tất cả Pending Order thừa
      for(int i = OrdersTotal() - 1; i >= 0; i--)
        {
         ulong pkt = OrderGetTicket(i);
         if(OrderGetString(ORDER_SYMBOL) == _Symbol && OrderGetInteger(ORDER_MAGIC) == InpMagicNumber)
           {
            trade.OrderDelete(pkt);
           }
        }
      
      // Chandelier Trailing Stop
      if(InpTPMode == TP_CHANDELIER || InpTPMode == TP_BOTH)
        {
         for(int i = PositionsTotal() - 1; i >= 0; i--)
           {
            ulong ticket = PositionGetTicket(i);
            if(PositionGetString(POSITION_SYMBOL) == _Symbol && PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
              {
               ENUM_POSITION_TYPE type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
               double current_sl = PositionGetDouble(POSITION_SL);
               
               if(type == POSITION_TYPE_BUY)
                 {
               // SL với Buy: SL = Giá Cao Mới - (3 * ATR)
               double latest_high = iHigh(_Symbol, InpEntryTimeframe, 1);
               double new_sl = NormalizeDouble(latest_high - (InpTrailingMultiplier * atr_val), _Digits);
               
               // Chỉ dời lên, không bao giờ dời xuống
               if(current_sl == 0 || new_sl > current_sl + _Point)
                 {
                  double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
                  if(new_sl >= bid) // Chandelier chạm giá nhưng lệnh chưa ngắt
                    {
                     trade.PositionClose(ticket);
                    }
                  else if(new_sl <= bid - stop_level)
                    {
                     trade.PositionModify(ticket, new_sl, 0); // SL + TP(0)
                    }
                 }
              }
            else if(type == POSITION_TYPE_SELL)
              {
               // SL với Sell: SL = Giá Thấp Mới + (3 * ATR)
               double latest_low = iLow(_Symbol, InpEntryTimeframe, 1);
               double new_sl = NormalizeDouble(latest_low + (InpTrailingMultiplier * atr_val), _Digits);
               
               // Chỉ dời xuống, không bao giờ dời lên
               if(current_sl == 0 || new_sl < current_sl - _Point)
                 {
                  double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
                  if(new_sl <= ask)
                    {
                     trade.PositionClose(ticket);
                    }
                  else if(new_sl >= ask + stop_level)
                    {
                     trade.PositionModify(ticket, new_sl, 0);
                    }
                 }
              }
           }
        }
        }
     }
   // +------------------------------------------------------------------+
   // | QUẢN LÝ LỆNH PENDING (TÍN HIỆU VÀO) KHI KHÔNG CÓ POSITIONS MỞ
   // +------------------------------------------------------------------+
   else
     {
      bool buy_stop_exists = false;
      bool sell_stop_exists = false;
      ulong buy_stop_ticket = 0;
      ulong sell_stop_ticket = 0;
      
      // Kiểm tra có lệnh Pending nào tồn tại
      for(int i = OrdersTotal() - 1; i >= 0; i--)
        {
         ulong pkt = OrderGetTicket(i);
         if(OrderGetString(ORDER_SYMBOL) == _Symbol && OrderGetInteger(ORDER_MAGIC) == InpMagicNumber)
           {
            ENUM_ORDER_TYPE type = (ENUM_ORDER_TYPE)OrderGetInteger(ORDER_TYPE);
            if(is_bullish && type == ORDER_TYPE_BUY_STOP)
              {
               buy_stop_exists = true;
               buy_stop_ticket = pkt;
              }
            else if(is_bearish && type == ORDER_TYPE_SELL_STOP)
              {
               sell_stop_exists = true;
               sell_stop_ticket = pkt;
              }
            else
              {
               // Xóa Limit/Stop lệnh lộn xộn dư thừa
               trade.OrderDelete(pkt);
              }
           }
        }
        
      double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      
      // GIAO DỊCH BULLISH
      if(is_bullish && highest_h1 > 0)
        {
         double target_price = NormalizeDouble(highest_h1, _Digits);
         double target_sl    = NormalizeDouble(target_price - (InpSLMultiplier * atr_val), _Digits);
         
         // Đảm bảo giá Stop hợp lệ (khỏang cách > stop_level so với Ask)
         if(ask < target_price - stop_level)
           {
            if(buy_stop_exists)
              {
               // Modify nếu kênh Donchian bị trượt tạo đỉnh mới hoặc ATR thay đổi
               double current_price = OrderGetDouble(ORDER_PRICE_OPEN);
               double current_sl    = OrderGetDouble(ORDER_SL);
               
               if(MathAbs(current_price - target_price) > _Point || MathAbs(current_sl - target_sl) > _Point)
                 {
                  trade.OrderModify(buy_stop_ticket, target_price, target_sl, 0, ORDER_TIME_GTC, 0);
                 }
              }
            else
              {
               trade.BuyStop(InpLotSize, target_price, _Symbol, target_sl, 0, ORDER_TIME_GTC, 0, "Volatility Rider Buy");
              }
           }
         else
           {
            // Trong trường hợp giá hiện tại đã cao hơn đỉnh (do gáp giá đầu nến hoặc dao động mạnh chưa được phát hiện là break), xóa lệnh bảo lưu.
            if(buy_stop_exists) trade.OrderDelete(buy_stop_ticket);
           }
        }
        
      // GIAO DỊCH BEARISH
      else if(is_bearish && lowest_h1 > 0)
        {
         double target_price = NormalizeDouble(lowest_h1, _Digits);
         double target_sl    = NormalizeDouble(target_price + (InpSLMultiplier * atr_val), _Digits);
         
         if(bid > target_price + stop_level)
           {
            if(sell_stop_exists)
              {
               double current_price = OrderGetDouble(ORDER_PRICE_OPEN);
               double current_sl    = OrderGetDouble(ORDER_SL);
               
               if(MathAbs(current_price - target_price) > _Point || MathAbs(current_sl - target_sl) > _Point)
                 {
                  trade.OrderModify(sell_stop_ticket, target_price, target_sl, 0, ORDER_TIME_GTC, 0);
                 }
              }
            else
              {
               trade.SellStop(InpLotSize, target_price, _Symbol, target_sl, 0, ORDER_TIME_GTC, 0, "Volatility Rider Sell");
              }
           }
         else
           {
            if(sell_stop_exists) trade.OrderDelete(sell_stop_ticket);
           }
        }
     }
  }
//+------------------------------------------------------------------+
