//+------------------------------------------------------------------+
//|                                              KalmanTrend_EA.mq5  |
//|                                  Copyright 2024, Vu (Antigravity)|
//+------------------------------------------------------------------+
#property copyright "Vu - Generated by AI"
#property link      "https://antigravity.ide"
#property version   "1.00"
#property description "EA Kalman Trend Retest (The Kalman Bias + ATR Killzone)"
#property description "Dựa trên Kalman Trend Levels [BigBeluga]"

#include <Trade\Trade.mqh>
CTrade trade;

//--- inputs
input group "=== General Settings ==="
input double InpFixLot          = 0.01;    // Fixed Lot Size
input ulong  InpMagicNumber     = 66666;   // Magic Number
input int    InpSlippage        = 3;       // Slippage

input group "=== Kalman Settings ==="
input int    InpShortLen        = 50;      // Kalman Short Length
input int    InpLongLen         = 150;     // Kalman Long Length
input double InpKalmanR         = 0.01;    // Kalman R (Measurement Noise)
input double InpKalmanQ         = 0.1;     // Kalman Q (Process Noise)
input int    InpATRPeriod       = 200;     // ATR Period for Box Thickness
input double InpATRMult         = 0.5;     // ATR Multiplier for Box

input group "=== Display Settings ==="
input color  ClrBullish         = clrLime;          // Bullish Color
input color  ClrBearish         = clrRed;           // Bearish Color  
input color  ClrNeutral         = clrGray;          // Neutral / Momentum Loss Color
input color  ClrBoxBull         = clrForestGreen;   // Bull Box Color
input color  ClrBoxBear         = clrCrimson;       // Bear Box Color

//--- Kalman Filter state (persistent across bars)
struct KalmanState {
   double estimate;
   double error_est;
   bool   initialized;
};

KalmanState ks_short;
KalmanState ks_long;

//--- Box tracking
struct RetestBox {
   double top;
   double bottom;
   datetime start_time;
   bool   active;
   string obj_name;
};

RetestBox lower_box; // Support box (in uptrend)
RetestBox upper_box; // Resistance box (in downtrend)

//--- Global state
double   prev_short_kalman = 0;
double   prev_long_kalman = 0;
double   prev_prev_short_kalman = 0; // short_kalman[2] equivalent
bool     prev_trend_up = false;
bool     was_bull_momentum = false;  // track candle color for exit
bool     was_bear_momentum = false;

datetime last_bar_time = 0;
int      atr_handle = INVALID_HANDLE;

//+------------------------------------------------------------------+
//| Kalman Filter Update                                             |
//+------------------------------------------------------------------+
double KalmanUpdate(KalmanState &state, double src, int length, double R, double Q) {
   if(!state.initialized) {
      state.estimate = src;
      state.error_est = 1.0;
      state.initialized = true;
      return src;
   }
   
   double error_meas = R * length;
   double prediction = state.estimate;
   double kalman_gain = state.error_est / (state.error_est + error_meas);
   
   state.estimate = prediction + kalman_gain * (src - prediction);
   state.error_est = (1.0 - kalman_gain) * state.error_est + Q / length;
   
   return state.estimate;
}

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit() {
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   
   // Initialize Kalman states
   ks_short.initialized = false;
   ks_short.estimate = 0;
   ks_short.error_est = 1.0;
   
   ks_long.initialized = false;
   ks_long.estimate = 0;
   ks_long.error_est = 1.0;
   
   // Initialize boxes
   lower_box.active = false;
   upper_box.active = false;
   
   prev_trend_up = false;
   was_bull_momentum = false;
   was_bear_momentum = false;
   
   // ATR handle
   atr_handle = iATR(Symbol(), Period(), InpATRPeriod);
   if(atr_handle == INVALID_HANDLE) {
      Print("Error creating ATR handle");
      return(INIT_FAILED);
   }
   
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason) {
   if(atr_handle != INVALID_HANDLE)
      IndicatorRelease(atr_handle);
}

//+------------------------------------------------------------------+
//| Draw / Extend Box on Chart                                       |
//+------------------------------------------------------------------+
void DrawBox(RetestBox &box_ref, color clr) {
   if(!box_ref.active) return;
   
   // Delete old box object if exists
   if(ObjectFind(0, box_ref.obj_name) >= 0)
      ObjectDelete(0, box_ref.obj_name);
   
   // Draw new rectangle from start_time to current time  
   datetime t_end = iTime(Symbol(), Period(), 0) + 50 * PeriodSeconds();
   
   ObjectCreate(0, box_ref.obj_name, OBJ_RECTANGLE, 0,
                box_ref.start_time, box_ref.top,
                t_end, box_ref.bottom);
   ObjectSetInteger(0, box_ref.obj_name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, box_ref.obj_name, OBJPROP_FILL, true);
   ObjectSetInteger(0, box_ref.obj_name, OBJPROP_BACK, true);
   ObjectSetInteger(0, box_ref.obj_name, OBJPROP_STYLE, STYLE_SOLID);
   ObjectSetInteger(0, box_ref.obj_name, OBJPROP_WIDTH, 1);
   
   // Set transparency 
   color fill_clr = clr;
   ObjectSetInteger(0, box_ref.obj_name, OBJPROP_COLOR, fill_clr);
}

//+------------------------------------------------------------------+
//| Draw Crossover Label                                             |
//+------------------------------------------------------------------+
void DrawCrossLabel(string name, datetime t, double price, string text, color clr, bool is_up) {
   ObjectCreate(0, name, OBJ_TEXT, 0, t, price);
   ObjectSetString(0, name, OBJPROP_TEXT, text);
   ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, name, OBJPROP_FONTSIZE, 14);
   ObjectSetString(0, name, OBJPROP_FONT, "Arial Bold");
   ObjectSetInteger(0, name, OBJPROP_ANCHOR, is_up ? ANCHOR_UPPER : ANCHOR_LOWER);
}

//+------------------------------------------------------------------+
//| Draw Signal Arrow                                                |
//+------------------------------------------------------------------+
void DrawSignalArrow(string name, datetime t, double price, color clr, bool is_buy) {
   if(is_buy) {
      ObjectCreate(0, name, OBJ_ARROW_BUY, 0, t, price);
   } else {
      ObjectCreate(0, name, OBJ_ARROW_SELL, 0, t, price);
   }
   ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, name, OBJPROP_WIDTH, 2);
}

//+------------------------------------------------------------------+
//| Draw Kalman Lines on Chart                                       |
//+------------------------------------------------------------------+
void DrawKalmanDot(string prefix, datetime t, double value, color clr, int width) {
   string name = prefix + TimeToString(t, TIME_DATE|TIME_MINUTES);
   StringReplace(name, ":", "");
   StringReplace(name, " ", "_");
   
   ObjectCreate(0, name, OBJ_ARROW, 0, t, value);
   ObjectSetInteger(0, name, OBJPROP_ARROWCODE, 159); // Small dot
   ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, name, OBJPROP_WIDTH, width);
   ObjectSetInteger(0, name, OBJPROP_BACK, true);
}

//+------------------------------------------------------------------+
//| Check if we have an open position                                |
//+------------------------------------------------------------------+
bool HasOpenPosition(ENUM_POSITION_TYPE &pos_type) {
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      string symbol = PositionGetSymbol(i);
      ulong magic = PositionGetInteger(POSITION_MAGIC);
      if(symbol == Symbol() && magic == InpMagicNumber) {
         pos_type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
         return true;
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| Close all positions of this EA                                   |
//+------------------------------------------------------------------+
void CloseAllPositions() {
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      string symbol = PositionGetSymbol(i);
      ulong magic = PositionGetInteger(POSITION_MAGIC);
      if(symbol == Symbol() && magic == InpMagicNumber) {
         ulong ticket = PositionGetTicket(i);
         trade.PositionClose(ticket);
      }
   }
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick() {
   datetime current_time = iTime(Symbol(), Period(), 0);
   if(current_time == last_bar_time) return;
   last_bar_time = current_time;
   
   // We process on close of previous bar (shift=1) for confirmation
   double close1 = iClose(Symbol(), Period(), 1);
   double low1   = iLow(Symbol(), Period(), 1);
   double high1  = iHigh(Symbol(), Period(), 1);
   
   if(close1 == 0) return;
   
   // Get ATR value
   double atr_buf[];
   if(CopyBuffer(atr_handle, 0, 1, 1, atr_buf) <= 0) return;
   double atr_val = atr_buf[0] * InpATRMult;
   
   // Save previous states (shift back)
   prev_prev_short_kalman = prev_short_kalman;
   double old_short = prev_short_kalman;
   double old_long  = prev_long_kalman;
   bool   old_trend_up = prev_trend_up;
   
   // ============================================================
   // Component 1: Kalman Filter Update
   // ============================================================
   double short_kalman = KalmanUpdate(ks_short, close1, InpShortLen, InpKalmanR, InpKalmanQ);
   double long_kalman  = KalmanUpdate(ks_long, close1, InpLongLen, InpKalmanR, InpKalmanQ);
   
   bool trend_up = (short_kalman > long_kalman);
   
   // Candle color logic from Pine:
   // trend_up AND short_kalman > short_kalman[2] => GREEN (bull momentum)
   // NOT trend_up AND short_kalman < short_kalman[2] => RED (bear momentum) 
   // else => GRAY (momentum loss)
   bool bull_momentum = trend_up && (short_kalman > prev_prev_short_kalman);
   bool bear_momentum = !trend_up && (short_kalman < prev_prev_short_kalman);
   bool neutral_momentum = !bull_momentum && !bear_momentum;
   
   // Visual: Draw Kalman dots on chart
   datetime bar_time = iTime(Symbol(), Period(), 1);
   
   // Color for short kalman line (trend_col1 in Pine)
   color short_clr = (short_kalman > prev_prev_short_kalman) ? ClrBullish : ClrBearish;
   // Color for long kalman line (trend_col in Pine)
   color long_clr = trend_up ? ClrBullish : ClrBearish;
   
   DrawKalmanDot("KS_", bar_time, short_kalman, short_clr, 1);
   DrawKalmanDot("KL_", bar_time, long_kalman, long_clr, 2);
   
   // ============================================================
   // Component 2: Box Creation at Crossover
   // ============================================================
   
   // Bullish crossover: short crosses ABOVE long
   if(trend_up && !old_trend_up) {
      // Create Lower Box (Support)
      lower_box.top = low1 + atr_val;
      lower_box.bottom = low1;
      lower_box.start_time = bar_time;
      lower_box.active = true;
      lower_box.obj_name = "KT_LBox_" + IntegerToString((long)bar_time);
      
      DrawBox(lower_box, ClrBoxBull);
      
      // Draw crossover label
      string lbl_name = "KT_CrossUp_" + IntegerToString((long)bar_time);
      DrawCrossLabel(lbl_name, bar_time, short_kalman - atr_val * 0.5, 
                     "▲ " + DoubleToString(close1, _Digits), ClrBullish, true);
   }
   
   // Bearish crossover: short crosses BELOW long
   if(!trend_up && old_trend_up) {
      // Create Upper Box (Resistance)
      upper_box.top = high1;
      upper_box.bottom = high1 - atr_val;
      upper_box.start_time = bar_time;
      upper_box.active = true;
      upper_box.obj_name = "KT_UBox_" + IntegerToString((long)bar_time);
      
      DrawBox(upper_box, ClrBoxBear);
      
      // Draw crossover label
      string lbl_name = "KT_CrossDn_" + IntegerToString((long)bar_time);
      DrawCrossLabel(lbl_name, bar_time, short_kalman + atr_val * 0.5,
                     DoubleToString(close1, _Digits) + " ▼", ClrBearish, false);
   }
   
   // Extend boxes to current bar
   if(lower_box.active) DrawBox(lower_box, ClrBoxBull);
   if(upper_box.active) DrawBox(upper_box, ClrBoxBear);
   
   // ============================================================
   // Component 3: Retest Signal Detection + Entry
   // ============================================================
   // Previous bar data (shift=2) for crossover detection in retest
   double low2  = iLow(Symbol(), Period(), 2);
   double high2 = iHigh(Symbol(), Period(), 2);
   
   ENUM_POSITION_TYPE pos_type;
   bool has_position = HasOpenPosition(pos_type);
   
   // BUY SIGNAL: low bounces off lower_box top
   // Pine: low > lower_box.get_top() and low[1] <= lower_box.get_top()
   bool buy_retest = lower_box.active && 
                     (low1 > lower_box.top && low2 <= lower_box.top);
   
   // SELL SIGNAL: high bounces off upper_box bottom
   // Pine: high < upper_box.get_bottom() and high[1] >= upper_box.get_bottom()
   bool sell_retest = upper_box.active && 
                      (high1 < upper_box.bottom && high2 >= upper_box.bottom);
   
   if(buy_retest && !has_position) {
      double ask = SymbolInfoDouble(Symbol(), SYMBOL_ASK);
      double spread = SymbolInfoDouble(Symbol(), SYMBOL_ASK) - SymbolInfoDouble(Symbol(), SYMBOL_BID);
      
      // Component 4: SL dưới mép dưới Lower Box + spread
      double sl = NormalizeDouble(lower_box.bottom - spread, _Digits);
      
      if(trade.Buy(InpFixLot, Symbol(), ask, sl, 0, "Kalman Retest Buy")) {
         // Draw signal
         string sig_name = "KT_BuySig_" + IntegerToString((long)bar_time);
         DrawSignalArrow(sig_name, iTime(Symbol(), Period(), 1), low1 - atr_val * 0.3, ClrBullish, true);
         
         // Draw "+" text
         string txt_name = "KT_BuyTxt_" + IntegerToString((long)bar_time);
         DrawCrossLabel(txt_name, iTime(Symbol(), Period(), 1), low1 - atr_val * 0.6, "+", ClrBullish, true);
      }
   }
   
   if(sell_retest && !has_position) {
      double bid = SymbolInfoDouble(Symbol(), SYMBOL_BID);
      double spread = SymbolInfoDouble(Symbol(), SYMBOL_ASK) - SymbolInfoDouble(Symbol(), SYMBOL_BID);
      
      // Component 4: SL trên mép trên Upper Box + spread
      double sl = NormalizeDouble(upper_box.top + spread, _Digits);
      
      if(trade.Sell(InpFixLot, Symbol(), bid, sl, 0, "Kalman Retest Sell")) {
         // Draw signal
         string sig_name = "KT_SellSig_" + IntegerToString((long)bar_time);
         DrawSignalArrow(sig_name, iTime(Symbol(), Period(), 1), high1 + atr_val * 0.3, ClrBearish, false);
         
         // Draw "x" text
         string txt_name = "KT_SellTxt_" + IntegerToString((long)bar_time);
         DrawCrossLabel(txt_name, iTime(Symbol(), Period(), 1), high1 + atr_val * 0.6, "x", ClrBearish, false);
      }
   }
   
   // ============================================================
   // Component 5: Momentum Trailing Exit (Candle Color Change)
   // ============================================================
   if(has_position) {
      // EXIT LONG: Was Green (bull momentum), now Gray or Red
      if(pos_type == POSITION_TYPE_BUY) {
         if(was_bull_momentum && (neutral_momentum || bear_momentum)) {
            CloseAllPositions();
            
            // Draw exit marker
            string exit_name = "KT_ExitL_" + IntegerToString((long)bar_time);
            DrawCrossLabel(exit_name, bar_time, high1 + atr_val * 0.3, "✕ EXIT", ClrNeutral, false);
         }
      }
      
      // EXIT SHORT: Was Red (bear momentum), now Gray or Green
      if(pos_type == POSITION_TYPE_SELL) {
         if(was_bear_momentum && (neutral_momentum || bull_momentum)) {
            CloseAllPositions();
            
            // Draw exit marker
            string exit_name = "KT_ExitS_" + IntegerToString((long)bar_time);
            DrawCrossLabel(exit_name, bar_time, low1 - atr_val * 0.3, "✕ EXIT", ClrNeutral, true);
         }
      }
   }
   
   // Save states for next bar
   prev_short_kalman = short_kalman;
   prev_long_kalman = long_kalman;
   prev_trend_up = trend_up;
   was_bull_momentum = bull_momentum;
   was_bear_momentum = bear_momentum;
}
//+------------------------------------------------------------------+
