//+------------------------------------------------------------------+
//|                                              MonteCarlo_Cone.mq5 |
//|                                  Copyright 2024, Vu (Antigravity)|
//+------------------------------------------------------------------+
#property copyright "Vu - Generated by AI"
#property link      "https://antigravity.ide"
#property version   "1.00"
#property description "EA Hồi Quy Nón Xác Suất (The Cone Reversion)"
#property description "Dựa trên mô phỏng Monte Carlo 1000 lượt"

#include <Trade\Trade.mqh>
CTrade trade;

//--- inputs
input group "=== General Settings ==="
input int    InpTradeDuration   = 100;     // Max Trade Duration (bars)
input double InpFixLot          = 0.01;     // Fixed Lot Size for Trade
input ulong  InpMagicNumber     = 55555;   // Magic Number
input int    InpSlippage        = 3;       // Slippage

input group "=== Calculation Settings ==="
input int    InpLocLookback     = 252;     // Projection Lookback (bars)
input int    InpSimulations     = 1000;    // Monte Carlo Simulations
input double InpRiskFreeRate    = 5.0;     // Annual Risk-Free Rate (%)
input double InpMinSharpe       = 0.5;     // Minimum Sharpe Ratio (EV Filter)
input double InpMinWinRate      = 55.0;    // Minimum Win Rate (%) (EV Filter)

input group "=== Display Settings ==="
input color  ClrConeEV          = clrMediumOrchid; // EV Line Color
input color  ClrConeBands       = clrWhite;        // Bounds Color
input color  ClrSignalBuy       = clrLime;         // Buy Signal Color

//--- global variables
bool     cone_active = false;
datetime cone_anchor_time = 0;
double   cone_anchor_price = 0;
double   cone_target_ev = 0;
double   cone_target_upper = 0;
double   cone_target_lower = 0;
int      cone_age = 0;
string   cone_id_str = "";
bool     trade_opened_for_cone = false; // Block multiple entries in same cone

datetime last_bar_time = 0;

//+------------------------------------------------------------------+
//| Random function (30 bits entropy)                                |
//+------------------------------------------------------------------+
double RandomDouble() {
   double r = (MathRand() * 32768.0 + MathRand()) / 1073741824.0; 
   if(r <= 0.0) r = 0.000001; 
   return r;
}

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit() {
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   MathSrand(GetTickCount());
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason) {
   // Không xóa object trên chart khi Deinit để người dùng có thể xem lại lịch sử
   // ObjectsDeleteAll(0, "MCEV_");
}

//+------------------------------------------------------------------+
//| Draw Cone Line on Chart                                          |
//+------------------------------------------------------------------+
void DrawConeLine(string name, double price1, double price2, color clr, ENUM_LINE_STYLE style, int width) {
   // Tìm khoảng cách cho visual
   datetime t2 = cone_anchor_time + InpTradeDuration * PeriodSeconds(); 
   
   ObjectCreate(0, name, OBJ_TREND, 0, cone_anchor_time, price1, t2, price2);
   ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, name, OBJPROP_STYLE, style);
   ObjectSetInteger(0, name, OBJPROP_WIDTH, width);
   ObjectSetInteger(0, name, OBJPROP_RAY_RIGHT, false);
   ObjectSetInteger(0, name, OBJPROP_BACK, true);
   ObjectSetString(0, name, OBJPROP_TOOLTIP, name);
   ObjectSetInteger(0, name, OBJPROP_HIDDEN, true);
}

//+------------------------------------------------------------------+
//| Check condition for New Cone (Anchor)                            |
//+------------------------------------------------------------------+
void CheckNewCone(int shift) {
   if(cone_active) return;
   
   // Đủ data
   if(iBars(Symbol(), Period()) < InpLocLookback + 50) return;
   
   double returns[];
   ArrayResize(returns, InpLocLookback);
   
   double sum = 0;
   for(int i=0; i<InpLocLookback; i++) {
      double c1 = iClose(Symbol(), Period(), shift + i);
      double c2 = iClose(Symbol(), Period(), shift + i + 1);
      if(c2 == 0) return;
      returns[i] = MathLog(c1 / c2);
      sum += returns[i];
   }
   
   double mu = sum / InpLocLookback;
   double sum2 = 0;
   for(int i=0; i<InpLocLookback; i++) {
      sum2 += MathPow(returns[i] - mu, 2);
   }
   double stdev = MathSqrt(sum2 / InpLocLookback);
   
   double ann_factor = (365.0 * 24.0 * 60.0 * 60.0) / PeriodSeconds();
   if(Period() >= PERIOD_D1) ann_factor = 252.0; 
   
   double long_trend = mu * ann_factor * 100.0;
   double long_vol   = stdev * MathSqrt(ann_factor) * 100.0;
   
   double sharpe = 0;
   if(long_vol > 0) sharpe = (long_trend - InpRiskFreeRate) / long_vol;
   
   double total_drift = mu * InpTradeDuration;
   double total_vol   = stdev * MathSqrt(InpTradeDuration);
   
   double sum_ret = 0, sum_ret2 = 0;
   int wins = 0;
   
   // Monte Carlo Sim
   for(int i=0; i<InpSimulations; i++) {
      double u1 = RandomDouble();
      double u2 = RandomDouble();
      double std_norm = MathSqrt(-2.0 * MathLog(u1)) * MathCos(2.0 * M_PI * u2);
      
      double log_ret_sim = total_drift + std_norm * total_vol;
      double ret_sim = MathExp(log_ret_sim) - 1.0;
      
      sum_ret += ret_sim;
      sum_ret2 += ret_sim * ret_sim;
      if(ret_sim > 0.0) wins++;
   }
   
   double avg_ret = sum_ret / InpSimulations;
   double var_sim = (sum_ret2 - InpSimulations * avg_ret * avg_ret) / InpSimulations;
   if(var_sim < 0) var_sim = 0;
   double period_vol = MathSqrt(var_sim);
   
   double wr_pct = ((double)wins / InpSimulations) * 100.0;
   
   // Component 1: Màng Lọc Kỳ Vọng (The EV Filter)
   if(sharpe > InpMinSharpe && wr_pct > InpMinWinRate) {
      cone_active = true;
      cone_anchor_time = iTime(Symbol(), Period(), shift);
      cone_anchor_price = iClose(Symbol(), Period(), shift);
      cone_age = 0;
      trade_opened_for_cone = false; 
      
      string time_str = TimeToString(cone_anchor_time, TIME_DATE|TIME_MINUTES);
      StringReplace(time_str, ":", ""); 
      StringReplace(time_str, " ", "_"); 
      StringReplace(time_str, ".", "");
      cone_id_str = "MCEV_" + time_str;
      
      cone_target_ev    = cone_anchor_price * (1.0 + avg_ret);
      cone_target_upper = cone_anchor_price * (1.0 + avg_ret + period_vol);
      cone_target_lower = cone_anchor_price * (1.0 + avg_ret - period_vol);
      
      DrawConeLine(cone_id_str + "_EV", cone_anchor_price, cone_target_ev, ClrConeEV, STYLE_SOLID, 2);
      DrawConeLine(cone_id_str + "_UP", cone_anchor_price, cone_target_upper, ClrConeBands, STYLE_DASH, 1);
      DrawConeLine(cone_id_str + "_DN", cone_anchor_price, cone_target_lower, ClrConeBands, STYLE_DASH, 1);
   }
}

//+------------------------------------------------------------------+
//| Update Take Profit for Active Buy Orders                         |
//+------------------------------------------------------------------+
void TrailingTPtoEV() {
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      string symbol = PositionGetSymbol(i);
      ulong magic = PositionGetInteger(POSITION_MAGIC);
      
      if(symbol == Symbol() && magic == InpMagicNumber) {
         if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) {
            double current_ev = cone_anchor_price + cone_age * (cone_target_ev - cone_anchor_price) / InpTradeDuration;
            double current_sl = PositionGetDouble(POSITION_SL);
            double current_tp = PositionGetDouble(POSITION_TP);
            
            current_ev = NormalizeDouble(current_ev, _Digits);
            
            // Nếu EV tiếp tục tăng, update TP cứng tại EV mới 
            if(current_tp != current_ev && current_ev > SymbolInfoDouble(Symbol(), SYMBOL_BID)) {
               trade.PositionModify(PositionGetTicket(i), current_sl, current_ev);
            }
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick() {
   datetime current_time = iTime(Symbol(), Period(), 0);
   if(current_time != last_bar_time) {
      last_bar_time = current_time;
      
      if(cone_active) {
         cone_age++;
         if(cone_age > InpTradeDuration) {
            cone_active = false;
         }
      }
      
      if(!cone_active) {
         CheckNewCone(1);
      }
      else {
         // Tính toán EV và -1Sigma của thanh nến vừa đóng (shift = 1)
         // Cone_age hiện tại là của cây nến mới hình thành (0). 
         // Vậy tuổi của cây nến đã đóng (1) là cone_age - 1. Tối thiểu là 0.
         int prev_age = cone_age - 1;
         if(prev_age < 0) prev_age = 0;
         
         double lower_1 = cone_anchor_price + prev_age * (cone_target_lower - cone_anchor_price) / InpTradeDuration;
         
         double low1 = iLow(Symbol(), Period(), 1);
         double close1 = iClose(Symbol(), Period(), 1);
         
         // Component 2 & 3: Phase Rình Mồi + Nhồi / Xác Nhận
         // Giá đâm xuống dưới Lower (-1σ) và đóng nến rút râu lên vào lại trong Nón.
         if(low1 < lower_1 && close1 > lower_1) {
            
            if(!trade_opened_for_cone && PositionsTotal() == 0) {
               
               double ask = SymbolInfoDouble(Symbol(), SYMBOL_ASK);
               
               // Component 4: Quản Trị Khủng Hoảng - Stop Loss
               double sl = NormalizeDouble(low1, _Digits);
               
               // Component 5: Trả Về Giá Trị Thực - Take Profit
               double expected_current_ev = cone_anchor_price + cone_age * (cone_target_ev - cone_anchor_price) / InpTradeDuration;
               double tp = NormalizeDouble(expected_current_ev, _Digits);
               
               if(trade.Buy(InpFixLot, Symbol(), ask, sl, tp, "Monte Carlo Cone Buy")) {
                  trade_opened_for_cone = true;
                  
                  // Trực quan hóa Arrow Buy Signal
                  string sig_name = cone_id_str + "_BuySig_" + IntegerToString(cone_age);
                  ObjectCreate(0, sig_name, OBJ_ARROW_BUY, 0, iTime(Symbol(), Period(), 1), low1 - 10 * Point());
                  ObjectSetInteger(0, sig_name, OBJPROP_COLOR, ClrSignalBuy);
                  ObjectSetInteger(0, sig_name, OBJPROP_WIDTH, 2);
                  ObjectSetString(0, sig_name, OBJPROP_TOOLTIP, "Giao cắt Hồi Quy (" + DoubleToString(lower_1, _Digits) + ")");
               }
            }
         }
         
         // Duy trì trailing TP bám theo EV line đối với lệnh Mua đang giữ
         TrailingTPtoEV();
      }
   }
}
//+------------------------------------------------------------------+
