//+------------------------------------------------------------------+
//|                                                          nr7.mq5 |
//|                                  Copyright 2024, Vu (Antigravity)|
//+------------------------------------------------------------------+
#property copyright "Vu - Generated by AI"
#property link      "https://antigravity.ide"
#property version   "1.00"
#property description "NR7 Breakout - Toby Crabel"
#property description "Narrow Range 7 + EMA50 Filter + Bar-by-Bar Trailing"

#include <Trade\Trade.mqh>
CTrade trade;

//--- inputs
input group "=== General Settings ==="
input double InpFixLot          = 0.01;    // Fixed Lot Size
input ulong  InpMagicNumber     = 55555;   // Magic Number
input int    InpSlippage         = 3;       // Slippage (points)

input group "=== NR7 Detection ==="
input int    InpNRPeriod         = 7;       // Narrow Range Period (bars)

input group "=== Trend Filter ==="
input int    InpEMAPeriod        = 50;      // EMA Period (Trend Filter)

input group "=== Entry Settings ==="
input double InpEntryPadPips     = 2.0;     // Entry Pad above/below NR7 (pips)
input bool   InpAddSpread        = true;    // Add Spread to Buy Stop

input group "=== Stop Loss ==="
input double InpSLPadPips        = 2.0;     // SL Pad below NR7 Low / above NR7 High (pips)

input group "=== Trailing Stop ==="
input double InpTrailPadPips     = 1.0;     // Trailing SL Pad (pips)

input group "=== Pending Order Management ==="
input int    InpPendingExpBars   = 3;       // Cancel pending after N bars (0=no cancel)

input group "=== Risk Settings ==="
input double InpMaxLossUSD       = 0;       // Max Floating Loss ($, 0=off)

input group "=== Display Settings ==="
input color  ClrBuySignal        = clrDodgerBlue;    // Buy Signal Color
input color  ClrSellSignal       = clrOrangeRed;     // Sell Signal Color
input color  ClrNR7Box           = clrGold;           // NR7 Highlight Color
input color  ClrEMA              = clrMagenta;        // EMA50 Color
input color  ClrSLLine           = clrCrimson;        // Stop Loss Line Color
input color  ClrTrailLine        = clrLime;           // Trailing SL Color

//--- Indicator handles
int    ema_handle = INVALID_HANDLE;

//--- Global variables
datetime g_lastBarTime      = 0;
datetime g_pendingPlacedBar = 0;
ulong    g_pendingTicket    = 0;

//+------------------------------------------------------------------+
//| Convert pips to price distance                                   |
//+------------------------------------------------------------------+
double PipsToPrice(double pips) {
   int digits = (int)SymbolInfoInteger(Symbol(), SYMBOL_DIGITS);
   if(digits == 5 || digits == 3)
      return pips * 10.0 * SymbolInfoDouble(Symbol(), SYMBOL_POINT);
   else
      return pips * SymbolInfoDouble(Symbol(), SYMBOL_POINT);
}

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit() {
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   trade.SetTypeFilling(ORDER_FILLING_IOC);
   
   ema_handle = iMA(Symbol(), Period(), InpEMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   
   if(ema_handle == INVALID_HANDLE) {
      Print("[NR7] Error creating EMA handle");
      return(INIT_FAILED);
   }
   
   Print("=== NR7 Breakout EA Initialized ===");
   Print("NR Period: ", InpNRPeriod,
         " | EMA Filter: ", InpEMAPeriod,
         " | Entry Pad: ", InpEntryPadPips, " pips",
         " | SL Pad: ", InpSLPadPips, " pips",
         " | Trail Pad: ", InpTrailPadPips, " pips");
   
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason) {
   if(ema_handle != INVALID_HANDLE) IndicatorRelease(ema_handle);
   ObjectsDeleteAll(0, "NR7_");
}

//+------------------------------------------------------------------+
//| Draw visual helpers                                              |
//+------------------------------------------------------------------+
void DrawDot(string name, datetime t, double price, color clr, int code, int width) {
   ObjectCreate(0, name, OBJ_ARROW, 0, t, price);
   ObjectSetInteger(0, name, OBJPROP_ARROWCODE, code);
   ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, name, OBJPROP_WIDTH, width);
   ObjectSetInteger(0, name, OBJPROP_BACK, true);
}

void DrawText(string name, datetime t, double price, string text, color clr) {
   ObjectCreate(0, name, OBJ_TEXT, 0, t, price);
   ObjectSetString(0, name, OBJPROP_TEXT, text);
   ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, name, OBJPROP_FONTSIZE, 9);
   ObjectSetString(0, name, OBJPROP_FONT, "Arial Bold");
}

void DrawHLine(string name, datetime t1, datetime t2, double price, color clr, int style, int width) {
   ObjectCreate(0, name, OBJ_TREND, 0, t1, price, t2, price);
   ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, name, OBJPROP_STYLE, style);
   ObjectSetInteger(0, name, OBJPROP_WIDTH, width);
   ObjectSetInteger(0, name, OBJPROP_RAY_RIGHT, false);
   ObjectSetInteger(0, name, OBJPROP_BACK, true);
}

void DrawRect(string name, datetime t1, double p1, datetime t2, double p2, color clr) {
   ObjectCreate(0, name, OBJ_RECTANGLE, 0, t1, p1, t2, p2);
   ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, name, OBJPROP_FILL, true);
   ObjectSetInteger(0, name, OBJPROP_BACK, true);
   ObjectSetInteger(0, name, OBJPROP_STYLE, STYLE_SOLID);
   ObjectSetInteger(0, name, OBJPROP_WIDTH, 1);
}

//+------------------------------------------------------------------+
//| Check if we have an open position                                |
//+------------------------------------------------------------------+
bool HasOpenPosition(ENUM_POSITION_TYPE &pos_type) {
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      string symbol = PositionGetSymbol(i);
      ulong magic = PositionGetInteger(POSITION_MAGIC);
      if(symbol == Symbol() && magic == InpMagicNumber) {
         pos_type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
         return true;
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| Check if there is an active pending order                        |
//+------------------------------------------------------------------+
bool HasPendingOrder(ulong &ticket) {
   for(int i = OrdersTotal() - 1; i >= 0; i--) {
      if(OrderSelect(OrderGetTicket(i))) {
         if(OrderGetString(ORDER_SYMBOL) == Symbol() &&
            OrderGetInteger(ORDER_MAGIC) == (long)InpMagicNumber) {
            ticket = OrderGetInteger(ORDER_TICKET);
            return true;
         }
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| Delete pending order                                             |
//+------------------------------------------------------------------+
void DeletePendingOrder(ulong ticket) {
   if(ticket > 0) {
      trade.OrderDelete(ticket);
      g_pendingTicket = 0;
      g_pendingPlacedBar = 0;
      Print("[NR7] Pending order #", ticket, " deleted.");
   }
}

//+------------------------------------------------------------------+
//| Close all positions of this EA                                   |
//+------------------------------------------------------------------+
void CloseAllPositions() {
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      string symbol = PositionGetSymbol(i);
      ulong magic = PositionGetInteger(POSITION_MAGIC);
      if(symbol == Symbol() && magic == InpMagicNumber) {
         ulong ticket = PositionGetTicket(i);
         trade.PositionClose(ticket);
      }
   }
}

//+------------------------------------------------------------------+
//| Get total floating P/L                                           |
//+------------------------------------------------------------------+
double GetTotalFloatingPL() {
   double total_pl = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      string symbol = PositionGetSymbol(i);
      ulong magic = PositionGetInteger(POSITION_MAGIC);
      if(symbol == Symbol() && magic == InpMagicNumber) {
         total_pl += PositionGetDouble(POSITION_PROFIT)
                   + PositionGetDouble(POSITION_SWAP);
      }
   }
   return total_pl;
}

//+------------------------------------------------------------------+
//| Detect NR7: Is bar[1] the narrowest range in [1..InpNRPeriod]?   |
//+------------------------------------------------------------------+
bool IsNR7(double &nr_high, double &nr_low) {
   nr_high = iHigh(Symbol(), Period(), 1);
   nr_low  = iLow(Symbol(), Period(), 1);
   double nr_range = nr_high - nr_low;
   
   // NR range must be > 0 (avoid doji with 0 range causing issues)
   if(nr_range <= 0) return false;
   
   // Compare with bars [2..InpNRPeriod]
   for(int i = 2; i <= InpNRPeriod; i++) {
      double h = iHigh(Symbol(), Period(), i);
      double l = iLow(Symbol(), Period(), i);
      double range_i = h - l;
      
      // If any older bar has equal or smaller range, bar 1 is NOT narrowest
      if(range_i <= nr_range) return false;
   }
   
   return true;  // Bar 1 has the smallest range → NR7 confirmed!
}

//+------------------------------------------------------------------+
//| Modify SL of open position (trailing)                            |
//+------------------------------------------------------------------+
bool TrailStopLoss(double new_sl) {
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      string symbol = PositionGetSymbol(i);
      ulong magic = PositionGetInteger(POSITION_MAGIC);
      if(symbol == Symbol() && magic == InpMagicNumber) {
         ulong ticket = PositionGetTicket(i);
         double current_sl = PositionGetDouble(POSITION_SL);
         double current_tp = PositionGetDouble(POSITION_TP);
         ENUM_POSITION_TYPE ptype = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
         
         // Only trail in profitable direction (1-way rule)
         if(ptype == POSITION_TYPE_BUY && new_sl > current_sl) {
            return trade.PositionModify(ticket, NormalizeDouble(new_sl, _Digits), current_tp);
         }
         if(ptype == POSITION_TYPE_SELL && (current_sl == 0 || new_sl < current_sl)) {
            return trade.PositionModify(ticket, NormalizeDouble(new_sl, _Digits), current_tp);
         }
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick() {
   // === MAX LOSS CHECK (every tick) ===
   if(InpMaxLossUSD > 0) {
      double floatingPL = GetTotalFloatingPL();
      if(floatingPL <= -InpMaxLossUSD) {
         CloseAllPositions();
         Alert("[NR7] MAX LOSS HIT! Floating: $",
               DoubleToString(floatingPL, 2),
               " | Limit: -$", DoubleToString(InpMaxLossUSD, 2));
         return;
      }
   }
   
   // === New bar check ===
   datetime current_time = iTime(Symbol(), Period(), 0);
   if(current_time == g_lastBarTime) return;
   g_lastBarTime = current_time;
   
   // === Get EMA value ===
   double ema_buf[1];
   if(CopyBuffer(ema_handle, 0, 1, 1, ema_buf) <= 0) return;
   double ema50 = ema_buf[0];
   
   // Draw EMA dot
   datetime bar1_time = iTime(Symbol(), Period(), 1);
   DrawDot("NR7_EMA_" + IntegerToString((long)bar1_time), bar1_time, ema50, ClrEMA, 159, 1);
   
   // === Price data ===
   double close1 = iClose(Symbol(), Period(), 1);
   double high1  = iHigh(Symbol(), Period(), 1);
   double low1   = iLow(Symbol(), Period(), 1);
   double ask    = SymbolInfoDouble(Symbol(), SYMBOL_ASK);
   double bid    = SymbolInfoDouble(Symbol(), SYMBOL_BID);
   double spread = ask - bid;
   
   double entry_pad = PipsToPrice(InpEntryPadPips);
   double sl_pad    = PipsToPrice(InpSLPadPips);
   double trail_pad = PipsToPrice(InpTrailPadPips);
   
   // === Position tracking ===
   ENUM_POSITION_TYPE pos_type;
   bool has_position = HasOpenPosition(pos_type);
   
   // ==============================================================
   // BAR-BY-BAR TRAILING STOP (Toby Crabel style)
   // Mỗi khi nến đóng cửa, dời SL lên/xuống theo Low/High nến cũ
   // Quy tắc 1 chiều: chỉ dời theo hướng có lợi
   // ==============================================================
   if(has_position) {
      if(pos_type == POSITION_TYPE_BUY) {
         // Trail SL lên dưới Low của nến vừa đóng cửa (bar 1)
         double new_sl = NormalizeDouble(low1 - trail_pad, _Digits);
         if(TrailStopLoss(new_sl)) {
            Print("[NR7] ▲ Trailing SL (BUY) → ", DoubleToString(new_sl, _Digits),
                  " (Low[1]=", DoubleToString(low1, _Digits), " - pad)");
            
            string trail_name = "NR7_TrailB_" + IntegerToString((long)bar1_time);
            DrawDot(trail_name, bar1_time, new_sl, ClrTrailLine, 159, 1);
         }
      }
      
      if(pos_type == POSITION_TYPE_SELL) {
         // Trail SL xuống trên High của nến vừa đóng cửa (bar 1)
         double new_sl = NormalizeDouble(high1 + trail_pad + spread, _Digits);
         if(TrailStopLoss(new_sl)) {
            Print("[NR7] ▼ Trailing SL (SELL) → ", DoubleToString(new_sl, _Digits),
                  " (High[1]=", DoubleToString(high1, _Digits), " + pad)");
            
            string trail_name = "NR7_TrailS_" + IntegerToString((long)bar1_time);
            DrawDot(trail_name, bar1_time, new_sl, ClrTrailLine, 159, 1);
         }
      }
   }
   
   // === Pending order expiry management ===
   ulong pending_ticket = 0;
   bool has_pending = HasPendingOrder(pending_ticket);
   
   if(has_pending && InpPendingExpBars > 0 && g_pendingPlacedBar > 0) {
      int bars_since = iBarShift(Symbol(), Period(), g_pendingPlacedBar, false);
      if(bars_since >= InpPendingExpBars) {
         Print("[NR7] Pending order expired after ", bars_since, " bars.");
         DeletePendingOrder(pending_ticket);
         has_pending = false;
      }
   }
   
   // If already in position or has pending, skip new setup
   if(has_position || has_pending) return;
   
   // ==============================================================
   // COMPONENT 1: NR7 DETECTION
   // Bar 1 phải có biên độ nhỏ nhất trong 7 nến gần nhất
   // ==============================================================
   double nr_high = 0, nr_low = 0;
   
   if(!IsNR7(nr_high, nr_low)) return;  // Not an NR7 bar → skip
   
   double nr_range = nr_high - nr_low;
   
   Print("[NR7] ★ NR7 Detected! High=", DoubleToString(nr_high, _Digits),
         " Low=", DoubleToString(nr_low, _Digits),
         " Range=", DoubleToString(nr_range, _Digits));
   
   // === Draw NR7 box highlight ===
   datetime bar0_time = iTime(Symbol(), Period(), 0);
   string box_name = "NR7_Box_" + IntegerToString((long)bar1_time);
   DrawRect(box_name, bar1_time, nr_high, bar0_time, nr_low, ClrNR7Box);
   
   string nr_label = "NR7_Label_" + IntegerToString((long)bar1_time);
   DrawText(nr_label, bar1_time, nr_high + entry_pad * 2, "NR7", ClrNR7Box);
   
   // ==============================================================
   // COMPONENT 2: EMA50 TREND FILTER
   // Nến NR7 phải nằm hoàn toàn trên/dưới EMA50
   // ==============================================================
   
   bool above_ema = (nr_low > ema50);     // Toàn bộ nến trên EMA50 → BUY only
   bool below_ema = (nr_high < ema50);    // Toàn bộ nến dưới EMA50 → SELL only
   
   if(!above_ema && !below_ema) {
      Print("[NR7] NR7 cắt ngang EMA50 → Không tín hiệu. EMA50=", DoubleToString(ema50, _Digits));
      return;
   }
   
   // ==============================================================
   // COMPONENT 3 & 4: ENTRY + STOP LOSS
   // Buy Stop / Sell Stop đặt ngoài biên của nến NR7
   // ==============================================================
   
   // ------ BUY SETUP: NR7 nằm trên EMA50 ------
   if(above_ema) {
      double entry_price = NormalizeDouble(nr_high + entry_pad + (InpAddSpread ? spread : 0), _Digits);
      double sl_price    = NormalizeDouble(nr_low - sl_pad, _Digits);
      double risk        = entry_price - sl_price;
      
      if(risk <= 0) {
         Print("[NR7] BUY SETUP rejected: risk <= 0");
         return;
      }
      
      // Ensure Buy Stop is above current Ask
      if(entry_price <= ask) {
         Print("[NR7] BUY SETUP: Price already above NR7 high. Breakout missed.");
         return;
      }
      
      string comment = StringFormat("NR7_Buy|E:%.5f|SL:%.5f", entry_price, sl_price);
      
      if(trade.BuyStop(InpFixLot, entry_price, Symbol(), sl_price, 0,
                       ORDER_TIME_GTC, 0, comment)) {
         g_pendingTicket = trade.ResultOrder();
         g_pendingPlacedBar = current_time;
         
         Print("[NR7] ★ BUY STOP placed at ", DoubleToString(entry_price, _Digits),
               " | SL: ", DoubleToString(sl_price, _Digits),
               " | Risk: ", DoubleToString(risk, _Digits),
               " | EMA50: ", DoubleToString(ema50, _Digits));
         
         // === Visuals ===
         string sig_name = "NR7_BuySig_" + IntegerToString((long)bar1_time);
         ObjectCreate(0, sig_name, OBJ_ARROW_BUY, 0, bar1_time, nr_low - entry_pad);
         ObjectSetInteger(0, sig_name, OBJPROP_COLOR, ClrBuySignal);
         ObjectSetInteger(0, sig_name, OBJPROP_WIDTH, 2);
         
         string trap_name = "NR7_TrapB_" + IntegerToString((long)bar1_time);
         DrawText(trap_name, bar1_time, nr_low - entry_pad * 4,
                  "NR7 ▲ BuyStop", ClrBuySignal);
         
         // Entry line
         string entry_name = "NR7_EntryB_" + IntegerToString((long)bar1_time);
         DrawHLine(entry_name, bar1_time, bar0_time, entry_price, ClrBuySignal, STYLE_DOT, 1);
         
         // SL line
         string sl_name = "NR7_SLB_" + IntegerToString((long)bar1_time);
         DrawHLine(sl_name, bar1_time, bar0_time, sl_price, ClrSLLine, STYLE_DASH, 1);
      }
      else {
         Print("[NR7] BUY STOP failed: ", trade.ResultRetcodeDescription());
      }
   }
   
   // ------ SELL SETUP: NR7 nằm dưới EMA50 ------
   if(below_ema) {
      double entry_price = NormalizeDouble(nr_low - entry_pad, _Digits);
      double sl_price    = NormalizeDouble(nr_high + sl_pad + (InpAddSpread ? spread : 0), _Digits);
      double risk        = sl_price - entry_price;
      
      if(risk <= 0) {
         Print("[NR7] SELL SETUP rejected: risk <= 0");
         return;
      }
      
      // Ensure Sell Stop is below current Bid
      if(entry_price >= bid) {
         Print("[NR7] SELL SETUP: Price already below NR7 low. Breakout missed.");
         return;
      }
      
      string comment = StringFormat("NR7_Sell|E:%.5f|SL:%.5f", entry_price, sl_price);
      
      if(trade.SellStop(InpFixLot, entry_price, Symbol(), sl_price, 0,
                        ORDER_TIME_GTC, 0, comment)) {
         g_pendingTicket = trade.ResultOrder();
         g_pendingPlacedBar = current_time;
         
         Print("[NR7] ★ SELL STOP placed at ", DoubleToString(entry_price, _Digits),
               " | SL: ", DoubleToString(sl_price, _Digits),
               " | Risk: ", DoubleToString(risk, _Digits),
               " | EMA50: ", DoubleToString(ema50, _Digits));
         
         // === Visuals ===
         string sig_name = "NR7_SellSig_" + IntegerToString((long)bar1_time);
         ObjectCreate(0, sig_name, OBJ_ARROW_SELL, 0, bar1_time, nr_high + entry_pad);
         ObjectSetInteger(0, sig_name, OBJPROP_COLOR, ClrSellSignal);
         ObjectSetInteger(0, sig_name, OBJPROP_WIDTH, 2);
         
         string trap_name = "NR7_TrapS_" + IntegerToString((long)bar1_time);
         DrawText(trap_name, bar1_time, nr_high + entry_pad * 4,
                  "NR7 ▼ SellStop", ClrSellSignal);
         
         // Entry line
         string entry_name = "NR7_EntryS_" + IntegerToString((long)bar1_time);
         DrawHLine(entry_name, bar1_time, bar0_time, entry_price, ClrSellSignal, STYLE_DOT, 1);
         
         // SL line
         string sl_name = "NR7_SLS_" + IntegerToString((long)bar1_time);
         DrawHLine(sl_name, bar1_time, bar0_time, sl_price, ClrSLLine, STYLE_DASH, 1);
      }
      else {
         Print("[NR7] SELL STOP failed: ", trade.ResultRetcodeDescription());
      }
   }
}

//+------------------------------------------------------------------+
//| Trade event handler - log when pending triggers                   |
//+------------------------------------------------------------------+
void OnTradeTransaction(const MqlTradeTransaction &trans,
                        const MqlTradeRequest &request,
                        const MqlTradeResult &result) {
   if(trans.type == TRADE_TRANSACTION_DEAL_ADD) {
      if(HistoryDealSelect(trans.deal)) {
         ulong deal_magic = HistoryDealGetInteger(trans.deal, DEAL_MAGIC);
         if(deal_magic == InpMagicNumber) {
            ENUM_DEAL_ENTRY entry_type = (ENUM_DEAL_ENTRY)HistoryDealGetInteger(trans.deal, DEAL_ENTRY);
            if(entry_type == DEAL_ENTRY_IN) {
               double deal_price = HistoryDealGetDouble(trans.deal, DEAL_PRICE);
               double deal_vol   = HistoryDealGetDouble(trans.deal, DEAL_VOLUME);
               ENUM_DEAL_TYPE deal_type = (ENUM_DEAL_TYPE)HistoryDealGetInteger(trans.deal, DEAL_TYPE);
               
               string direction = (deal_type == DEAL_TYPE_BUY) ? "BUY" : "SELL";
               Print("[NR7] ✔ ", direction, " triggered at ", DoubleToString(deal_price, _Digits),
                     " | Vol: ", DoubleToString(deal_vol, 2));
               
               g_pendingTicket = 0;
               g_pendingPlacedBar = 0;
            }
         }
      }
   }
   
   if(trans.type == TRADE_TRANSACTION_ORDER_DELETE) {
      if(trans.order == g_pendingTicket) {
         Print("[NR7] Pending order #", g_pendingTicket, " was cancelled.");
         g_pendingTicket = 0;
         g_pendingPlacedBar = 0;
      }
   }
}
//+------------------------------------------------------------------+
