//+------------------------------------------------------------------+
//|                                           RangeBreakoutEA_v2.mq5 |
//| Auto-generated by Assistant                                      |
//+------------------------------------------------------------------+
#property copyright "AlgoPoint / Converted to EA"
#property link      ""
#property version   "1.00"

#include <Trade\Trade.mqh>
CTrade trade;

//--- Cài đặt cơ bản
input string               Settings_Base        = "=== CÀI ĐẶT CƠ BẢN ===";
input double               InpLotSize           = 0.01;         // Khối lượng (Lot Size)
input ulong                InpMagicNumber       = 778899;       // Magic Number

//--- Component 1: Bộ Lọc Xu Hướng (The Macro Filter)
input string               Settings_Trend       = "=== BỘ LỌC XU HƯỚNG ===";
input ENUM_TIMEFRAMES      InpFilterTimeframe   = PERIOD_D1;    // Khung thời gian Xu hướng (D1)
input int                  InpEMAPeriod         = 100;          // Chu kỳ EMA Filter

//--- Component 2: Logic Range
input string               Settings_Range       = "=== LOGIC RANGE DETECTOR ===";
input ENUM_TIMEFRAMES      InpRangeTimeframe    = PERIOD_H1;    // Khung thời gian Range (H1)
input int                  InpRangePeriod       = 20;           // Số nến để tính biên độ hộp
input int                  InpAvgPeriod         = 100;          // Số nến trung bình
input double               InpThreshold         = 0.85;         // Hệ số nén
input double               InpOverlapPct        = 0.60;         // Tỷ lệ overlap (%)
input int                  InpMinGap            = 5;            // Khoảng cách overlap tối thiểu

//--- Component 3: Quản trị Rủi ro (ATR Stop Loss)
input string               Settings_Risk        = "=== STOP LOSS & TRAILING ===";
input int                  InpATRPeriod         = 14;           // Chu kỳ ATR
input double               InpSLMultiplier      = 1.5;          // Hệ số SL theo ATR
input int                  InpTrailEMAPeriod    = 21;           // Chu kỳ EMA dùng để Trailing TP

//--- Handles
int h_ema_filter;
int h_atr;
int h_ema_trail;

//+------------------------------------------------------------------+
//| Helper func: Range calculation                                   |
//+------------------------------------------------------------------+
double CalcBarRange(ENUM_TIMEFRAMES tf, int bar, int period)
{
   double high[], low[];
   ArraySetAsSeries(high, true);
   ArraySetAsSeries(low, true);
   if(CopyHigh(_Symbol, tf, bar, period, high) < period) return 0;
   if(CopyLow(_Symbol, tf, bar, period, low) < period) return 0;
   
   int hi_idx = ArrayMaximum(high);
   int lo_idx = ArrayMinimum(low);
   return high[hi_idx] - low[lo_idx];
}

//+------------------------------------------------------------------+
//| Overlap check for Range Detection                                |
//+------------------------------------------------------------------+
double CalcOverlapRatio(ENUM_TIMEFRAMES tf, int bar, int period, int min_gap)
{
   double high[], low[];
   ArraySetAsSeries(high, true);
   ArraySetAsSeries(low, true);
   if(CopyHigh(_Symbol, tf, bar, period, high) < period) return 0;
   if(CopyLow(_Symbol, tf, bar, period, low) < period) return 0;
   
   int cnt = period;
   if(cnt <= min_gap) return 0.0;
   
   int revisited = 0;
   
   for(int j = 0; j < cnt; j++)
   {
      double h_j = high[j];
      double l_j = low[j];
      bool has_distant_overlap = false;
      
      for(int k = 0; k < cnt; k++)
      {
         if(MathAbs(k - j) < min_gap) continue;
         
         if(low[k] <= h_j && high[k] >= l_j)
         {
            has_distant_overlap = true;
            break;
         }
      }
      if(has_distant_overlap) revisited++;
   }
   
   return (double)revisited / cnt;
}

//+------------------------------------------------------------------+
//| Get highest/lowest of current period                             |
//+------------------------------------------------------------------+
void GetRangeExtremes(ENUM_TIMEFRAMES tf, int bar, int period, double &range_high, double &range_low)
{
   range_high = 0; range_low = 0;
   double high[], low[];
   ArraySetAsSeries(high, true);
   ArraySetAsSeries(low, true);
   if(CopyHigh(_Symbol, tf, bar, period, high) < period) return;
   if(CopyLow(_Symbol, tf, bar, period, low) < period) return;
   
   int hi_idx = ArrayMaximum(high);
   int lo_idx = ArrayMinimum(low);
   
   range_high = high[hi_idx];
   range_low = low[lo_idx];
}

//+------------------------------------------------------------------+
//| Draw visual range box                                            |
//+------------------------------------------------------------------+
void DrawRangeBox(datetime time1, double price1, datetime time2, double price2)
{
   string name = "Current_RangeBox";
   if(ObjectFind(0, name) < 0)
   {
      ObjectCreate(0, name, OBJ_RECTANGLE, 0, time1, price1, time2, price2);
      ObjectSetInteger(0, name, OBJPROP_BACK, true);
      ObjectSetInteger(0, name, OBJPROP_FILL, false); // Viền hộp chứ không fill
   }
   ObjectSetInteger(0, name, OBJPROP_TIME, 0, time1);
   ObjectSetDouble(0, name, OBJPROP_PRICE, 0, price1);
   ObjectSetInteger(0, name, OBJPROP_TIME, 1, time2);
   ObjectSetDouble(0, name, OBJPROP_PRICE, 1, price2);
   ObjectSetInteger(0, name, OBJPROP_COLOR, clrOrange);
   ObjectSetInteger(0, name, OBJPROP_STYLE, STYLE_SOLID);
   ObjectSetInteger(0, name, OBJPROP_WIDTH, 2);
}

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   trade.SetExpertMagicNumber(InpMagicNumber);
   
   h_ema_filter = iMA(_Symbol, InpFilterTimeframe, InpEMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   h_atr        = iATR(_Symbol, InpRangeTimeframe, InpATRPeriod);
   h_ema_trail  = iMA(_Symbol, InpRangeTimeframe, InpTrailEMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   
   if(h_ema_filter == INVALID_HANDLE || h_atr == INVALID_HANDLE || h_ema_trail == INVALID_HANDLE)
   {
      Print("Failed to initialize indicators");
      return INIT_FAILED;
   }
   
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| New Bar check                                                    |
//+------------------------------------------------------------------+
bool IsNewBar(ENUM_TIMEFRAMES tf)
{
   static datetime last_time = 0;
   datetime current_time = iTime(_Symbol, tf, 0);
   if(current_time != last_time)
   {
      if(last_time == 0)
      {
         last_time = current_time;
         return false;
      }
      last_time = current_time;
      return true;
   }
   return false;
}

//+------------------------------------------------------------------+
//| Main logic tick                                                  |
//+------------------------------------------------------------------+
void OnTick()
{
   // Manage Trailing stop via EMA 21 every tick for precision
   ManageEMATrailingStop();
   
   // Create signals and pending orders only on new candle
   if(!IsNewBar(InpRangeTimeframe)) return;
   
   double ema_filter_arr[], atr_arr[];
   if(CopyBuffer(h_ema_filter, 0, 1, 1, ema_filter_arr) <= 0) return;
   if(CopyBuffer(h_atr, 0, 1, 1, atr_arr) <= 0) return;
   
   double ema_filter = ema_filter_arr[0];
   double current_atr = atr_arr[0];
   
   // --- Khung D1 Filter
   double close_current = iClose(_Symbol, InpFilterTimeframe, 1);
   bool is_bullish = close_current > ema_filter;
   bool is_bearish = close_current < ema_filter;
   
   // --- Range Detection Logic ---
   double current_range = CalcBarRange(InpRangeTimeframe, 1, InpRangePeriod);
   
   double sum_range = 0;
   for(int i = 0; i < InpAvgPeriod; i++)
   {
      sum_range += CalcBarRange(InpRangeTimeframe, 1 + i, InpRangePeriod);
   }
   double avg_range = sum_range / InpAvgPeriod;
   
   bool cond_squeeze = false;
   if(avg_range > 0) cond_squeeze = (current_range < avg_range * InpThreshold);
   
   double overlap = CalcOverlapRatio(InpRangeTimeframe, 1, InpRangePeriod, InpMinGap);
   bool cond_overlap = (overlap >= InpOverlapPct);
   
   bool is_ranging = cond_squeeze && cond_overlap;
   
   int pos_count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == InpMagicNumber) pos_count++;
   }

   // --- Placing Pending Orders ---
   if(pos_count == 0)
   {
      // Remove stale orders first
      for(int i = OrdersTotal() - 1; i >= 0; i--)
      {
         ulong pkt = OrderGetTicket(i);
         if(OrderGetString(ORDER_SYMBOL) == _Symbol && OrderGetInteger(ORDER_MAGIC) == InpMagicNumber)
         {
             trade.OrderDelete(pkt);
         }
      }
       
      if(is_ranging)
      {
         double r_high, r_low;
         GetRangeExtremes(InpRangeTimeframe, 1, InpRangePeriod, r_high, r_low);
         
         double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
         double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
         double stoplevel = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL) * _Point;
         if(stoplevel == 0) stoplevel = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD) * _Point * 2;
         
         if(is_bullish && r_high > 0)
         {
            double entry_price = NormalizeDouble(r_high, _Digits);
            double stop_loss = NormalizeDouble(entry_price - (InpSLMultiplier * current_atr), _Digits);
            
            if(ask < entry_price - stoplevel)
            {
               trade.BuyStop(InpLotSize, entry_price, _Symbol, stop_loss, 0, ORDER_TIME_GTC, 0, "Range Breakout Buy");
            }
         }
         else if(is_bearish && r_low > 0)
         {
            double entry_price = NormalizeDouble(r_low, _Digits);
            double stop_loss = NormalizeDouble(entry_price + (InpSLMultiplier * current_atr), _Digits);
            
            if(bid > entry_price + stoplevel)
            {
               trade.SellStop(InpLotSize, entry_price, _Symbol, stop_loss, 0, ORDER_TIME_GTC, 0, "Range Breakout Sell");
            }
         }
         
         // Vẽ hộp Range
         datetime t1 = iTime(_Symbol, InpRangeTimeframe, InpRangePeriod);
         datetime t2 = iTime(_Symbol, InpRangeTimeframe, 0);
         DrawRangeBox(t1, r_high, t2, r_low);
      }
      else
      {
         // Xóa hộp nếu không còn nằm trong Range và không có vị thế mở
         ObjectDelete(0, "Current_RangeBox");
      }
   }
   else
   {
       // If we have an open position, delete any remaining pending limit/stop orders
      for(int i = OrdersTotal() - 1; i >= 0; i--)
      {
         ulong pkt = OrderGetTicket(i);
         if(OrderGetString(ORDER_SYMBOL) == _Symbol && OrderGetInteger(ORDER_MAGIC) == InpMagicNumber)
         {
             trade.OrderDelete(pkt);
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Manage EMA Trailing Stop                                         |
//+------------------------------------------------------------------+
void ManageEMATrailingStop()
{
   double ema_trail_arr[];
   // Get shift 1 for stable EMA Trailing (using closed candle)
   if(CopyBuffer(h_ema_trail, 0, 1, 1, ema_trail_arr) <= 0) return;
   double ema_trail = ema_trail_arr[0];
   
   double stoplevel = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL) * _Point;
   if(stoplevel == 0) stoplevel = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD) * _Point * 2;
   
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(PositionGetString(POSITION_SYMBOL) == _Symbol && PositionGetInteger(POSITION_MAGIC) == InpMagicNumber)
      {
         ENUM_POSITION_TYPE type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
         double current_sl = PositionGetDouble(POSITION_SL);
         
         if(type == POSITION_TYPE_BUY)
         {
            double new_sl = NormalizeDouble(ema_trail, _Digits);
            // Only trail up: if new_sl is higher than current SL and further than stoplevel from BID
            if(current_sl == 0 || new_sl > current_sl + _Point)
            {
               double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
               if(new_sl <= bid - stoplevel)
               {
                  trade.PositionModify(ticket, new_sl, 0);
               }
               else if (new_sl >= bid) // Passed price, trigger market close manually as virtual TP
               {
                  trade.PositionClose(ticket);
               }
            }
         }
         else if(type == POSITION_TYPE_SELL)
         {
            double new_sl = NormalizeDouble(ema_trail, _Digits);
            // Only trail down: if new_sl is lower than current SL and further than stoplevel from ASK
            if(current_sl == 0 || new_sl < current_sl - _Point)
            {
               double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
               if(new_sl >= ask + stoplevel)
               {
                  trade.PositionModify(ticket, new_sl, 0);
               }
               else if (new_sl <= ask) // Passed price, trigger market close manually as virtual TP
               {
                  trade.PositionClose(ticket);
               }
            }
         }
      }
   }
}
