//+------------------------------------------------------------------+
//|                                         Volatility Breakout.mq5  |
//|                                  Copyright 2024, Vu (Antigravity)|
//+------------------------------------------------------------------+
#property copyright "Vu - Generated by AI"
#property link      "https://antigravity.ide"
#property version   "2.00"
#property description "Volatility Breakout (VBO) - Larry Williams Style"
#property description "Session Open ± K×Range | Session-based timing"
#property description "Uses EU/US Session Open instead of Daily 00:00"

#include <Trade\Trade.mqh>
CTrade trade;

//--- Session selection enum
enum ENUM_SESSION_TYPE {
   SESSION_FRANKFURT = 0,  // Frankfurt Open (07:00 GMT)
   SESSION_LONDON   = 1,  // London Open (08:00 GMT)
   SESSION_NEWYORK  = 2   // New York Open (13:00 GMT)
};

//--- inputs
input group "=== General Settings ==="
input double InpFixLot        = 0.01;    // Fixed Lot Size
input ulong  InpMagicNumber   = 33333;   // Magic Number
input int    InpSlippage       = 3;       // Slippage (points)

input group "=== VBO Strategy ==="
input double InpK             = 0.25;    // K Factor (0.25-0.5)
input bool   InpSLAtOpen      = false;   // SL at Session Open (true) or opposite pending (false)
input double InpRRRatio       = 2.0;     // R:R Ratio for Dynamic TP (e.g. 2.0 = 1:2)

input group "=== Session Settings ==="
input ENUM_SESSION_TYPE InpSessionType = SESSION_FRANKFURT;  // Session Open to use
input int    InpGMTOffset     = 2;       // Broker/Server GMT Offset (e.g. 2 for GMT+2)
input int    InpCloseHour     = 23;      // Force close Hour (server time)
input int    InpCloseMinute   = 55;      // Force close Minute

input group "=== Risk Settings ==="
input double InpMaxLossUSD    = 0;       // Max Floating Loss ($, 0=off)

input group "=== Display Settings ==="
input color  ClrBuyEntry      = clrDodgerBlue;   // Buy Entry Level
input color  ClrSellEntry     = clrOrangeRed;    // Sell Entry Level
input color  ClrSessionOpen   = clrWhite;         // Session Open Level
input color  ClrSLLine        = clrCrimson;       // Stop Loss Line
input color  ClrTPLine        = clrLimeGreen;     // Take Profit Line
input color  ClrInfo          = clrGold;           // Info Text

//--- Global state
datetime g_lastSetupTime   = 0;        // Track which session we already set up
double   g_sessionOpen     = 0;        // Session open price (pivot)
double   g_yesterdayRange  = 0;        // Yesterday's D1 range
double   g_buyLevel        = 0;        // Buy Stop level
double   g_sellLevel       = 0;        // Sell Stop level
ulong    g_buyTicket       = 0;        // Buy Stop ticket
ulong    g_sellTicket      = 0;        // Sell Stop ticket
bool     g_orderTriggered  = false;    // A pending has been triggered this session
bool     g_setupDone       = false;    // Setup done for current session

//+------------------------------------------------------------------+
//| Get session name string                                          |
//+------------------------------------------------------------------+
string GetSessionName() {
   switch(InpSessionType) {
      case SESSION_FRANKFURT: return "Frankfurt";
      case SESSION_LONDON:    return "London";
      case SESSION_NEWYORK:   return "New York";
   }
   return "Unknown";
}

//+------------------------------------------------------------------+
//| Get session open hour in GMT                                     |
//+------------------------------------------------------------------+
int GetSessionGMTHour() {
   switch(InpSessionType) {
      case SESSION_FRANKFURT: return 7;   // 07:00 GMT
      case SESSION_LONDON:    return 8;   // 08:00 GMT
      case SESSION_NEWYORK:   return 13;  // 13:00 GMT (8:00 AM EST)
   }
   return 7;
}

//+------------------------------------------------------------------+
//| Get session open hour in server time                             |
//+------------------------------------------------------------------+
int GetSessionServerHour() {
   int gmt_hour = GetSessionGMTHour();
   int server_hour = gmt_hour + InpGMTOffset;
   // Wrap around midnight
   if(server_hour >= 24) server_hour -= 24;
   if(server_hour < 0)   server_hour += 24;
   return server_hour;
}

//+------------------------------------------------------------------+
//| Get the session open datetime for today (server time)            |
//+------------------------------------------------------------------+
datetime GetSessionOpenTime() {
   MqlDateTime dt;
   TimeCurrent(dt);
   dt.hour = GetSessionServerHour();
   dt.min  = 0;
   dt.sec  = 0;
   return StructToTime(dt);
}

//+------------------------------------------------------------------+
//| Check if current time is at or past session open                 |
//+------------------------------------------------------------------+
bool IsSessionOpenTime() {
   MqlDateTime dt;
   TimeCurrent(dt);
   int session_hour = GetSessionServerHour();
   // Trigger on the exact session open hour (minute 0)
   return (dt.hour == session_hour && dt.min == 0);
}

//+------------------------------------------------------------------+
//| Check if current time is past session open (for late setup)      |
//+------------------------------------------------------------------+
bool IsPastSessionOpen() {
   MqlDateTime dt;
   TimeCurrent(dt);
   int session_hour = GetSessionServerHour();
   return (dt.hour > session_hour || (dt.hour == session_hour && dt.min > 0));
}

//+------------------------------------------------------------------+
//| Get the session open price from M1 candle data                   |
//| Finds the M1 candle at the exact session open time               |
//+------------------------------------------------------------------+
double GetSessionOpenPrice() {
   datetime session_time = GetSessionOpenTime();
   
   // Method 1: Try to find exact M1 bar at session open time
   int bar_index = iBarShift(Symbol(), PERIOD_M1, session_time, false);
   if(bar_index >= 0 && bar_index < 1440) {  // Within last 24h of M1 bars
      datetime bar_time = iTime(Symbol(), PERIOD_M1, bar_index);
      // Check the bar is reasonably close (within 5 minutes)
      if(MathAbs((int)(bar_time - session_time)) <= 300) {
         double price = iOpen(Symbol(), PERIOD_M1, bar_index);
         if(price > 0) return price;
      }
   }
   
   // Method 2: Fallback - use current price if we're right at session open
   MqlDateTime dt;
   TimeCurrent(dt);
   int session_hour = GetSessionServerHour();
   if(dt.hour == session_hour && dt.min <= 1) {
      // We're at session open, use current bid as session open
      double bid = SymbolInfoDouble(Symbol(), SYMBOL_BID);
      if(bid > 0) return bid;
   }
   
   // Method 3: Last resort fallback - search nearby M1 bars
   for(int i = 0; i < 10; i++) {
      datetime bar_time = iTime(Symbol(), PERIOD_M1, i);
      MqlDateTime bar_dt;
      TimeToStruct(bar_time, bar_dt);
      if(bar_dt.hour == session_hour && bar_dt.min == 0) {
         double price = iOpen(Symbol(), PERIOD_M1, i);
         if(price > 0) return price;
      }
   }
   
   return 0;  // Failed
}

//+------------------------------------------------------------------+
int OnInit() {
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   trade.SetTypeFilling(ORDER_FILLING_IOC);
   
   int server_hour = GetSessionServerHour();
   
   Print("=== Volatility Breakout EA v2.0 - SESSION BASED ===");
   Print("Session: ", GetSessionName(), " Open (",
         IntegerToString(GetSessionGMTHour()), ":00 GMT → ",
         IntegerToString(server_hour), ":00 Server)");
   Print("K Factor: ", DoubleToString(InpK, 2),
         " | Close at: ", IntegerToString(InpCloseHour), ":",
         StringFormat("%02d", InpCloseMinute),
         " | SL at: ", (InpSLAtOpen ? "Session Open" : "Opposite Pending"));
   Print("Broker GMT Offset: GMT+", IntegerToString(InpGMTOffset));
   
   // Reset setup flag for today
   g_setupDone = false;
   g_lastSetupTime = 0;
   
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
void OnDeinit(const int reason) {
   ObjectsDeleteAll(0, "VBO_");
}

//+------------------------------------------------------------------+
void DrawHLine(string name, double price, color clr, int style, string tooltip) {
   if(ObjectFind(0, name) < 0) {
      ObjectCreate(0, name, OBJ_HLINE, 0, 0, price);
      ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
      ObjectSetInteger(0, name, OBJPROP_STYLE, style);
      ObjectSetInteger(0, name, OBJPROP_WIDTH, 1);
      ObjectSetInteger(0, name, OBJPROP_BACK, true);
      ObjectSetString(0, name, OBJPROP_TOOLTIP, tooltip);
      ObjectSetString(0, name, OBJPROP_TEXT, tooltip);
   } else {
      ObjectSetDouble(0, name, OBJPROP_PRICE, price);
   }
}

//+------------------------------------------------------------------+
bool HasOpenPosition(ENUM_POSITION_TYPE &pos_type) {
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      string symbol = PositionGetSymbol(i);
      if(symbol == Symbol() && PositionGetInteger(POSITION_MAGIC) == (long)InpMagicNumber) {
         pos_type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
         return true;
      }
   }
   return false;
}

void CloseAllPositions() {
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      string symbol = PositionGetSymbol(i);
      if(symbol == Symbol() && PositionGetInteger(POSITION_MAGIC) == (long)InpMagicNumber)
         trade.PositionClose(PositionGetTicket(i));
   }
}

void DeleteAllPendings() {
   for(int i = OrdersTotal() - 1; i >= 0; i--) {
      if(OrderSelect(OrderGetTicket(i))) {
         if(OrderGetString(ORDER_SYMBOL) == Symbol() &&
            OrderGetInteger(ORDER_MAGIC) == (long)InpMagicNumber) {
            trade.OrderDelete(OrderGetInteger(ORDER_TICKET));
         }
      }
   }
   g_buyTicket = 0;
   g_sellTicket = 0;
}

double GetTotalFloatingPL() {
   double total = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      string symbol = PositionGetSymbol(i);
      if(symbol == Symbol() && PositionGetInteger(POSITION_MAGIC) == (long)InpMagicNumber)
         total += PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);
   }
   return total;
}

bool HasPendingOrder(ulong check_ticket) {
   for(int i = OrdersTotal() - 1; i >= 0; i--) {
      if(OrderSelect(OrderGetTicket(i))) {
         if(OrderGetInteger(ORDER_TICKET) == (long)check_ticket)
            return true;
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| Get start-of-day datetime for today (for daily reset tracking)   |
//+------------------------------------------------------------------+
datetime GetStartOfDay() {
   MqlDateTime dt;
   TimeCurrent(dt);
   dt.hour = 0; dt.min = 0; dt.sec = 0;
   return StructToTime(dt);
}

//+------------------------------------------------------------------+
void OnTick() {
   // === MAX LOSS CHECK (every tick) ===
   if(InpMaxLossUSD > 0) {
      double pl = GetTotalFloatingPL();
      if(pl <= -InpMaxLossUSD) {
         CloseAllPositions();
         DeleteAllPendings();
         Alert("[VBO] MAX LOSS HIT! $", DoubleToString(pl, 2));
         return;
      }
   }
   
   // === FORCE CLOSE (every tick) ===
   MqlDateTime now_dt;
   TimeCurrent(now_dt);
   
   if(now_dt.hour == InpCloseHour && now_dt.min >= InpCloseMinute) {
      ENUM_POSITION_TYPE pt;
      if(HasOpenPosition(pt)) {
         Print("[VBO] ⏰ Force close at ", IntegerToString(InpCloseHour), ":",
               StringFormat("%02d", InpCloseMinute), " - Session end!");
         CloseAllPositions();
      }
      // Also cancel any remaining pendings
      DeleteAllPendings();
      return;
   }
   
   // === CANCEL OPPOSITE PENDING when one triggers (every tick) ===
   ENUM_POSITION_TYPE pos_type;
   bool has_position = HasOpenPosition(pos_type);
   
   if(has_position && !g_orderTriggered) {
      g_orderTriggered = true;
      
      // Cancel the opposite pending
      if(pos_type == POSITION_TYPE_BUY && g_sellTicket > 0) {
         if(HasPendingOrder(g_sellTicket)) {
            trade.OrderDelete(g_sellTicket);
            Print("[VBO] BUY triggered → Sell Stop #", g_sellTicket, " cancelled.");
         }
         g_sellTicket = 0;
      }
      if(pos_type == POSITION_TYPE_SELL && g_buyTicket > 0) {
         if(HasPendingOrder(g_buyTicket)) {
            trade.OrderDelete(g_buyTicket);
            Print("[VBO] SELL triggered → Buy Stop #", g_buyTicket, " cancelled.");
         }
         g_buyTicket = 0;
      }
   }
   
   // ==============================================================
   // DAILY RESET: Reset setup flag at start of new calendar day
   // ==============================================================
   datetime today = GetStartOfDay();
   if(today != g_lastSetupTime) {
      // New calendar day → allow new session setup
      g_setupDone = false;
   }
   
   // ==============================================================
   // SESSION SETUP: At session open time, calculate & place pendings
   // ==============================================================
   if(g_setupDone) return;  // Already set up for this session
   
   int session_hour = GetSessionServerHour();
   
   // Only trigger setup when we reach the session open hour
   if(now_dt.hour < session_hour) return;  // Too early, wait for session
   
   // We're at or past session open hour → do the setup
   g_setupDone = true;
   g_lastSetupTime = today;
   g_orderTriggered = false;
   
   // Clean up old visuals
   ObjectsDeleteAll(0, "VBO_");
   
   // Cancel any leftover pendings
   DeleteAllPendings();
   
   // === COMPONENT 1: Measure yesterday's D1 Range ===
   double yesterday_high = iHigh(Symbol(), PERIOD_D1, 1);
   double yesterday_low  = iLow(Symbol(), PERIOD_D1, 1);
   g_yesterdayRange = yesterday_high - yesterday_low;
   
   if(g_yesterdayRange <= 0) {
      Print("[VBO] Yesterday range = 0. Skipping today.");
      return;
   }
   
   // === COMPONENT 2: Get Session Open Price ===
   g_sessionOpen = GetSessionOpenPrice();
   
   if(g_sessionOpen <= 0) {
      Print("[VBO] Cannot get ", GetSessionName(), " session open price. Skipping.");
      g_setupDone = false;  // Allow retry
      return;
   }
   
   // === Calculate entry levels ===
   double offset = InpK * g_yesterdayRange;
   double spread = SymbolInfoDouble(Symbol(), SYMBOL_ASK) - SymbolInfoDouble(Symbol(), SYMBOL_BID);
   
   g_buyLevel  = NormalizeDouble(g_sessionOpen + offset, _Digits);
   g_sellLevel = NormalizeDouble(g_sessionOpen - offset, _Digits);
   
   // SL levels
   double buy_sl, sell_sl;
   double buy_sl_dist, sell_sl_dist;  // SL distance in price
   if(InpSLAtOpen) {
      // SL at Session Open → distance = K × Range
      buy_sl  = NormalizeDouble(g_sessionOpen, _Digits);
      sell_sl = NormalizeDouble(g_sessionOpen, _Digits);
      buy_sl_dist  = g_buyLevel - buy_sl;    // = offset = K × Range
      sell_sl_dist = sell_sl - g_sellLevel;   // = offset = K × Range
   } else {
      // SL at opposite pending level → distance = 2 × K × Range
      buy_sl  = NormalizeDouble(g_sellLevel, _Digits);
      sell_sl = NormalizeDouble(g_buyLevel, _Digits);
      buy_sl_dist  = g_buyLevel - buy_sl;    // = 2 × offset
      sell_sl_dist = sell_sl - g_sellLevel;   // = 2 × offset
   }
   
   // === Dynamic TP: TP = Entry ± (R:R × SL_distance) ===
   double buy_tp  = NormalizeDouble(g_buyLevel  + InpRRRatio * buy_sl_dist, _Digits);
   double sell_tp = NormalizeDouble(g_sellLevel - InpRRRatio * sell_sl_dist, _Digits);
   
   string sess_name = GetSessionName();
   
   Print("[VBO] ══════════════════════════════════════");
   Print("[VBO] ★ SESSION SETUP: ", sess_name, " Open");
   Print("[VBO]   Session Time: ", IntegerToString(GetSessionGMTHour()),
         ":00 GMT (", IntegerToString(session_hour), ":00 Server)");
   Print("[VBO]   Yesterday Range: ", DoubleToString(g_yesterdayRange, _Digits),
         " (H=", DoubleToString(yesterday_high, _Digits),
         " L=", DoubleToString(yesterday_low, _Digits), ")");
   Print("[VBO]   ", sess_name, " Open: ", DoubleToString(g_sessionOpen, _Digits));
   Print("[VBO]   K Factor:    ", DoubleToString(InpK, 2),
         " → Offset: ", DoubleToString(offset, _Digits));
   Print("[VBO]   R:R Ratio:   1:", DoubleToString(InpRRRatio, 1));
   Print("[VBO]   Buy Stop:    ", DoubleToString(g_buyLevel, _Digits),
         " | SL: ", DoubleToString(buy_sl, _Digits),
         " | TP: ", DoubleToString(buy_tp, _Digits),
         " (SL dist: ", DoubleToString(buy_sl_dist, _Digits),
         ", TP dist: ", DoubleToString(InpRRRatio * buy_sl_dist, _Digits), ")");
   Print("[VBO]   Sell Stop:   ", DoubleToString(g_sellLevel, _Digits),
         " | SL: ", DoubleToString(sell_sl, _Digits),
         " | TP: ", DoubleToString(sell_tp, _Digits),
         " (SL dist: ", DoubleToString(sell_sl_dist, _Digits),
         ", TP dist: ", DoubleToString(InpRRRatio * sell_sl_dist, _Digits), ")");
   
   // === Place Buy Stop ===
   double ask = SymbolInfoDouble(Symbol(), SYMBOL_ASK);
   if(g_buyLevel > ask) {
      string cmt = StringFormat("VBO_%s|K=%.2f|RR=%.1f|Buy", sess_name, InpK, InpRRRatio);
      if(trade.BuyStop(InpFixLot, g_buyLevel, Symbol(), buy_sl, buy_tp,
                       ORDER_TIME_GTC, 0, cmt)) {
         g_buyTicket = trade.ResultOrder();
         Print("[VBO] ✔ Buy Stop placed #", g_buyTicket,
               " | TP: ", DoubleToString(buy_tp, _Digits));
      } else {
         Print("[VBO] ✗ Buy Stop FAILED: ", trade.ResultRetcodeDescription());
      }
   } else {
      Print("[VBO] Buy level already below Ask. Skipping Buy Stop.");
   }
   
   // === Place Sell Stop ===
   double bid = SymbolInfoDouble(Symbol(), SYMBOL_BID);
   if(g_sellLevel < bid) {
      string cmt = StringFormat("VBO_%s|K=%.2f|RR=%.1f|Sell", sess_name, InpK, InpRRRatio);
      if(trade.SellStop(InpFixLot, g_sellLevel, Symbol(), sell_sl, sell_tp,
                        ORDER_TIME_GTC, 0, cmt)) {
         g_sellTicket = trade.ResultOrder();
         Print("[VBO] ✔ Sell Stop placed #", g_sellTicket,
               " | TP: ", DoubleToString(sell_tp, _Digits));
      } else {
         Print("[VBO] ✗ Sell Stop FAILED: ", trade.ResultRetcodeDescription());
      }
   } else {
      Print("[VBO] Sell level already above Bid. Skipping Sell Stop.");
   }
   
   // === Draw visual levels ===
   ChartSetInteger(0, CHART_SHOW_OBJECT_DESCR, true);
   
   DrawHLine("VBO_Open", g_sessionOpen, ClrSessionOpen, STYLE_DOT,
             sess_name + " Open: " + DoubleToString(g_sessionOpen, _Digits));
   DrawHLine("VBO_BuyLv", g_buyLevel, ClrBuyEntry, STYLE_SOLID,
             StringFormat("Buy Stop: %s (%s Open + %.2f×Range)",
                          DoubleToString(g_buyLevel, _Digits), sess_name, InpK));
   DrawHLine("VBO_SellLv", g_sellLevel, ClrSellEntry, STYLE_SOLID,
             StringFormat("Sell Stop: %s (%s Open - %.2f×Range)",
                          DoubleToString(g_sellLevel, _Digits), sess_name, InpK));
   DrawHLine("VBO_BuySL", buy_sl, ClrSLLine, STYLE_DASH,
             "Buy SL: " + DoubleToString(buy_sl, _Digits));
   DrawHLine("VBO_SellSL", sell_sl, ClrSLLine, STYLE_DASH,
             "Sell SL: " + DoubleToString(sell_sl, _Digits));
   DrawHLine("VBO_BuyTP", buy_tp, ClrTPLine, STYLE_DASHDOTDOT,
             StringFormat("Buy TP: %s (R:R 1:%.1f)",
                          DoubleToString(buy_tp, _Digits), InpRRRatio));
   DrawHLine("VBO_SellTP", sell_tp, ClrTPLine, STYLE_DASHDOTDOT,
             StringFormat("Sell TP: %s (R:R 1:%.1f)",
                          DoubleToString(sell_tp, _Digits), InpRRRatio));
}

//+------------------------------------------------------------------+
void OnTradeTransaction(const MqlTradeTransaction &trans,
                        const MqlTradeRequest &request,
                        const MqlTradeResult &result) {
   if(trans.type == TRADE_TRANSACTION_DEAL_ADD) {
      if(HistoryDealSelect(trans.deal)) {
         if(HistoryDealGetInteger(trans.deal, DEAL_MAGIC) == (long)InpMagicNumber) {
            ENUM_DEAL_ENTRY entry = (ENUM_DEAL_ENTRY)HistoryDealGetInteger(trans.deal, DEAL_ENTRY);
            if(entry == DEAL_ENTRY_IN) {
               double price = HistoryDealGetDouble(trans.deal, DEAL_PRICE);
               ENUM_DEAL_TYPE dtype = (ENUM_DEAL_TYPE)HistoryDealGetInteger(trans.deal, DEAL_TYPE);
               string dir = (dtype == DEAL_TYPE_BUY) ? "BUY" : "SELL";
               Print("[VBO] ✔ ", dir, " triggered at ", DoubleToString(price, _Digits),
                     " (", GetSessionName(), " session)");
            }
         }
      }
   }
}
//+------------------------------------------------------------------+
