//+------------------------------------------------------------------+
//|                                                  Turtle Soup.mq5 |
//|                                  Copyright 2024, Vu (Antigravity)|
//+------------------------------------------------------------------+
#property copyright "Vu - Generated by AI"
#property link      "https://antigravity.ide"
#property version   "1.00"
#property description "Turtle Soup - Linda Bradford Raschke"
#property description "Mean Reversion: Fade false breakouts of 20-bar Donchian Channel"

#include <Trade\Trade.mqh>
CTrade trade;

//--- inputs
input group "=== General Settings ==="
input double InpFixLot          = 0.01;    // Fixed Lot Size
input ulong  InpMagicNumber     = 77777;   // Magic Number
input int    InpSlippage         = 3;       // Slippage (points)

input group "=== Donchian Channel ==="
input int    InpDonchianPeriod   = 20;      // Donchian Period (bars)
input int    InpMinAge           = 4;       // Min Age of High/Low (bars ago)

input group "=== Entry Settings ==="
input double InpBufferPips       = 5.0;     // Buffer from Low20/High20 (pips)
input bool   InpAddSpread        = true;    // Add Spread to Buffer (Buy Side)

input group "=== Risk Settings ==="
input double InpSLPadPips        = 2.0;     // SL Pad below New Low / above New High (pips)
input double InpRR               = 2.0;     // Take Profit R:R Ratio
input double InpMaxLossUSD       = 0;       // Max Floating Loss ($, 0=off)

input group "=== Pending Order Management ==="
input int    InpPendingExpBars   = 5;       // Cancel pending after N bars (0=no cancel)

input group "=== Display Settings ==="
input color  ClrBuySignal        = clrDodgerBlue;   // Buy Signal Color
input color  ClrSellSignal       = clrOrangeRed;    // Sell Signal Color
input color  ClrDonchianHi       = clrGold;          // Donchian High Color
input color  ClrDonchianLo       = clrDeepSkyBlue;   // Donchian Low Color
input color  ClrSLLine           = clrCrimson;        // Stop Loss Line Color
input color  ClrTPLine           = clrLimeGreen;      // Take Profit Line Color

//--- global variables
datetime g_lastBarTime           = 0;
datetime g_pendingPlacedBar      = 0;       // Bar time when pending was placed
ulong    g_pendingTicket         = 0;       // Ticket of active pending order
bool     g_buySetupActive        = false;   // Active buy trap detected this cycle
bool     g_sellSetupActive       = false;   // Active sell trap detected this cycle

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit() {
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpSlippage);
   trade.SetTypeFilling(ORDER_FILLING_IOC);
   
   Print("=== Turtle Soup EA Initialized ===");
   Print("Donchian Period: ", InpDonchianPeriod,
         " | Min Age: ", InpMinAge,
         " | Buffer: ", InpBufferPips, " pips",
         " | SL Pad: ", InpSLPadPips, " pips",
         " | R:R = 1:", DoubleToString(InpRR, 1));
   
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason) {
   // Clean up chart objects
   ObjectsDeleteAll(0, "TS_");
}

//+------------------------------------------------------------------+
//| Convert pips to price distance                                   |
//+------------------------------------------------------------------+
double PipsToPrice(double pips) {
   int digits = (int)SymbolInfoInteger(Symbol(), SYMBOL_DIGITS);
   // For 5-digit (Forex) or 3-digit (JPY/Gold) brokers
   if(digits == 5 || digits == 3)
      return pips * 10.0 * SymbolInfoDouble(Symbol(), SYMBOL_POINT);
   else
      return pips * SymbolInfoDouble(Symbol(), SYMBOL_POINT);
}

//+------------------------------------------------------------------+
//| Draw visual dot on chart                                         |
//+------------------------------------------------------------------+
void DrawDot(string name, datetime t, double price, color clr, int code, int width) {
   ObjectCreate(0, name, OBJ_ARROW, 0, t, price);
   ObjectSetInteger(0, name, OBJPROP_ARROWCODE, code);
   ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, name, OBJPROP_WIDTH, width);
   ObjectSetInteger(0, name, OBJPROP_BACK, true);
}

//+------------------------------------------------------------------+
//| Draw text label                                                  |
//+------------------------------------------------------------------+
void DrawText(string name, datetime t, double price, string text, color clr) {
   ObjectCreate(0, name, OBJ_TEXT, 0, t, price);
   ObjectSetString(0, name, OBJPROP_TEXT, text);
   ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, name, OBJPROP_FONTSIZE, 9);
   ObjectSetString(0, name, OBJPROP_FONT, "Arial Bold");
}

//+------------------------------------------------------------------+
//| Draw horizontal trend line segment                               |
//+------------------------------------------------------------------+
void DrawHLine(string name, datetime t1, datetime t2, double price, color clr, int style, int width) {
   ObjectCreate(0, name, OBJ_TREND, 0, t1, price, t2, price);
   ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, name, OBJPROP_STYLE, style);
   ObjectSetInteger(0, name, OBJPROP_WIDTH, width);
   ObjectSetInteger(0, name, OBJPROP_RAY_RIGHT, false);
   ObjectSetInteger(0, name, OBJPROP_BACK, true);
}

//+------------------------------------------------------------------+
//| Check if we have an open position                                |
//+------------------------------------------------------------------+
bool HasOpenPosition(ENUM_POSITION_TYPE &pos_type) {
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      string symbol = PositionGetSymbol(i);
      ulong magic = PositionGetInteger(POSITION_MAGIC);
      if(symbol == Symbol() && magic == InpMagicNumber) {
         pos_type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
         return true;
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| Check if there is an active pending order                        |
//+------------------------------------------------------------------+
bool HasPendingOrder(ulong &ticket) {
   for(int i = OrdersTotal() - 1; i >= 0; i--) {
      if(OrderSelect(OrderGetTicket(i))) {
         if(OrderGetString(ORDER_SYMBOL) == Symbol() &&
            OrderGetInteger(ORDER_MAGIC) == (long)InpMagicNumber) {
            ticket = OrderGetInteger(ORDER_TICKET);
            return true;
         }
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| Delete pending order by ticket                                   |
//+------------------------------------------------------------------+
void DeletePendingOrder(ulong ticket) {
   if(ticket > 0) {
      trade.OrderDelete(ticket);
      g_pendingTicket = 0;
      g_pendingPlacedBar = 0;
      Print("[TS] Pending order #", ticket, " deleted.");
   }
}

//+------------------------------------------------------------------+
//| Close all positions of this EA                                   |
//+------------------------------------------------------------------+
void CloseAllPositions() {
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      string symbol = PositionGetSymbol(i);
      ulong magic = PositionGetInteger(POSITION_MAGIC);
      if(symbol == Symbol() && magic == InpMagicNumber) {
         ulong ticket = PositionGetTicket(i);
         trade.PositionClose(ticket);
      }
   }
}

//+------------------------------------------------------------------+
//| Get total floating P/L                                           |
//+------------------------------------------------------------------+
double GetTotalFloatingPL() {
   double total_pl = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      string symbol = PositionGetSymbol(i);
      ulong magic = PositionGetInteger(POSITION_MAGIC);
      if(symbol == Symbol() && magic == InpMagicNumber) {
         total_pl += PositionGetDouble(POSITION_PROFIT)
                   + PositionGetDouble(POSITION_SWAP);
      }
   }
   return total_pl;
}

//+------------------------------------------------------------------+
//| Find 20-bar Donchian High and the bar index where it occurred    |
//| We look at bars [2..InpDonchianPeriod+1] to EXCLUDE bar 1        |
//| Bar 1 is the breakout candle - must be compared separately       |
//+------------------------------------------------------------------+
bool FindDonchianHigh(double &highVal, int &highIdx) {
   highVal = -DBL_MAX;
   highIdx = -1;
   
   for(int i = 2; i <= InpDonchianPeriod + 1; i++) {
      double h = iHigh(Symbol(), Period(), i);
      if(h > highVal) {
         highVal = h;
         highIdx = i;
      }
   }
   return (highIdx > 0);
}

//+------------------------------------------------------------------+
//| Find 20-bar Donchian Low and the bar index where it occurred     |
//| Same range [2..InpDonchianPeriod+1] to exclude breakout bar      |
//+------------------------------------------------------------------+
bool FindDonchianLow(double &lowVal, int &lowIdx) {
   lowVal = DBL_MAX;
   lowIdx = -1;
   
   for(int i = 2; i <= InpDonchianPeriod + 1; i++) {
      double l = iLow(Symbol(), Period(), i);
      if(l < lowVal) {
         lowVal = l;
         lowIdx = i;
      }
   }
   return (lowIdx > 0);
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick() {
   // === MAX LOSS CHECK (every tick) ===
   if(InpMaxLossUSD > 0) {
      double floatingPL = GetTotalFloatingPL();
      if(floatingPL <= -InpMaxLossUSD) {
         CloseAllPositions();
         Alert("[Turtle Soup] MAX LOSS HIT! Floating: $",
               DoubleToString(floatingPL, 2),
               " | Limit: -$", DoubleToString(InpMaxLossUSD, 2));
         return;
      }
   }

   // === New bar check ===
   datetime current_time = iTime(Symbol(), Period(), 0);
   if(current_time == g_lastBarTime) return;
   g_lastBarTime = current_time;
   
   // === Get current price data ===
   double ask    = SymbolInfoDouble(Symbol(), SYMBOL_ASK);
   double bid    = SymbolInfoDouble(Symbol(), SYMBOL_BID);
   double spread = ask - bid;
   double point  = SymbolInfoDouble(Symbol(), SYMBOL_POINT);
   
   double close0 = iClose(Symbol(), Period(), 0);
   double high0  = iHigh(Symbol(), Period(), 0);
   double low0   = iLow(Symbol(), Period(), 0);
   
   // Previous bar data (for SL calculation when breakout detected)
   double close1 = iClose(Symbol(), Period(), 1);
   double high1  = iHigh(Symbol(), Period(), 1);
   double low1   = iLow(Symbol(), Period(), 1);
   datetime bar1_time = iTime(Symbol(), Period(), 1);
   
   // === Position tracking ===
   ENUM_POSITION_TYPE pos_type;
   bool has_position = HasOpenPosition(pos_type);
   
   // === Pending order expiry management ===
   ulong pending_ticket = 0;
   bool has_pending = HasPendingOrder(pending_ticket);
   
   if(has_pending && InpPendingExpBars > 0 && g_pendingPlacedBar > 0) {
      // Count how many bars have passed since pending was placed
      int bars_since = iBarShift(Symbol(), Period(), g_pendingPlacedBar, false);
      if(bars_since >= InpPendingExpBars) {
         Print("[TS] Pending order expired after ", bars_since, " bars.");
         DeletePendingOrder(pending_ticket);
         has_pending = false;
      }
   }
   
   // If already in position or has pending, skip new setup
   if(has_position || has_pending) return;
   
   // ==============================================================
   // COMPONENT 1: THE 20-PERIOD TRAP DETECTION
   // Find Donchian High/Low and verify age >= InpMinAge
   // ==============================================================
   
   double donchian_high = 0, donchian_low = 0;
   int    high_idx = 0, low_idx = 0;
   
   bool found_high = FindDonchianHigh(donchian_high, high_idx);
   bool found_low  = FindDonchianLow(donchian_low, low_idx);
   
   // Draw Donchian levels on chart for visualization
   if(found_high) {
      string hi_name = "TS_DCH_" + IntegerToString((long)bar1_time);
      DrawDot(hi_name, bar1_time, donchian_high, ClrDonchianHi, 159, 1);
   }
   if(found_low) {
      string lo_name = "TS_DCL_" + IntegerToString((long)bar1_time);
      DrawDot(lo_name, bar1_time, donchian_low, ClrDonchianLo, 159, 1);
   }
   
   double buffer_price = PipsToPrice(InpBufferPips);
   double sl_pad       = PipsToPrice(InpSLPadPips);
   
   // ==============================================================
   // BUY SETUP: Price pierces below Low_20 → Fade the false breakdown
   // Condition: 
   //   1. Low_20 was created >= InpMinAge bars ago (not a fresh low)
   //   2. Current bar's low breaks below Low_20
   //   3. Place BUY STOP at Low_20 + buffer + spread
   //   4. SL = New Low (bar that broke) - SL pad
   //   5. TP = Entry + (Entry - SL) * R:R
   // ==============================================================
   if(found_low && low_idx >= InpMinAge) {
      // Check if the PREVIOUS closed bar broke below Low_20
      if(low1 < donchian_low) {
         // === The trap is sprung! Previous bar broke the 20-period low ===
         
         double entry_price = NormalizeDouble(donchian_low + buffer_price + (InpAddSpread ? spread : 0), _Digits);
         double sl_price    = NormalizeDouble(low1 - sl_pad, _Digits);
         double risk        = entry_price - sl_price;
         double tp_price    = NormalizeDouble(entry_price + risk * InpRR, _Digits);
         
         // Validate risk > 0
         if(risk <= 0) {
            Print("[TS] BUY SETUP rejected: risk <= 0. Entry=", entry_price, " SL=", sl_price);
         }
         else {
            // Ensure Buy Stop is ABOVE current Ask (required by broker)
            if(entry_price <= ask) {
               Print("[TS] BUY SETUP: Price already above entry level. Reversal already happened.");
            }
            else {
               string comment = StringFormat("TS_Buy|E:%.5f|SL:%.5f|TP:%.5f|RR:%.1f",
                                              entry_price, sl_price, tp_price, InpRR);
               
               if(trade.BuyStop(InpFixLot, entry_price, Symbol(), sl_price, tp_price, 
                                ORDER_TIME_GTC, 0, comment)) {
                  g_pendingTicket = trade.ResultOrder();
                  g_pendingPlacedBar = current_time;
                  
                  Print("[TS] ★ BUY STOP placed at ", DoubleToString(entry_price, _Digits),
                        " | SL: ", DoubleToString(sl_price, _Digits),
                        " | TP: ", DoubleToString(tp_price, _Digits),
                        " | Low20: ", DoubleToString(donchian_low, _Digits),
                        " | Age: ", low_idx, " bars");
                  
                  // === Visual: Draw entry signal ===
                  string sig_name = "TS_BuySig_" + IntegerToString((long)bar1_time);
                  ObjectCreate(0, sig_name, OBJ_ARROW_BUY, 0, bar1_time, low1 - buffer_price);
                  ObjectSetInteger(0, sig_name, OBJPROP_COLOR, ClrBuySignal);
                  ObjectSetInteger(0, sig_name, OBJPROP_WIDTH, 2);
                  
                  // Draw trap text
                  string trap_name = "TS_TrapB_" + IntegerToString((long)bar1_time);
                  DrawText(trap_name, bar1_time, low1 - buffer_price * 3,
                           "TRAP ▲ BuyStop", ClrBuySignal);
                  
                  // Draw SL line
                  datetime t2 = iTime(Symbol(), Period(), 0);
                  string sl_name = "TS_SLB_" + IntegerToString((long)bar1_time);
                  DrawHLine(sl_name, bar1_time, t2, sl_price, ClrSLLine, STYLE_DASH, 1);
                  
                  // Draw TP line
                  string tp_name = "TS_TPB_" + IntegerToString((long)bar1_time);
                  DrawHLine(tp_name, bar1_time, t2, tp_price, ClrTPLine, STYLE_DASH, 1);
                  
                  // Draw Entry line
                  string entry_name = "TS_EntryB_" + IntegerToString((long)bar1_time);
                  DrawHLine(entry_name, bar1_time, t2, entry_price, ClrBuySignal, STYLE_DOT, 1);
               }
               else {
                  Print("[TS] BUY STOP failed: ", trade.ResultRetcodeDescription());
               }
            }
         }
      }
   }
   
   // ==============================================================
   // SELL SETUP: Price pierces above High_20 → Fade the false breakout
   // Condition:
   //   1. High_20 was created >= InpMinAge bars ago
   //   2. Current bar's high breaks above High_20
   //   3. Place SELL STOP at High_20 - buffer
   //   4. SL = New High (bar that broke) + SL pad + spread
   //   5. TP = Entry - (SL - Entry) * R:R
   // ==============================================================
   if(found_high && high_idx >= InpMinAge) {
      // Check if the PREVIOUS closed bar broke above High_20
      if(high1 > donchian_high) {
         // === The trap is sprung! Previous bar broke the 20-period high ===
         
         double entry_price = NormalizeDouble(donchian_high - buffer_price, _Digits);
         double sl_price    = NormalizeDouble(high1 + sl_pad + (InpAddSpread ? spread : 0), _Digits);
         double risk        = sl_price - entry_price;
         double tp_price    = NormalizeDouble(entry_price - risk * InpRR, _Digits);
         
         // Validate risk > 0
         if(risk <= 0) {
            Print("[TS] SELL SETUP rejected: risk <= 0. Entry=", entry_price, " SL=", sl_price);
         }
         else {
            // Ensure Sell Stop is BELOW current Bid (required by broker)
            if(entry_price >= bid) {
               Print("[TS] SELL SETUP: Price already below entry level. Reversal already happened.");
            }
            else {
               string comment = StringFormat("TS_Sell|E:%.5f|SL:%.5f|TP:%.5f|RR:%.1f",
                                              entry_price, sl_price, tp_price, InpRR);
               
               if(trade.SellStop(InpFixLot, entry_price, Symbol(), sl_price, tp_price,
                                 ORDER_TIME_GTC, 0, comment)) {
                  g_pendingTicket = trade.ResultOrder();
                  g_pendingPlacedBar = current_time;
                  
                  Print("[TS] ★ SELL STOP placed at ", DoubleToString(entry_price, _Digits),
                        " | SL: ", DoubleToString(sl_price, _Digits),
                        " | TP: ", DoubleToString(tp_price, _Digits),
                        " | High20: ", DoubleToString(donchian_high, _Digits),
                        " | Age: ", high_idx, " bars");
                  
                  // === Visual: Draw entry signal ===
                  string sig_name = "TS_SellSig_" + IntegerToString((long)bar1_time);
                  ObjectCreate(0, sig_name, OBJ_ARROW_SELL, 0, bar1_time, high1 + buffer_price);
                  ObjectSetInteger(0, sig_name, OBJPROP_COLOR, ClrSellSignal);
                  ObjectSetInteger(0, sig_name, OBJPROP_WIDTH, 2);
                  
                  // Draw trap text
                  string trap_name = "TS_TrapS_" + IntegerToString((long)bar1_time);
                  DrawText(trap_name, bar1_time, high1 + buffer_price * 3,
                           "TRAP ▼ SellStop", ClrSellSignal);
                  
                  // Draw SL line
                  datetime t2 = iTime(Symbol(), Period(), 0);
                  string sl_name = "TS_SLS_" + IntegerToString((long)bar1_time);
                  DrawHLine(sl_name, bar1_time, t2, sl_price, ClrSLLine, STYLE_DASH, 1);
                  
                  // Draw TP line
                  string tp_name = "TS_TPS_" + IntegerToString((long)bar1_time);
                  DrawHLine(tp_name, bar1_time, t2, tp_price, ClrTPLine, STYLE_DASH, 1);
                  
                  // Draw Entry line
                  string entry_name = "TS_EntryS_" + IntegerToString((long)bar1_time);
                  DrawHLine(entry_name, bar1_time, t2, entry_price, ClrSellSignal, STYLE_DOT, 1);
               }
               else {
                  Print("[TS] SELL STOP failed: ", trade.ResultRetcodeDescription());
               }
            }
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Trade event handler - log when pending triggers                   |
//+------------------------------------------------------------------+
void OnTradeTransaction(const MqlTradeTransaction &trans,
                        const MqlTradeRequest &request,
                        const MqlTradeResult &result) {
   // Detect when our pending order gets triggered
   if(trans.type == TRADE_TRANSACTION_DEAL_ADD) {
      if(trans.order_state == ORDER_STATE_FILLED || trans.type == TRADE_TRANSACTION_DEAL_ADD) {
         // Check if this deal belongs to our EA
         if(HistoryDealSelect(trans.deal)) {
            ulong deal_magic = HistoryDealGetInteger(trans.deal, DEAL_MAGIC);
            if(deal_magic == InpMagicNumber) {
               ENUM_DEAL_ENTRY entry_type = (ENUM_DEAL_ENTRY)HistoryDealGetInteger(trans.deal, DEAL_ENTRY);
               if(entry_type == DEAL_ENTRY_IN) {
                  double deal_price = HistoryDealGetDouble(trans.deal, DEAL_PRICE);
                  double deal_vol   = HistoryDealGetDouble(trans.deal, DEAL_VOLUME);
                  ENUM_DEAL_TYPE deal_type = (ENUM_DEAL_TYPE)HistoryDealGetInteger(trans.deal, DEAL_TYPE);
                  
                  string direction = (deal_type == DEAL_TYPE_BUY) ? "BUY" : "SELL";
                  Print("[TS] ✔ ", direction, " triggered at ", DoubleToString(deal_price, _Digits),
                        " | Vol: ", DoubleToString(deal_vol, 2));
                  
                  // Reset pending tracking
                  g_pendingTicket = 0;
                  g_pendingPlacedBar = 0;
               }
            }
         }
      }
   }
   
   // Detect when pending order is cancelled (externally)
   if(trans.type == TRADE_TRANSACTION_ORDER_DELETE) {
      if(trans.order == g_pendingTicket) {
         Print("[TS] Pending order #", g_pendingTicket, " was cancelled externally.");
         g_pendingTicket = 0;
         g_pendingPlacedBar = 0;
      }
   }
}
//+------------------------------------------------------------------+
